### ISSUE TITLE
Parsoid?

### ISSUE THREAD

**Issue by legoktm** [spencermountain/wtf_wikipedia#1]
Have you looked into the output that Parsoid produces? It converts wikitext into HTML/RDFa (and back!) and is expected to eventually replace the current MediaWiki parser. 

An example is: http://parsoid-lb.eqiad.wikimedia.org/enwiki/Main_Page?oldid=598252063 (API docs at https://www.mediawiki.org/wiki/Parsoid/API.

**Comment by spencermountain** [comment]
added a section to the readme, thanks
