### ISSUE TITLE
doc.html() Abstract Syntax Tree -  Replacement of tree nodes

### ISSUE THREAD

**Issue by niebert** [spencermountain/wtf_wikipedia#102]
Abstract Syntax Tree (AST) does not replace the appropriate tree node data on deeper tree levels.

```html
<div class="section">
<ul>
  <li>function(){return this.data.text||""}</li>
  <li>function(){return ...
```

**Comment by niebert** [comment]
currently no clue for dealing with the output handlers correctly. Need time to understand the origin of the output result. Maybe a `typeof(...)` check for functions could help and create a `switch` may help, but I may be just a temporary problem due to major change on the AST handling?

**Comment by niebert** [comment]
added a proposal AST handling in the GitHub wiki. Some methods might be already implemented and should be reused. Excuse me if I reinvented the wheel for something the is already there in the code.

**Comment by spencermountain** [comment]
gonna merge this with #88
