### ISSUE TITLE
Inline template-replacement

### ISSUE THREAD

**Issue by niebert** [spencermountain/wtf_wikipedia#115]
There is another question I have according to your plans for the output rendering,
The output can be precised defined by a template like [Handlebars](https://handlebarsjs.com/) or Mustache.

An output template will look like
```markdown
## {{title}}
```
in Markdown,
```latex
\subsection{ {{title}} }
```
in LaTeX
```html
<h2>{{title}}</h2>
```
in HTML.

Basic principle of template engine:
* use a template for generation of a compiler function `ast4title`. (only once)
* multiple applications of this compiler function with different JSON `ast4title('html',pMyTitle,pOptions)`.
* `pMyTitle` is a JSON that contains the title in `pMyTitle.title`. The string value of `title` will be replaced by the compiler in the template of the output language `html`,
* the compiled output will be return from the function `my_title_in_html = ast4title('html',pMyTitle,pOptions)`. 
* The first parameter defines the output format.
Iterations over lists are possible with these template engines `foreach` (see Handlebars https://handlebarsjs.com/builtin_helpers.html ) . Does it make sense to you to reduce your work for output rendering  for `wtf_wikipedia` by using the handlebars or other template engines by requiring those NPM modules in `wtf_wikipedia`? Those templates defined the output node handlers for the Abstract Syntax Tree (AST), similar to want you are currently  doning in `src/output`.

This comment might be irrelevant, if you have e.g. some performance befefits from implementing that in the way to have planed it currently in the `dev`-branch.  

Best regards with great appreciations for your work for refactoring `wtf_wikipedia`

**Comment by spencermountain** [comment]
hey, yeah so the goal is more-flexible output formats? I think i understand. It's true that any opinionated things we do will be wrong half-the-time. It would be cool to make this process easier to customize.

When it comes to building-in a generic templating language, it may be easiest for users to use the javascript string-templating stuff, to build-out a perfect output format - ` <h2>${doc.title()}</h2>` etc.

i've been working on [this documentation stuff](https://beta.observablehq.com/@spencermountain/wtf_wikipedia) and that's what i've been doing for that - 
```
  doc.sections().map(s=> `<li>${s.title()}</li>`).join('')
```
and stuff like that.

i like that reveal format you did - and the math stuff is still in there but not yet parsed. It would also be neat to support references in latex/html/md formats somehow

**Comment by niebert** [comment]
I can do it, if you provide citation handler, call when you cite literature in the wiki text. The citation handler needs an unique ID from the list of all collected references from the article. References will be placed at the end of the generated output document unless a reference marker was parsed in the document. If someone wants to use `wtf_wikipedia` as a client side [Book Creator](https://en.wikiversity.org/w/index.php?title=Special:Book&bookcmd=book_creator&referer=3D+Modelling) aggregation of references across multiple downloaded Wiki articles lead to an aggregrated reference list at the end of all articles.

**Comment by niebert** [comment]
Could you give me a quick note, if I can start handling the math code for different output formats and add the reveal output to the current capabilities of `wtf_wikipedia`?

**Comment by spencermountain** [comment]
yeah, you're right. Connecting citation templates back to their sentence would be awesome. Right now it's at the Section level only. This is due to some bad order-of-operations choices I made, seemingly 5 years ago. ;) Changing it will be a little hard.

hey, book-creator is cool. That's a great idea.

yeah, [math formulas](https://en.wikipedia.org/wiki/Help:Displaying_a_formula) are set with `<math></math>` tags, which get obliterated with [a regular expr](https://github.com/spencermountain/wtf_wikipedia/blob/master/src/document/preProcess/kill_xml.js). We'd need to add that information to `section.templates`.

You can see we do the same thing for [<ref>some text</ref>](https://github.com/spencermountain/wtf_wikipedia/blob/master/src/section/references.js#L35) inline references, so it could be the same thing?

both are good challenges, and you're really smart. ;)

**Comment by spencermountain** [comment]
so yeah, if you somehow got `<math>gobbely-gook</math>` into the list of templates on `Section`, I think the math `./output` stuff you did is still there, so we could look at rendering that in html/whatever. That would be really neat stuff.

**Comment by spencermountain** [comment]
ok last one:

latex has built-in support for math-formula rendering right? 

I guess in html we could just add a class name, like this?
```html
<div class="math">gobbel-gook</div>
```

and in markdown, what would you recommend? that mathdown library you used?
cheers

**Comment by niebert** [comment]
Yes as recommended in the wiki, If you alter the wiki recommendation in way that is OK for you, that I will follow that route of implementation and support you.  Would recommend to convert the results of discussion in `issues` into a wiki proposal for implementation, that will serve as guideline for all developers that support you. At the same time we have the documentation ready. Use the `MathJax` syntax for rending math expression as output. With MathJax we can preserve the LaTeX math in HTML output without any need to alter the provide math expression.

**Comment by niebert** [comment]
Math tags are currently parsed at the sentence level in the abstract syntax tree. I guess we will still have the problems of the incompatible grammar of LaTeX within the Math-tags `<math>...</math>` and Wiki markdown. E.g. characters like `:` or `*` can appear as first character in a line and it is from the syntax within the math tags OK. There I so many potential pitfalls due to differences of underlying grammar of LaTeX and Wiki markdown that it would give us many headaches and this requires an ongoing exeptions handling for on the sentence level. The tokenizer at the `preProcess` in the document level will prevent a lot work. I understand partially why you parse the math closer to the leafs of an Abtract Syntax Tree (AST). I would recommend to 
* (1) tokenize at the preProcess in `01-Document` and
* (2) hook back to tokens at the sentence level.
May be I did not understand your way forward properly, but in my understanding of the existing code I guess it is necessary  
* (3) to add a folder in the sentence level with the name `/math`
* (4) and this `/math` folder as usual `toHtml.js`, `toLatex.js` and `toMarkdown.js`  modules.
The functions fetch the formula for the JSON `data` and generate the proper output dependent on the chosen output. 

Could you correct me if I am wrong with the assumptions mentioned above. When lectures and assessments are over, I willing to support you according to the math-handling. It is around end of February.
You mentioned help wanted

**Comment by spencermountain** [comment]
ah nice! good luck with your busy-season.

yeah, solving this to keep the order of <math> and {{math}} templates -  It really is a problem for all templates, you can have this, for example:
```
Toronto is a very cold city in the winter, as you can see: {{HUMUNGOUS-CLIMATE-TEMPLATE}} and it is snowy too.
```
i'd prefer to solve this for all templates, as-opposed to just math and refs, you know? It would be cool to represent the sequence of the document, properly in all cases.

and yeah, as you said, templates need to get parsed-out first, then leave some kinda flag around, so we can insert their data post-hoc.
doable! Just hard ;)

**Comment by spencermountain** [comment]
as of v8 our [4 output formats](https://github.com/spencermountain/wtf_wikipedia/tree/master/plugins) have been split-out into plugins, which may help in your work in wikiversity.
Let me know if there's anything I can do.
