### ISSUE TITLE
Paragraph recognition

### ISSUE THREAD

**Issue by xsedla0k** [spencermountain/wtf_wikipedia#129]
Hi, is there any way for spliting wikipedia text to paragraph? I mean something like to get from "https://en.wikipedia.org/wiki/Tham_Luang_cave_rescue" Only this text:
On Saturday, 23 June 2018, 12 members of the Moo Pa (Wild Boar) soccer team, aged 11–16, and their coach, aged 25, went into the Tham Luang Nang Non cave in Chiang Rai, Thailand, and got trapped deep inside when the entrance was flooded by a sudden downpour.[1] A search was immediately commenced when a ranger of the National Park in Chiang Rai alerted authorities of the missing boys after seeing their unclaimed belongings at the cave entrance.

Now I am getting all text until: Tham Luang cave.

Thanks for answer, Paul

**Comment by spencermountain** [comment]
hi Paul, yeah this is our most-requested feature. Unfortunately it's a little complicated to do, given the way we parse the document, and would effect a number of steps.
This one is on the roadmap, I'll keep the issue open until then.
cheers

**Comment by yanosh-igor** [comment]
Will be good to get sentences, links, images in paragraphs. Similar like we can do with sections.
@spencermountain Do you know any estimates when this feature could be ready? Like this month or this year.

**Comment by spencermountain** [comment]
hi Yanosh, yeah, i agree - it would be cool to be able to do `sections(0).paragraphs()` or whatever.

but yeah, not this month. It's a good idea but has a lot of implications for how the document gets parsed, and then the methods all need to loop-around another abstraction, which is a tough change too

**Comment by tograd** [comment]
I'd like to +1 this one into high-priority

1. It's **very important** when displaying a document that paragraph exists, least you want hard-to-read texts
2. It's literally impossible to algorithmically infer paragraph breakpoints

If you give a little bit more info on what would need to be done to make this happen; I'm sure people smarter than me could offset some of the labor for you

**Comment by niebert** [comment]
Section are split up be sections header. The method `doSection()` is applied on section bodies. Exactly at the method the parsing process should split paragraph. Paragraph splitter could be a regular expression like 
```javascript 
var parRegEx = /\n[\S\s]*\n/g
```
Two newlines with optional enclose blanks, tabs, .... May be we RegEx should be expanded to two or more subsequent newlines.

**Comment by spencermountain** [comment]
paragraphs are now supported end-to-end.
Please try it out in v6
cheers

**Comment by niebert** [comment]
Thank you Spencer,
