### ISSUE TITLE
Too many apostrophes removed along with formatting.

### ISSUE THREAD

**Issue by jacopofar** [spencermountain/wtf_wikipedia#13]
Thanks for the library, it's very useful!

When I run it on the Italian wikipedia, I find text like
>L''''armonium''' o '''armonio''' (in francese, ''harmonium'')

where the first apostrophe is part of the text and the other three are formatting.

The parser have to check that the apostrophes are balanced, the change in the pull request does that.

**Comment by spencermountain** [comment]
fixed by #14 thanks!
