### ISSUE TITLE
Hidden methods and can't actually fetch by id? 

### ISSUE THREAD

**Issue by tograd** [spencermountain/wtf_wikipedia#134]
Love the software. Got some issues;

1. `.thumb()` isn't in the docs (except for an example), are there more hidden methods? is thumb link different from "full size link"? and how would one go about getting on of those since the image object don't seem to keep one for some reason?

2. Fetching by id crashes so hard

```
wtf.fetch(325480, 'en', (err, doc) => {
    console.log(err || doc);
});

>>>>>>>>>>

wtf_wikipedia.min.js:6 Uncaught TypeError: i.map is not a function
    at wtf_wikipedia.min.js:6
    at t.exports (wtf_wikipedia.min.js:6)
    at Function.s.fetch (wtf_wikipedia.min.js:6)
    at Article.componentWillMount (Article.js:20)
    at callComponentWillMount (react-dom.development.js:11508)
    ....etc
```

3. Einstein weird parsing but you seem to be on top of that

**Comment by spencermountain** [comment]
yikes. will look at the id crashing today.

yeah, should list-out the methods of Image, and Infobox in the docs, but to be honest, I think a refactor is a good-idea first. Lots of gnarly bits still.

you can see all the Image methods [here](https://github.com/spencermountain/wtf_wikipedia/blob/master/src/image/Image.js#L38)

**Comment by spencermountain** [comment]
ids work again in 4.6, good find.
will look at improving docs in another iteration
cheers
