### ISSUE TITLE
Support links in Section titles

### ISSUE THREAD

**Issue by tograd** [spencermountain/wtf_wikipedia#135]
`console.log(section[i].data.title);`
```
...
Baptism and temptation
{{anchor|Ministry}} Public ministry
Disciples and followers
{{anchor|Teachings and preachings}} Teachings and miracles
Proclamation as Christ and Transfiguration
...
```

The "alternative spelling" anchor **should** be stripped right? Or are `data` properties considered "raw"?

**Comment by spencermountain** [comment]
which page is that from?
Yeah, this is a good point. We should include both...

that would be a breaking change, so will have to be a v5.

**Comment by tograd** [comment]
sorry, https://en.wikipedia.org/wiki/Jesus

**Comment by spencermountain** [comment]
oh, looks like that's using an [Anchor](https://en.wikipedia.org/wiki/Template:Anchor) template - I reckon we should just remove these.

happy to do it

**Comment by spencermountain** [comment]
just stripped them out in 4.6.0
¯\_(ツ)_/¯
