### ISSUE TITLE
Parser skipping sections

### ISSUE THREAD

**Issue by tograd** [spencermountain/wtf_wikipedia#136]
https://en.wikipedia.org/wiki/Anders_Zorn

Missing sections include Collection, Zorngården, Paintings, Zorn's palette. They are missing from the `.sections()` method but are available in the raw `.wiki` attribute

**Comment by spencermountain** [comment]
whoa, that's a nice wikipedia page!
good find. I'll take a look. Gotta be something with that massive `<gallery>` section

**Comment by spencermountain** [comment]
fixed in 4.6.0
cheers

**Comment by tograd** [comment]
you're amazing, thank you
