### ISSUE TITLE
doc.images gives error 'Cannot read property 'forEach' of undefined at templates.forEach '

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#146]
Hi, I'm trying to get images from this page https://en.wikipedia.org/wiki/Kurmi
and function `doc.images()` throws an error:

`TypeError: Cannot read property 'forEach' of undefined
    at templates.forEach (/app/node_modules/wtf_wikipedia/src/document/Document.js:104:20)
    at Array.forEach (<anonymous>)
    at Document.images (/app/node_modules/wtf_wikipedia/src/document/Document.js:102:22)`

I'm using latest verison 5.0.1.

Looks like `obj` doesn't have any images.

`this.templates().forEach((obj) => {
      if (obj.template === 'gallery') {
        obj.images.forEach((img) => arr.push(img));
      }
    });`

**Comment by spencermountain** [comment]
yikes!
will take a look, thanks.

**Comment by spencermountain** [comment]
got it!
should be fixed in 5.1.0
thanks
