### ISSUE TITLE
Missing data from the templates - Wiktionary 

### ISSUE THREAD

**Issue by HaoCSE** [spencermountain/wtf_wikipedia#149]
---Input---
`var testing = wtf("==Latin==\n\n===Verb===\n{{la-verb-form|cānēsceris}}\n\n# {{inflection of|cānēscō||2|s|pres|pasv|indc|lang=la}}");`

---Output---
I expect that the templates will return a list of data 
(`inflection of` template has these data: cānēscō||2|s|pres|pasv|indc|lang=la)

But the actual result (for "Verb" section): 
`{
      "title": "Verb",
      "depth": 1,
      "sentences": [],
      "templates": [
        {
          "template": "inflection of",
          "data": {
            "lang": "la"
          }
        }
      ]
    }`

The returned data for 'inflection of' is only `"lang": "la"`

So, i need to fingure it out the other ways to solve this.

PS, thanks for this amazing wtf_wikipedia 
Cheers,

**Comment by spencermountain** [comment]
hey Hao, I'm happy to support this `la-verb-form` template.
will add it to the next release
cheers!

**Comment by spencermountain** [comment]
got it.
fixed in 5.1.0
thanks!
