### ISSUE TITLE
<gallery> Mücken/de

### ISSUE THREAD

**Issue by xeladotbe** [spencermountain/wtf_wikipedia#151]
I'm so, so sorry! another german wikitext thing :P 

https://de.wikipedia.org/w/api.php?action=query&redirects=true&prop=revisions&rvprop=content&maxlag=5&format=json&origin=*&titles=M%C3%BCcken

prints:
Culex-female.jpg|Stechmücke Black Fly.png|Kriebelmücke Culicoides-imicola-bloodfeeding.jpg|Gnitzen Tipula oleracea female.jpg|Schnake Chironomus plumosus01.jpg|Zuckmücke Psychodidae.jpg|Schmetterlingsmücke Fly February 2009-2.jpg|Haarmücke Sciara_analis_de.jpg|Trauermücke

**Comment by spencermountain** [comment]
fixed in **5.0.1**
cheers

**Comment by spencermountain** [comment]
oop 5.1.0
