### ISSUE TITLE
Overmatching of 'File' links

### ISSUE THREAD

**Issue by tstibbs** [spencermountain/wtf_wikipedia#153]
The regex for sorting out file links https://github.com/spencermountain/wtf_wikipedia/blob/b7807a46edcef5495fc248b213e80337f2896c80/src/sentence/index.js#L16 seems to be matching some other things as well. Smallest example I can come up with:
```javascript
wtf("[[Fileaway|Fileaway]]").text()
//should return "Fileaway"; actually returns "away"
```
I'm not sure what the fix is here. The `:` after `File` seems to marked as optional - making this non-optional would fix this particular example, but not sure what else it would break.

**Comment by spencermountain** [comment]
whoa! nice find.
yeah, that's me being sloppy, for sure.
will fix this today

**Comment by spencermountain** [comment]
fixed in **5.0.1**

**Comment by spencermountain** [comment]
oop, 5.1.0 i mean

**Comment by tstibbs** [comment]
Awesome, thanks for the fast fix.
