### ISSUE TITLE
Tinnitus / de - missing sentences after list

### ISSUE THREAD

**Issue by xeladotbe** [spencermountain/wtf_wikipedia#157]
`
 wtf("Nach dem Zeitraum der Wahrnehmung eines Tinnitus werden im deutschsprachigen Raum in der Regel [[Krankheitsverlauf|zwei Phasen]] unterschieden:\n* akuter Tinnitus (bis drei Monate)\n* chronischer Tinnitus (über drei Monate)\nIn der Vergangenheit wurde ein Tinnitus, der zwischen drei und sechs Monaten anhielt, auch als [[subakut]] bezeichnet. Bislang gibt es keine wissenschaftliche Grundlage für die Einteilung in zwei bzw. drei Phasen, sie richtet sich lediglich nach Erfahrungswerten. Hierdurch erklären sich die unterschiedlichen Angaben. In der akuten und subakuten Phase kommt es vergleichsweise häufig zu einer spontanen Heilung oder Besserung der Symptome. Je länger der Tinnitus besteht, desto höher ist jedoch die Wahrscheinlichkeit, dass er dauerhaft bestehen bleibt.").plaintext()
`

observed:

> Nach dem Zeitraum der Wahrnehmung eines Tinnitus werden im deutschsprachigen Raum in der Regel zwei Phasen unterschieden:

expected:

missing sentences.

> Nach dem Zeitraum der Wahrnehmung eines Tinnitus werden im deutschsprachigen Raum in der Regel zwei Phasen unterschieden: In der Vergangenheit wurde ein Tinnitus, der zwischen drei und sechs Monaten anhielt, auch als subakut bezeichnet. Bislang gibt es keine wissenschaftliche Grundlage für die Einteilung in zwei bzw. drei Phasen, sie richtet sich lediglich nach Erfahrungswerten. Hierdurch erklären sich die unterschiedlichen Angaben. In der akuten und subakuten Phase kommt es vergleichsweise häufig zu einer spontanen Heilung oder Besserung der Symptome. Je länger der Tinnitus besteht, desto höher ist jedoch die Wahrscheinlichkeit, dass er dauerhaft bestehen bleibt.

**Comment by xeladotbe** [comment]
https://github.com/spencermountain/wtf_wikipedia/blob/master/src/section/list.js#L58

the current line "i" is a list entry, followed by n lines of list entries. at the end "i" should not be increased by sub.length but by sub.length - 1, or am I wrong? I changed it in my local version and got the missing sentences.

**Comment by spencermountain** [comment]
works for me!
thanks.
fixed in 5.1.2
