### ISSUE TITLE
wtf_wikipedia custom markup?

### ISSUE THREAD

**Issue by xeladotbe** [spencermountain/wtf_wikipedia#159]
what do you think about having some "wtf_wikipedia" markups within the parsed wikitext.

right now I'm able to access all sentences, images, lists and tables, but I don't know their natural position.

imagine the following wikitext:

=== section ===\nsome phrases\n* a list entry\n* another list entry\nmore phrases\n* once again, a list entry\n*  with  another list entry

section.plaintext() currently gives me an array with some phrases  and more phrases and section.lists() gives me an array of lists.

if you would add some markers to the parsed sentences (ie. some phrases {{wtf_wikipedia|list:0}} more phrases {{wtf_wikipedia|list:1}}) it would be easy to have something like:

```
section.compile({
  lists: true
});

```
section.plaintext() would than return:
some phrases * list entry * another list entry more phrases * once again, a list entry *  with  another list entry

maybe it would also be possible to add transformers to the compile method:
```

section.compile({
  lists: true,
  transformers: {
    lists: (list) => list.map(entry => entry.toUpperCase())  // all list entries should be in upper case
  }
});
```

section.plaintext() would than return:
some phrases * LIST ENTRY * ANOTHER LIST ENTRY more phrases * ONCE AGAIN A LIST ENTRY  *  WITH ANOTHER LIST ENTRY

**Comment by xeladotbe** [comment]
just saw #88

**Comment by spencermountain** [comment]
thanks Alexander, yeah. This is good thinking. A big refactor is needed to handle this sorta thing, not just in the API, but mostly in the parser, which does parsing ordered by 'danger', so the scary stuff gets parsed first. That's why things are un-ordered in the results.
We will need to do some thinking on this, for sure, but it is clearly something we should do.
