### ISSUE TITLE
HTML table head doesn't adhere to formatting standard 

### ISSUE THREAD

**Issue by j-rausch** [spencermountain/wtf_wikipedia#163]
Hey, 
Thanks for the amazing project!

I noticed that generated HTML files don't adhere to the formatting standard for the `<thead>` element.
Specifically, `<thead>` should only contain 0 or more `<tr>` element for its content (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead).
What's missing right now is an additional `<tr>` element to wrap the individual table columns in the head row.

Here's an example snippet from running `wtf_wikipedia` on the article "Bill Clinton" (https://runkit.com/j-rausch/5b91ab22fefc58001253e67d):
```
...
<table>
  <thead>
    <td>Year</td>
    <td>Office</td>
    <td>District</td>
    <td>Democratic</td>
    <td>Republican</td>
    <td>Other</td>
  </thead>
  <tbody>
  <tr>
    <td>...
```
Whereas it should be:
```
...
<table>
  <thead>
   <tr>
    <td>Year</td>
    <td>Office</td>
    <td>District</td>
    <td>Democratic</td>
    <td>Republican</td>
    <td>Other</td>
   </tr>
  </thead>
  <tbody>
  <tr>
    <td>...
````

It didn't come up in my use-case yet, but the same issue might also occur for the `<tfoot>` element.

Thanks!

**Comment by spencermountain** [comment]
thank you Johannes!
