### ISSUE TITLE
Support longer links

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#167]
Hi, 
Tried to parse page https://en.wikipedia.org/wiki/Fidget_Cube
and have noticed that parser missing 1 link on this page(List_of_highest_funded_crowdfunding_projects)
![2018-09-08_1946](https://user-images.githubusercontent.com/435827/45256529-26afe100-b3a0-11e8-928c-cb1e5a237d3a.png)
![2018-09-08_1947](https://user-images.githubusercontent.com/435827/45256528-26afe100-b3a0-11e8-9778-5090a0f66abe.png)

**Comment by spencermountain** [comment]
hey, yeah looks like it decides the link is too long
to reproduce:
```js
let str = `hello [[List of highest funded crowdfunding projects|highest funded crowdfunding projects]] world`;
console.log(wtf(str).links());
```

**Comment by spencermountain** [comment]
got it in 5.3.0
thanks
