### ISSUE TITLE
Generated html files are missing root elements 

### ISSUE THREAD

**Issue by j-rausch** [spencermountain/wtf_wikipedia#168]
Generated html files currently seem to be missing the `<html>` root element. They should probably be wrapped by an `<html>` and `<body>` element.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body
If a title is added, e.g. in https://github.com/spencermountain/wtf_wikipedia/blob/master/src/document/toHtml.js#L6, it should probably be contained within a `<head>` element.

Current conversion without these elements can be observed here:
https://runkit.com/spencermountain/5b912901c133fe0012ebfc8f

Thanks!

**Comment by spencermountain** [comment]
:fireworks:
