### ISSUE TITLE
Redundant quotes in sentences

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#169]
Hi, noticed redundant quotes on sentenses.
Try to parse topic 1986 in film
![2018-09-11_0955](https://user-images.githubusercontent.com/435827/45343481-b2e12480-b5a9-11e8-8902-94bcec409d3a.png)

**Comment by spencermountain** [comment]
god the top one fixed,
gonna leave the newline thing for now. it's #8 
cheers
