### ISSUE TITLE
Missing infobox

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#174]
Hi, 
Can't get infobox information from this page https://en.wikipedia.org/wiki/Grampa_Simpson
![2018-09-12_1236](https://user-images.githubusercontent.com/435827/45416389-86e8a080-b688-11e8-9bdc-75b171410360.png)

**Comment by spencermountain** [comment]
hey, you can get that with `doc.templates('simpsons character')`
i guess it's not technically an infobox, not sure why
