### ISSUE TITLE
Lists not generated in html conversion

### ISSUE THREAD

**Issue by j-rausch** [spencermountain/wtf_wikipedia#178]
Hi, it seems that for version `5.3.1` several lists/references are not included in the html output.
For example, among others, References/Bibliography/Supreme Court Appointments in https://en.wikipedia.org/wiki/Abraham_Lincoln.
Output: https://runkit.com/j-rausch/abraham-lincoln

At other points, the link text is visible, but the link and header is missing, e.g. in

> ### Organizations
> Abraham Lincoln Association
> Abraham Lincoln Bicentennial Foundation

Organizations (header) and the links for the two following list items are missing.

(This is basically a follow-up to spencermountain/dumpster-dive/issues/58, where the references were displayed, but faulty. Continuing here, since it's actually more of a `wtf_wikipedia` topic).
Cheers

**Comment by spencermountain** [comment]
good find. added-them back into the outputs, in `6.1.0`
cheers!
