### ISSUE TITLE
Support advanced {{convert}} syntax

### ISSUE THREAD

**Issue by AbhinavMadahar** [spencermountain/wtf_wikipedia#18]
Running the following script:

``` javascript
var wtf_wikipedia = require('wtf_wikipedia');
wtf_wikipedia.from_api("Paris", function(page) {
    var parsed = wtf_wikipedia.parse(page); // causes the crash
    console.log(parsed);
});
```

Results in the process taking up 1 GB of RAM, then quickly crashing with the message
`FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
Aborted (core dumped)`

Running Ubuntu 14.04

**Comment by AbhinavMadahar** [comment]
Wait- a simple reinstall fixed it. I'm not sure why though

**Comment by spencermountain** [comment]
whoa!
i'll check it out. that sounds like a scary one

**Comment by spencermountain** [comment]
hey, this is a great bug. i fixed the memory leak, but i've found two more issues using the same sentence:

```
Summer days are usually warm and pleasant with average temperatures hovering between {{convert|15|and|25|°C|°F}}, and a fair amount of sunshine.{{sfn|Lawrence|Gondrand|2010|p=309}} Each year, however, there are a few days where the temperature rises above {{convert|32|C}}. Some years have even witnessed long periods of harsh summer weather, such as the [[2003 European heat wave|heat wave of 2003]] when temperatures exceeded {{convert|30|°C}} for weeks, surged up to {{convert|40|°C}} on some days and seldom cooled down at night.
```
will leave it open till these are fixed. core dump fixed on v0.1.10
thanks

**Comment by AbhinavMadahar** [comment]
Thanks

**Comment by spencermountain** [comment]
for reference, here is the syntax:
`{{convert|15|and|25|°C|°F}}`
https://en.wikipedia.org/wiki/Template:Convert#Ranges_of_values

**Comment by spencermountain** [comment]
this template is supported now
thanks
