### ISSUE TITLE
Cannot read property 'pages' of undefined

### ISSUE THREAD

**Issue by xeladotbe** [spencermountain/wtf_wikipedia#181]
`const d = wtf('2018', 'de'); `

I tried to fetch: https://de.wikipedia.org/wiki/2018

causes Unhandled Rejection at: Promise {
<rejected> TypeError: Cannot read property 'pages' of undefined
at postProcess (/var/task/node_modules/wtf_wikipedia/src/fetch.js:36:38)

root cause is the following check:
```
  var lookup = 'titles';
  if (isNumber.test(title) && title.length > 3) {
    lookup = 'curid';
  }
```

possible fix... hmm... 

`Object.prototype.toString.call(title) === '[object Number]'`

would mean, I have to pass a real number as first argument.

```
wtf(1111111111, 'de');
```

? new option property? 

```
wtf('2018', 'de', {
  pageId: true
});
```

**Comment by spencermountain** [comment]
hey, sorry for missing this. Been getting swamped.
hah, yeah- this looks like it's just me being sloppy.
How would you feel about it listening to `typeof`, so that `'1984'` returns the title, but `1984` returns the pageid.
I like that over using another config param.
that cool?

**Comment by moustachedelait** [comment]
@spencermountain I think that's a really clean solution, that way you don't have to introduce a config object.

Btw, do you need some dev help with this project? I can't promise a ton of time, but wouldn't mind helping out here and there with some issues if you'd like.

**Comment by spencermountain** [comment]
cool, thanks. Of course! I'm working on v6 in the [dev branch](https://github.com/spencermountain/wtf_wikipedia/tree/dev), but hope to release this today, it's moving pretty fast, but will slow-down next week. PRs always welcome. 

v6 inolves a lot of cleanup, which will make jumping in (hopefully), a lot more pleasant. There is a lot of gross regex in here! A tonne of easy wins, all-over the place. The biggest-place that comes to mind is supporting more templates [here](https://github.com/spencermountain/wtf_wikipedia/tree/master/src/templates). I've made a few generic parsers, but there's a lot of random weird templates, and adding a few more would be fantastic to do.

**Comment by spencermountain** [comment]
okay, fetch looks at `typeof` now in `6.0.0`.
Take a look, at let me know if there's any funny-business, as a result.
thanks!

**Comment by spencermountain** [comment]
which error?
please provide steps to reproduce. thanks

**Comment by skipjack** [comment]
I see a similar error (at least the `TypeError: Cannot read property 'pages' of undefined` bit) fairly often, I think it's typically when the fetch fails because I'm making too many calls. Next time this happens, I'll grab the full stack trace and report back here.

Would love to submit a PR so that the tool instead outputs something like `Wikipedia call failed, you may need to slow down.` instead of the hard exception. @spencermountain lmk your thoughts and whether there's another ticket that would be better to track this.

**Comment by spencermountain** [comment]
@skipjack yep, that sounds plausible. i agree
prs welcome
