### ISSUE TITLE
section.json() returns lists as tables

### ISSUE THREAD

**Issue by xeladotbe** [spencermountain/wtf_wikipedia#182]
https://github.com/spencermountain/wtf_wikipedia/blob/master/src/section/toJson.js#L40
this should be data.lists instead of data.table ? :)

**Comment by spencermountain** [comment]
ya! yikes. spotted this already on dev.
ready to release it, but its gonna be a breaking change, so cramming some more things into it.
should release it today.
gonna close this issue, lemme know if you see anything else
