### ISSUE TITLE
[Improvment] can we keep {{Taste|XXX}} ?

### ISSUE THREAD

**Issue by xeladotbe** [spencermountain/wtf_wikipedia#183]
original url: https://de.wikipedia.org/wiki/QWERTZ-Tastaturbelegung 

wikitext: https://de.wikipedia.org/w/api.php?action=query&redirects=true&prop=revisions&rvprop=content&maxlag=5&format=json&origin=*&titles=QWERTZ-Tastaturbelegung

"Taste" seems to be a formatting thing, it looks like a keyboard key. Right now, I just get the following sentence which looks wrong: 

QWERTZ-Tastaturbelegung ist eine Sammelbezeichnung… lateinischen Buchstaben, , , , und  belegt sind.

**Comment by spencermountain** [comment]
added in `v6.0.0`.
