### ISSUE TITLE
Comments in wikitext can lead to big chunks of HTML commented out 

### ISSUE THREAD

**Issue by j-rausch** [spencermountain/wtf_wikipedia#184]
I noticed that wikitext snippets containing `<! --` can cause problems in the generated HTML documents, if they are not closed properly. This can lead to huge chunks of documents missing and/or invalid htmls.

An example:
Snippets such as
 ```
Mech Guard #1, Wealthy Jock || || <ref name="btva"/><!-- <ref>{{cite AV media | at=Closing credits | title=[[Batman Unlimited: Animal Instincts]] | year=2015 | medium=film}}</ref>  -->
```
in https://en.wikipedia.org/w/index.php?title=Matthew_Mercer&action=edit&editintro=Template:BLP_editintro
will lead to this html section, which is missing the comment end:
```
...
 <td><span class="sentence">Mech Guard #1, Wealthy Jock</span></td> 
<td><span class="sentence"></span></td> 
<td><span class="sentence"><! --></span></td>
</tr> 
```
The same problem is caused by lines such as `<!-- NEED ROLE CITED` and `<!-- NEED SOURCE AND NOTABILITY` in the wikitext of the same article.

**Comment by spencermountain** [comment]
fixed in 6.2.0
thanks
