### ISSUE TITLE
Would like the option to define using curid or not

### ISSUE THREAD

**Issue by moustachedelait** [spencermountain/wtf_wikipedia#187]
I ran into an issue when looking for the wikipedia page for 1984

src/fetch.js will recognize 1984 as a curid and then never respond back as it's not actually a valid curid

could we get an option to specify if I want curid or titles search?

**Comment by xeladotbe** [comment]
had the same issue 4 days ago :P #181

**Comment by moustachedelait** [comment]
Got it, I'll follow that issue. thanks!
