### ISSUE TITLE
First bold text doesn't parsed

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#188]
Hi,
I've noticed that bold words at the beginning are not parsing.
Check topic Toyota. Parsed text stats from `, usually shortened to Toyota, is a Japanese multinational automotive manufacturer headquartered in Toyota, Aichi, Japan.`
But should start with `Toyota Motor Corporation, usually shortened to Toyota, is a ..`
<img width="1076" alt="2018-09-21_1721" src="https://user-images.githubusercontent.com/435827/45887004-3cbb9980-bdc3-11e8-9d3e-f27500732740.png">

**Comment by spencermountain** [comment]
thanks, on it.

**Comment by spencermountain** [comment]
got this going in `6.0.0`.

weeee
thanks
