### ISSUE TITLE
Returns wrong infobox image

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#191]
Hi, 
Parse of infobox images(thumbnails) gives the wrong URL.
![2018-09-26_1813](https://user-images.githubusercontent.com/435827/46089937-49bbfc80-c1b8-11e8-8914-40bf9ad13922.png)

**Comment by spencermountain** [comment]
cool, thanks.

**Comment by spencermountain** [comment]
fixed in `6.1.0`
