### ISSUE TITLE
titlecase links

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#192]
Hi, trying to parse page https://en.wikipedia.org/wiki/Pete_Townshend
But noticed that links() return 'the Who' as a link page but real page 'The Who'
and 'the Who' should be in text field.
Looks like camel case is not counted.

![2018-09-27_2040](https://user-images.githubusercontent.com/435827/46164193-0afc7400-c296-11e8-8541-b4b6bee86a91.png)
![2018-09-27_2038](https://user-images.githubusercontent.com/435827/46164194-0afc7400-c296-11e8-97c6-dfd80246e10f.png)

**Comment by spencermountain** [comment]
agreed, good find.

**Comment by spencermountain** [comment]
got it in `6.1.0`
