### ISSUE TITLE
Article New York City doesn't return infoboxes

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#199]
Hi, trying to parse infoboxes for topic `New York City`
but it gives an empty array.
![2018-10-23_2322](https://user-images.githubusercontent.com/435827/47388350-9abd0300-d71a-11e8-8c23-cfe122975dcf.png)

**Comment by spencermountain** [comment]
ha, it was a mal-formed infobox on wikipedia
fixed it.
