### ISSUE TITLE
Table parsing

### ISSUE THREAD

**Issue by rpyaram** [spencermountain/wtf_wikipedia#2]
Great job, It works well. But one thing i noticed is its ignoring tables other than an infobox.

example : http://en.wikipedia.org/wiki/List_of_British_films_of_2014
```
{
  "type": "page",
  "text": {
    "Intro": [
      {
        "text": "A list of British films scheduled for release in 2014",
        "links": [
          {
            "page": "2014 in film",
            "src": "2014"
          }
        ]
      }
    ]
  },
  "categories": [
    "Lists of British films by year|2014",
    "2014 in British cinema|Films",
    "Lists of 2014 films by country or language"
  ],
  "images": [],
  "infobox": {}
}
```
Also, if the table has rowspan or a colspan too, it simply ignores that data.

**Comment by spencermountain** [comment]
hi rpyaram, thanks. this is a great idea.
i'll try this today.

**Comment by spencermountain** [comment]
hey, this functionality is mostly there now, with some issues. Try it out if you get a chance.
cheers
