### ISSUE TITLE
Support for flag templates

### ISSUE THREAD

**Issue by cldellow** [spencermountain/wtf_wikipedia#205]
Hello!

First, thanks for making this - it's great!

I'm doing some parsing with this library and have run into a few templates that I'd like to support. Currently, I "support" them by preprocessing the text before handing it to wtf_wikipedia.

I'd be happy to add it to the core code if you can point me to the right part of the code to add it (or to a previous PR/commit that I could reference)

The ones I'm thinking of in particular:

- [provincial flags for Canada](https://en.wikipedia.org/wiki/Template:Country_data_Canada)
- [state flags for USA](https://en.wikipedia.org/wiki/Template:Country_data_United_States)
- [Flag](https://en.wikipedia.org/wiki/Template:Flag)
- [Flagu](https://en.wikipedia.org/wiki/Template:Flagu)
- [Flagicon](https://en.wikipedia.org/wiki/Template:Flagicon)
- [Flagcountry](https://en.wikipedia.org/wiki/Template:Flagcountry)

I'm not sure I understand fully how Wikipedia's templates work either, which complicates things. :)

I'm also not sure what level of fidelity is desired. For my purposes, all I really care about is getting the text behind template. eg I'm happy for `{{flag|Canada}}` to be parsed as a text string `Canada`.

...but I think the most faithful experience would be to expand it to the image and the link to the Canada page, which is what you'd see if you looked at Wikipedia itself. Just checking -- what is the general preference for handling templates?

**Comment by spencermountain** [comment]
your timing is great Colin. I sorted our missing templates frequency [yesterday](https://github.com/spencermountain/wtf_wikipedia/wiki/Unsupported-Templates). Flags are #1, followed by, what seems, a ton of soccer templates.

Yeah, flags. I'm on board with your ideas. What about trying to somehow map [emoji flags](https://apps.timwhitlock.info/emoji/tables/iso3166) to wikipedia templates? Falling back to either the template name, or `''`, if they don't exist, like you said.

They're mostly used in tables, right? 
Go for it!

**Comment by spencermountain** [comment]
anyways, anything is better than what we have now.
Feel free to implement this as you'd like, most template parsing is [in here](https://github.com/spencermountain/wtf_wikipedia/tree/master/src/templates). There's some available parsering methods you can use if you choose to
cheers

**Comment by spencermountain** [comment]
hey, i've had a go at subbing emoji-flags from the flag templates on dev branch. It's kind of weird.

Haven't added provincial/state ones, [this](https://blog.emojipedia.org/us-state-flag-emojis-now-possible/) doesn't render well on chrome. figure it's better to return `''` for those for now..

feedback welcome

**Comment by cldellow** [comment]
Cool! Sorry for ghosting on this - I probably won't have time until the holidays to do any significant open source stuff.

Is it kind of weird, or kind of cool? :) I guess it depends on the spirit of this library. On the other hand, I like that they're (theoretically) a well-supported standard, and in any event, since it links to the target page, automated uses (that don't want to translate from understand emojis to map to Wikipedia pages) are easily supported, too.

**Comment by spencermountain** [comment]
this looks like it's supported in `v7`
here's a demo https://runkit.com/spencermountain/5c05d4f35ce3a000137a172c
cheers!

**Comment by cldellow** [comment]
You're the best! Thanks!
