### ISSUE TITLE
Wrong sentence parsed for topic Lil' Kim

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#207]
Hi, trying to parse topic Lil' Kim but getting a wrong first sentence.

![2018-10-31_1119](https://user-images.githubusercontent.com/435827/47778727-2678f580-dd00-11e8-8fda-f5279cf4afef.png)

![2018-10-31_1121](https://user-images.githubusercontent.com/435827/47778764-355fa800-dd00-11e8-80ca-dda87f3c2eef.png)

**Comment by spencermountain** [comment]
nice one, looks like there's a humungous `<ref>` that gets mis-parsed
will take a look.

**Comment by yanosh-igor** [comment]
Similar issue with topic https://en.wikipedia.org/wiki/Robert_De_Niro
```
On June 10, 2018, while introducing a performance by Bruce Springsteen of his song "My Hometown" at the 72nd Tony Awards, De Niro brought the audience to a standing ovation with this denunciation of President Trump:

A day later, in front of a crowd in Toronto, he apologized to Canadian Prime Minister Justin Trudeau for President Trump's "idiotic behavior".
```
![2018-10-31_1628](https://user-images.githubusercontent.com/435827/47794909-16760b80-dd2a-11e8-8d57-50fee5224796.png)
