### ISSUE TITLE
Missing hyphens article "Sylvia Kristel"

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#209]
Hi, I'm trying to parse topic "Sylvia Kristel" and noticed that some punctuation signs are missing.
There are missing hypens in the text. 
https://en.wikipedia.org/wiki/Sylvia_Kristel

![2018-11-06_1246](https://user-images.githubusercontent.com/435827/48059623-5faedb00-e1c2-11e8-9c7f-dd881cd92846.png)
![2018-11-06_1247](https://user-images.githubusercontent.com/435827/48059625-60477180-e1c2-11e8-81ac-8112bfe8214b.png)

**Comment by spencermountain** [comment]
looks like the `{{spaced ndash}}` template
cheers

**Comment by spencermountain** [comment]
fixed in `6.3.0`
