### ISSUE TITLE
Support for random articles

### ISSUE THREAD

**Issue by alator21** [spencermountain/wtf_wikipedia#213]
Is there support for getting a [random article](https://en.wikipedia.org/wiki/Wikipedia:Random)?

**Comment by spencermountain** [comment]
yeah, i like that idea
i could add a `.random()` that returns and parses a page
for reference, here's the method call

https://en.wikipedia.org/w/api.php?format=json&action=query&generator=random&grnnamespace=0&prop=revisions&rvprop=content&grnlimit=1&rvslots=main

**Comment by alator21** [comment]
@spencermountain  Thank you.

**Comment by spencermountain** [comment]
hey @alator21 this works now, in `v7.0.0`, check it out here
https://runkit.com/spencermountain/5c05d37f0104420012c8c8f7
thanks
