### ISSUE TITLE
Support {{NBA roster statistics start}}

### ISSUE THREAD

**Issue by ivan-kuzma-scelex** [spencermountain/wtf_wikipedia#214]
Hello, trying to parse https://en.wikipedia.org/wiki/2016_NBA_Finals and found styles in plain-text output.

![output](https://user-images.githubusercontent.com/41302223/48972032-6eebb080-f02b-11e8-991d-b9a7697e2b0d.png)
![page1](https://user-images.githubusercontent.com/41302223/48972033-6eebb080-f02b-11e8-81b7-4f856443b2f2.png)

Could you please tell how this can be avoided.

**Comment by spencermountain** [comment]
hi Ivan, I believe this is fixed now, on `7.1.1`
cheers
