### ISSUE TITLE
Links text joined with another

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#224]
Hi, parsing topic `Randy Johnson` and found that links text returned wrong.
It returns text `List of Major League Basebalimmaculate inning` 
![2018-12-18_1358](https://user-images.githubusercontent.com/435827/50152755-34dd9980-02cd-11e9-86c9-cc740e38f45c.png)
![2018-12-18_1401](https://user-images.githubusercontent.com/435827/50152871-89811480-02cd-11e9-883e-62673c78d9b7.png)

**Comment by spencermountain** [comment]
thanks, got it in `7.2.0`
