### ISSUE TITLE
Can't parse image

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#229]
Hi, trying to get 2 images from topic https://en.wikipedia.org/wiki/Timothy_Stoen
But getting only 1. Couldn't get an image with California map.

![2018-12-19_2037](https://user-images.githubusercontent.com/435827/50240689-11e6de80-03ce-11e9-957f-10fc706d1473.png)
![2018-12-19_2040](https://user-images.githubusercontent.com/435827/50240811-730eb200-03ce-11e9-833b-0360c77bd576.png)

**Comment by spencermountain** [comment]
yeah, that's svg those ones are rendered client-side

https://en.wikipedia.org/wiki/Template:Location_map_many

you can get the data for that template, and render it, but you'll need a geo projection ->svg library

let me know if you have any luck with this
