### ISSUE TITLE
Why limit regex whitespace replace to 0-500 instances?

### ISSUE THREAD

**Issue by ianwalter** [spencermountain/wtf_wikipedia#23]
For example here: https://github.com/spencermountain/wtf_wikipedia/blob/3ea64f841c30c80d784c0614f15805cdb1c1864f/src/kill_xml.js#L5
It causing a sentence that has a long citation spanning multiple lines to get cut off. I can submit a PR with a test if desired.

**Comment by spencermountain** [comment]
hi Ian, thanks for the help. You're right, and those should probably be increased.
I think they're just defensive against sloppy/invalid wikiscript, so they don't destroy the whole page.
happy to pull a pr, to whatever you'd like it as
cheers

**Comment by ianwalter** [comment]
Cool thanks, let me play around a little more so I can figure out what a sensible value would be and then I can create a PR.

**Comment by spencermountain** [comment]
hey Ian, just increased this to 750 - couldn't find any longer than that, though I'm sure they're out there.
lemme know
`v0.8.6`
