### ISSUE TITLE
Get a random article from specific category

### ISSUE THREAD

**Issue by alator21** [spencermountain/wtf_wikipedia#238]
Can i get a random article from a specific category? I know there is the .random() method but can i use a parameter so i can limit the results like [randomArticleFromCategoryArts](https://en.wikipedia.org/wiki/Special:RandomInCategory/Arts)?

**Comment by spencermountain** [comment]
hey Rafael, i don't see that as an option [here](https://www.mediawiki.org/wiki/API:Random).
I'd recommend fetching them all and doing a `Math.random()` on the results.

**Comment by alator21** [comment]
@spencermountain Isn't namespace exactly that?

**Comment by spencermountain** [comment]
nah, that's for templates and things
please read [the docs](https://en.wikipedia.org/wiki/Wikipedia:Namespace)
