### ISSUE TITLE
Parsing nested double curly brace item fails

### ISSUE THREAD

**Issue by ianwalter** [spencermountain/wtf_wikipedia#24]
Parsing broke on whatever this is: `{{nowrap|{{small|(1995–present)}}}}`
Will attempt to fix and create a PR.

**Comment by spencermountain** [comment]
ohgod!
thanks!

**Comment by spencermountain** [comment]
hey, i think fixed this. I'm gonna add some better unit tests before i publish an update.
will let you know when she's up
cheers

**Comment by spencermountain** [comment]
fixed in `0.8.7`
