### ISSUE TITLE
Image caption redundant characters

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#240]
Hi, @spencermountain,
Some image captions has `]]` at the end.

Parsed article `Audi`
<img width="791" alt="2019-01-24_2218" src="https://user-images.githubusercontent.com/435827/51706183-56e1de80-2026-11e9-9b37-9746c1374392.png">

**Comment by spencermountain** [comment]
fixed this in 7.2.9
in the near-future, we should properly support references and other templates in image captions.

**Comment by yanosh-igor** [comment]
Great, thanks!!
