### ISSUE TITLE
Stand Alone Output

### ISSUE THREAD

**Issue by niebert** [spencermountain/wtf_wikipedia#242]
E.g. by default [PanDoc](https://pandoc.org/try) generates just the pure text  (e.g. `Hello world!`) in HTML, Markdown, LaTeX without the head and tail wrapper for the HTML-head, HTML-body or in LaTeX `\documentclass{article}...  \begin{document}` and `\end{document}`.
```latex
\documentclass{article}
\title{Geoinformation Systems and Public Health}
\author{Jane Doe}
\date{January 2019}
\begin{document}
   Hello world!
\end{document}
```
This is a useful default strategy for PanDoc and I guess for `wtf:_wikipedia` too due to the fact that ´wtf_wikipedia` extract the content and not layout. Furthermore concatenation of different articles  on a client-side e.g. with a [WikiBook-Creator](https://en.wikiversity.org/wiki/Risk_Management/Tailored_Wikibooks) will be difficult, because all the wrapped document headers and tails had to be removed. 

**Recommendation:** Introduction of an `options.standalone=true`. Only if `options.standalone=true` will create a wrapped document head and tail.

Does that make sense?
Cheers Bert

**Comment by spencermountain** [comment]
yeah, i agree. Let's do this for html + markdown too.
People should generate their own headers, table-of-contents, and all-that.

this will be a breaking change, i reckon.

hey wikibook-creator is cool!
That's a pretty strong concept!

**Comment by niebert** [comment]
Wiki Communities battles with the server load of WikiBook generator. `wtf_wikipedia` is the key to transfer server-side content rendering to client-side Book generation. Since I first came accross `wtf_wikipedia` I understood more and more what a brilliant concept YOU had with `wtf_wikipedia`. It is really amazing what you did! When you come to Europe it would be great to have you at the University Koblenz-Landau presenting your work. Best regards, Bert

**Comment by spencermountain** [comment]
hey @niebert i've just removed the headers/footers from the automatic output. You're right, they were too opinionated and didn't help.
the data is there for people to create whatever they'd like.
thanks for this
cheers
