### ISSUE TITLE
References / Citations not showing

### ISSUE THREAD

**Issue by FortisFortuna** [spencermountain/wtf_wikipedia#245]
Looks like the Wikipedia API changed. It now only shows {{reflist}} and requires <ref></ref> tags.

**Comment by k26dr** [comment]
The citations are inline now as opposed to at the end in a references list. 

Example: 

```
In its broadest sense, a pest is a [[Competition (biology)|competitor]] of humanity.<ref>[http://www.merriam-webster.com/dictionary/pest Merriam-Webster dictionary], accessed 22 August 2012.</ref><ref>{{cite web |title=Pest vermin |url=http://www.britannica.com/EBchecked/topic/453421/pest |publisher=Britannica |accessdate=24 August 2016}}</ref>
```

**Comment by spencermountain** [comment]
hey, sorry for the delay on this.
I'm not completely following. Is this regarding the html/markdown output?
Otherwise, references are stripped-out as json, no matter if they are inline or what.
What's the proposed change to this parser?
cheers

**Comment by k26dr** [comment]
I think this is in the JSON output. When you do doc.infoboxes() it comes back empty now. The root of the problem seems to be that the Wikipedia API doesn't return infobox key-value pairs anymore when you fetch the MediaWiki text.

**Comment by k26dr** [comment]
Sorry, it seems like we may have been testing these improperly. I'm able to see infoboxes now.

**Comment by spencermountain** [comment]
oh, ya that's possible! thank you.

**Comment by spencermountain** [comment]
hey, in this example the references are stored in the `sections` object, as expected
```js
let str = `In its broadest sense, a pest is a [[Competition (biology)|competitor]] of humanity.<ref>[http://www.merriam-webster.com/dictionary/pest Merriam-Webster dictionary], accessed 22 August 2012.</ref><ref>{{cite web |title=Pest vermin |url=http://www.britannica.com/EBchecked/topic/453421/pest |publisher=Britannica |accessdate=24 August 2016}}</ref> `;
console.log(wtf(str).json());
```

if you want to copy these up into the main section, you can use `.json({citations:true})`

lemme know if there's anything else i'm missing.
cheers
