### ISSUE TITLE
4rth-nested template parser

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#247]
The Topic United Kingdom has wiki markup in doc.text()
https://beta.observablehq.com/@spencermountain/wtf_wikipedia fails to parse this topic
![2019-02-05_1327](https://user-images.githubusercontent.com/435827/52270513-e900b580-2949-11e9-9efc-60418fe39f05.png)
![2019-02-05_1326](https://user-images.githubusercontent.com/435827/52270514-e900b580-2949-11e9-877a-1bd4718af844.png)

**Comment by spencermountain** [comment]
oh yeah,
seems to not like the 4rth nested template.
i've isolated this case here:
```js
let str = `
{{Infobox country
| common_name = United Kingdom
| name = {{collapsible list
 | title = hello
 | {{Infobox
  | data1={{lang|foo}}
  | data2=bar
  }}
 }}
}}
First sentence`;
let doc = wtf(str);
console.log(doc.infoboxes());
//[]
```

likely something to do with [this janky parsing here](https://github.com/spencermountain/wtf_wikipedia/blob/master/src/templates/index.js#L26)

thanks for the heads up
