### ISSUE TITLE
support Template:Mono

### ISSUE THREAD

**Issue by pierreis** [spencermountain/wtf_wikipedia#248]
On pages such as" [https://en.wikipedia.org/wiki/ISO_3166-2:FR](https://en.wikipedia.org/wiki/ISO_3166-2:FR)

The monospaced text in tables is not parsed, resulting in an empty text.

**Comment by spencermountain** [comment]
good find, thanks

**Comment by spencermountain** [comment]
this should be fixed now in 7.2.10
cheers
