### ISSUE TITLE
Deeply-nested infobox

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#249]
Topic Ukraine has wiki markup in parsed text
![2019-02-18_1821](https://user-images.githubusercontent.com/435827/52964076-1b7acb80-33aa-11e9-8003-1aeaacbd4aae.png)

**Comment by spencermountain** [comment]
thanks, my guess is this is related to #247

**Comment by spencermountain** [comment]
this seems to work now
```js
;(async () => {
  let doc = await wtf.fetch('Ukraine')
  console.log(doc.sentences(0).text())
})()
```
