### ISSUE TITLE
Grade parsing

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#253]
**Feature request:**

Some of wiki articles have grades.
https://en.wikipedia.org/wiki/Wikipedia:Content_assessment
Will be good to have function in wtf_wikipedia to get article's grade.
Also it has importance https://en.wikipedia.org/wiki/Wikipedia:Version_1.0_Editorial_Team/Release_Version_Criteria#Importance_of_topic

**Comment by spencermountain** [comment]
good idea. happy to add them.

**Comment by spencermountain** [comment]
these are stored on the Aritcle's Talk page, you can retrieve them like this:
```js
wtf.fetch('Talk:Army_ant').then(doc => {
  console.log(doc.templates());
});
```
cheers
