### ISSUE TITLE
support CVT template

### ISSUE THREAD

**Issue by fractalien** [spencermountain/wtf_wikipedia#254]
[en:Sydney](https://en.wikipedia.org/wiki/Sydney) uses the template [Cvt](https://en.wikipedia.org/wiki/Template:Cvt) in the middle of a sentence:
`Boasting over {{cvt|1,000,000|ha|acre}} of [[Parks in Sydney|nature reserves and parks]]`
When applying text() to this section, the template is ignored, unsurprisingly yielding a nonsensically contracted version of the above sentence.

There are a zillion templates, so reporting every single one that's not considered probably won't make sense. I'm mainly posting this because templates whose output is actually 'needed' within sentences may be a special case – or is this actually quite common?

**Comment by spencermountain** [comment]
hey @fractalien yeah, I created [this output](https://github.com/spencermountain/wtf_wikipedia/wiki/Unsupported-Templates) a few months ago of the most frequent missed templates.

if the library doesn't have a custom parser for the template, it tried to auto-parse it, but will require certain conditions before it accepts it.

I haven't measured it, but i figure we properly-parse 90% of templates, by weight, on wikipedia.
I don't mind adding more one-offs, and you can add them too (it's easy!) [here](https://github.com/spencermountain/wtf_wikipedia/tree/master/src/templates).

**Comment by spencermountain** [comment]
note: that list is pretty out-of-date now.

**Comment by spencermountain** [comment]
hey @fractalien this is fixed now on dev and will be released as 8.1.0 in the next few days
cheers

**Comment by fractalien** [comment]
Belated thanks for this!

**Comment by waldenn** [comment]
BTW: The link on [that page](https://github.com/spencermountain/wtf_wikipedia/wiki/Unsupported-Templates), should be updated to [this URL](https://github.com/spencermountain/wtf_wikipedia/tree/master/src/template).
