### ISSUE TITLE
No Response when searching for words with `F*** + " "`

### ISSUE THREAD

**Issue by Aliyss** [spencermountain/wtf_wikipedia#255]
Trying the following when searching for something like "Fort Knox" or "Fort Foster" or "First Kid" or "Fort Knox Five" returns a null object.

**Comment by spencermountain** [comment]
hi @Aliyss can you give an example?
I don't understand the context for this

**Comment by Aliyss** [comment]
ofc..

`wtf.fetch("Fort Knox").then(doc => {
 console.log(doc)
})`

will return null

**Comment by Aliyss** [comment]
When retesting it seems, that the input works when both the words are capitalized at the beginning, however doesn't work when it's all lowercase

**Comment by spencermountain** [comment]
hi Aliyss, yes, the wikipedia api is case-sensitive.
I'm surprised there is not a redirect [there](https://en.wikipedia.org/wiki/Fort_knox).
You'll need to use another service if you want fuzzy matching
cheers
