### ISSUE TITLE
Mark paragraphs as quote

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#256]
**Feature request:**

Example:
https://en.wikipedia.org/wiki/Honey_(Moby_song)
There is a quote in the 2nd section "I was hanging out at Max Fish and Mars Bar and Motor City drinking with the few r.."
Right now this quote returns as a separate paragraph. 
Would be good to mark such paragraphs as a quote.

![2019-03-12_1407](https://user-images.githubusercontent.com/435827/54199934-bd399800-44d2-11e9-8c73-225ba8b421b9.png)
![2019-03-12_1408](https://user-images.githubusercontent.com/435827/54199937-bdd22e80-44d2-11e9-8870-1cea3bd5e583.png)

**Comment by spencermountain** [comment]
ah, given the ordering of our parser, i'm not sure this is going to be possible.
will flag as nofix, but prs welcome for this.
cheers
