### ISSUE TITLE
Certain articles in Hindi Wikipedia omit entire sections due to parsing issues 

### ISSUE THREAD

**Issue by tanvibhakta** [spencermountain/wtf_wikipedia#258]
For example, 

In this article, https://hi.wikipedia.org/wiki/%E0%A4%AE%E0%A4%B9%E0%A4%BE%E0%A4%A4%E0%A5%8D%E0%A4%AE%E0%A4%BE_%E0%A4%97%E0%A4%BE%E0%A4%82%E0%A4%A7%E0%A5%80
Lots of sections are omitted like large parts of this section, https://hi.wikipedia.org/wiki/%E0%A4%AE%E0%A4%B9%E0%A4%BE%E0%A4%A4%E0%A5%8D%E0%A4%AE%E0%A4%BE_%E0%A4%97%E0%A4%BE%E0%A4%82%E0%A4%A7%E0%A5%80#%E0%A4%AA%E0%A5%8D%E0%A4%B0%E0%A4%BE%E0%A4%B0%E0%A4%AE%E0%A5%8D%E0%A4%AD%E0%A4%BF%E0%A4%95_%E0%A4%9C%E0%A5%80%E0%A4%B5%E0%A4%A8 , these images https://hi.wikipedia.org/wiki/%E0%A4%AE%E0%A4%B9%E0%A4%BE%E0%A4%A4%E0%A5%8D%E0%A4%AE%E0%A4%BE_%E0%A4%97%E0%A4%BE%E0%A4%82%E0%A4%A7%E0%A5%80#/media/File:Gandhi_and_Kasturbhai_1902.jpg , etc

Further, many images don't show up and have random text associated with them like in this article 
https://hi.wikipedia.org/wiki/कर्नाटक

When rendered, most images don't show up but instead are displayed with the text 

175px|thumb|left|पत्तदकल में मल्लिकार्जुन और... 

(the Hindi part is just the caption)

We suspect that this is part of the styling of the page that isn't being captured right (verified when we looked at the html of the same page rendered by the wikijs API)

In case things aren't clear or you aren't able to reproduce the error, I'll be happy to get on a quick 10-min call with you to show you what is happening.

**Comment by spencermountain** [comment]
hey thanks Tanvi, it's possible that @ramusus fixed this, yesterday!
I'll check it out, then push a release today, if so.
cheers

**Comment by tanvibhakta** [comment]
Hey, thank you for the really quick response. 

We just pulled from master and checked - the content isn't omitted any more but some images still are. The captions for the missing images still appear in the middle of the page, along with the styling information, just as before. 

If these have been fixed too, are they available on some other branch?

**Comment by spencermountain** [comment]
hey Tanvi, I've added hindi support for Infoboxes, Images, and Categories.  it's `7.3.0`.
I'm sure there's more to do - can you spot anything else?

I don't think images links are working. That looks like it's [this issue](https://github.com/spencermountain/wtf_wikipedia/issues/237).
It also looks like there's a lot of templates, I'll leave this open if you spot anything else.
cheers

**Comment by tanvibhakta** [comment]
This has fixed most of our issues, except images as you pointed out. 

Thank you!
