### ISSUE TITLE
Logo parsing issue

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#263]
Couldn't get logo from topic Node.js.
https://en.wikipedia.org/wiki/Node.js

![2019-04-04_1307](https://user-images.githubusercontent.com/435827/55547791-b91c2700-56da-11e9-8d97-d58bbb627552.png)

**Comment by spencermountain** [comment]
thanks, good find

**Comment by spencermountain** [comment]
fixed on dev, will release as `8.1.0` in the next couple days
cheers
