### ISSUE TITLE
allow toHtml() to add span-ID's around sentences for later referral

### ISSUE THREAD

**Issue by waldenn** [spencermountain/wtf_wikipedia#265]
Hi, thanks for a wonderful library!

I am looking for some help to make toHTML() output span-wrapped-sentences (if an option for that is set).

```
<span id="s-[sentence-index]'> [sentence] </span>
```

The toHtml.js code seems to use sections (not sentences) though. Any pointers / tips where to look for adding this feature to toHTML() would be appreciated.

My use case is to link to a sentence containing some targeted data (eg. a list of found dates in each sentence). My personal project can be found here: https://wikischool.org/explore/

I am also interested in contributing some more template-parsers (such as {{main}}), but I am just beginning to research how these work. Some docs in this area would help here I think.

Thanks!

**Comment by spencermountain** [comment]
hey thanks @waldenn - whoa  that looks really nice!

are you using .html() for all of that? i'm really impressed.

you're right about the html output. You'll have to roll your own version of this.

yeah, last time I checked, the structure is `Doc -> Section -> Paragraph -> Sentence`.
you'll see the `.html()` method just of Section [just loops around](https://github.com/spencermountain/wtf_wikipedia/blob/master/src/02-section/toHtml.js#L37) the sentences, and whatnot. It's not very clever

to be honest, I've been feeling lately like html output ought to be a different library. 
Especially when it comes to rendering infoboxes, as you have done.
Maybe we should collaborate on this.
I think that'd be smart.

**Comment by waldenn** [comment]
Thanks again. I got it working by adding a span-wrap (with only a class set)  to each sentence and after document loading adding going over each class and then adding an "id". This seemed easier than counting the ID from within wtf_wikipedia.

I will have a look at understanding how those templates are parsed and see if I can contribute a relative simple one like {{main}}. If there is something else I can potentially help with let me now. So far your library has been very easy to use for me : )

**Comment by spencermountain** [comment]
*yes* - exactly.
right now we do well with templates that replace inline-text, like {{date|3|5|2018}} - and templates that produce data, like {{isbn|1234567}} - but we don't have a good layer for templates that need to render in a specific way, like `{{main|Page}}`. These should all render in a custom way for html/markdown/latex outputs.  👍

**Comment by spencermountain** [comment]
i'll scratch-together some ideas for this on the weekend.

**Comment by niebert** [comment]
great work @waldenn
