### ISSUE TITLE
Support Portal templates

### ISSUE THREAD

**Issue by waldenn** [spencermountain/wtf_wikipedia#266]
Any tips how to improve parsing Portal: pages, eg.:

  https://en.wikipedia.org/w/index.php?title=Portal:1930s
  https://en.wikipedia.org/w/index.php?title=Portal:1930s&action=edit 

Currently these Portal pages have little info when parsed. It all looks kinda messy from a wiki-text point of view. These portal pages are very informative for subject introductions.

**Comment by spencermountain** [comment]
oof, yeah. 
most of the content on that page appears to be `translcuded` (like an iframe) from other pages:
the main section appears to grab a random article from this list:

`{{Transclude random excerpt|paragraphs=1-2|files=1|more=|Great Depression|League of Nations|Spanish Civil War|Dust Bowl|Salt March}}`

ya, maybe we can get further on this page by supporing `Box-header` and `Flex columns`, but most of the content there is coming from elsewhere.

**Comment by waldenn** [comment]
Hey, I fixed the rendering of "Portal" pages (and other transcluded-pages) by using a small [webscraper](https://github.com/michaeluno/php-simple-web-scraper) and then cleaning up the HTML and CSS issues on the client. This works well enough and still allows full rendering control. Its not ideal, but I think its currently the most sane way of doing this. For me this closes the issue.

Example: https://wikischool.org/explore/Portal%3AHistory%20of%20science?l=en&t=wikipedia
