### ISSUE TITLE
Topic Joe Wilson (American politician) fails to parse

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#268]
Topic: https://en.wikipedia.org/wiki/Joe_Wilson_(American_politician)
![2019-04-09_1817](https://user-images.githubusercontent.com/435827/55812490-c3339080-5af3-11e9-8c5a-8edc04ebd126.png)
![2019-04-09_1816](https://user-images.githubusercontent.com/435827/55812491-c3339080-5af3-11e9-882c-72eb5a2764ca.png)

**Comment by spencermountain** [comment]
whoa, good find.

**Comment by spencermountain** [comment]
this works now in v8.0.0
cheers
