### ISSUE TITLE
Redirect parsing issue B.B._King 

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#269]
Method redirectTo() return page with underscores.

Parsing redirect https://en.wikipedia.org/w/index.php?title=B.B._King_Blues_Club&action=edit
```
const doc = wtf('#REDIRECT [[B.B._King#B.B._King.27s_Blues_Club]]');
console.log(doc.redirectsTo());
{ page: 'B.B._King', anchor: 'B.B._King.27s_Blues_Club' }
``` 
It returns page 'B.B._King' but should be 'B.B. King' without underscore.

**Comment by spencermountain** [comment]
thanks

**Comment by spencermountain** [comment]
if the underscore is in the Redirect page, i don't wanna change it blindly.
I think this is a 'fix it on wikipedia' bug.
let me know if there's a good reason to validate it within the library
cheers
