### ISSUE TITLE
Question: fetch raw wiki source

### ISSUE THREAD

**Issue by niebert** [spencermountain/wtf_wikipedia#270]
Hi Spencer,
the `fetch` call converts the raw wiki sources and returns a parse document (defined by `src/01-Document`). I want to call `wtf.fetch(...)` and
* just get the raw wiki source without parsing, 
* do some pre-processing with raw wiki source ,
* call `let doc = wtf(wiki,options)` with the preprocessed  wiki sources and
* append `toReveal()` to all tree nodes of parsed document.
Is that possible without touching your code and just do a `npm install wtf_wikipedia --save`?
Thank you Bert

**Comment by spencermountain** [comment]
hey Engelbert, hmm -  yea i think the best way to do this would be to just fetch the wikitext off the api, then throw it into wtf after your work.

the api request is uses is [here](https://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&maxlag=5&rvslots=main&format=json&titles=Radiohead) and probably would do what you want

**Comment by niebert** [comment]
Will describe the procedure in the github-Wiki of `wtf_wikipedia` so that others can expand `wtf_wikipedia` with any other output formats e.g. found in `[PanDoc](https://pandoc.org/try)`.
Thank you.

**Comment by niebert** [comment]
Thank you very much, that helps a lot. `src/_fetch/_url.js` is fetching a `JSON`.
