### ISSUE TITLE
Switching to WikiPeg or PEG.js

### ISSUE THREAD

**Issue by dan1wang** [spencermountain/wtf_wikipedia#272]
Parsoid uses Wikipeg, also a MediaWiki project, to convert wikitext to a list of tokens. Perhaps consider using Wikipeg as the parser and then process the tokens afterward.

https://github.com/dan1wang/wiki.ly is a project I'm working on. It's Parsoid with everything stripped away until only the tokenizer is left. I'm learning the PEG language so I can reduce it further.

**Comment by spencermountain** [comment]
hey Daniel, cool! sounds like a neat project.
yeah, PEG looks really cool. I thought it was used in parsoid, isn't it? I was impressed with it.

Others have thought about abstract-syntax-tree styles for understanding the nested structures. 

I think it would be a big change to make right now. Ultimately it's a style-decision if one prefers writing `if(tokens.find(t=>t.type==='ws-comma')){...}` or `str.match(/,/)`. 

I prefer the latter, personally. But there are advantages to using a formal tokenizer.
Will leave this open, Lemme know if you wanna colloberate!

**Comment by spencermountain** [comment]
hey Daniel, just cleaning up some issues.
how did this experiment go?
I've been *really* torn between using a formal parser, and a regex solution.
Your demo is the cleanest example I've seen of doing tokenization really well. My concern is that looping/recursing through the forest of results will be trickier than writing a regex match.

please share anything you've found. I have an open mind.
cheers
