### ISSUE TITLE
wtf_fetch update - collaborator

### ISSUE THREAD

**Issue by niebert** [spencermountain/wtf_wikipedia#273]
Hi Spencer,
`wtf_fetch`  is now based on the current release 7.3.0 - published the npm module added `domain` parameter to `fetch`-call, because I use wtf_wikipedia also on Wikiversity. Added you as collaborator to mircolibrary. Hope that is ok for you. 

see https://www.github.com/niebert/wtf_fetch

cheers Bert

**Comment by spencermountain** [comment]
thanks! saw that. great work!

**Comment by niebert** [comment]
I could provide a meaning for `wtf` e.g. "Wiki Transformation Framework", in which all submodules /mirco libraries have the module name `wtf_my_module` and `wtf` plugs the required sub modules together.  
* `wtf_fetch`
* `wtf_parse` that currently the main job `wtf_wikipedia´ does  i.e.. wiki to JSON others might 
* `wtf_absolute_links` transform relative links to absolute links.
Those processing chain are connected with `Promises` in the root `wtf` which is now `wtf_wikipedia`. 
One example processing chain if `wtf_absolute_links` exists would be

`wtf_fetch > wtf_absolute_links > wtf_wikipedia` 

(fetch the wiki markdown perform  a relative to absolute link transformation and the pipe the result with `wtf(wiki)` into your current npm module `wtf_wikipedia`. Someone asked for PEG and Parsoid, so if those developers want apply the PEG on the wiki source that create another processing chain like.

`wtf_fetch > wtf_absolute_links > wtf_parsoid` 

Cheers, Bert

**Comment by spencermountain** [comment]
yeah, this is a cool idea.

we could also export more functions, like `absolute_links`, from the library. the new esmodule stuff is hopefully making this sort of thing easier to do.

**Comment by spencermountain** [comment]
hey Engelbert, you may be interested in the new [cleaned-up fetch method](https://github.com/spencermountain/wtf_wikipedia#fetch) in v8.
it parses absolute links to articles, into an api response, and supports a domain param, like your solution does.
check it out, and let me know if you think of other ways that it can be improved upon
