### ISSUE TITLE
support for <section> tag

### ISSUE THREAD

**Issue by dan1wang** [spencermountain/wtf_wikipedia#274]
MediaWiki supports `<section>` (which is NOT HTML)

Example:
* https://en.wiktionary.org/wiki/User:Dan1wang/Sandbox/Sections
* https://en.wiktionary.org/wiki/User:Dan1wang/Sandbox/SectionTransclude

In the first page, you'd see 2 paragraphs under "section 2". The first paragraph is part of "section 2" while the second paragraph is actually part of "chapter 1". So, in the tranclude page, there is only one paragraph for section 2.

Right now, the parser would wrongly put both paragraphs under "section 2"

**Comment by spencermountain** [comment]
you're right. Ideally we could just replace it with `\n\n` and it would be recognized as two paragraphs

**Comment by spencermountain** [comment]
gonna merge this with #223 
maybe in the future, we could pass a `{is_transcluded:true}` to the parser, and it would selectively render the right parts, but seems like a way off still.
thanks for letting me know about this
