### ISSUE TITLE
improve i18n support with siteInfo api

### ISSUE THREAD

**Issue by dan1wang** [spencermountain/wtf_wikipedia#275]
A lot of information can be retrieved from site info:
https://en.wikipedia.org/w/api.php?action=query&format=json&prop=&meta=siteinfo&siprop=namespaces%7Cnamespacealiases%7Cmagicwords%7Cfunctionhooks%7Cextensiontags%7Cgeneral%7Cinterwikimap%7Clanguages%7Cprotocols%7Cspecialpagealiases

For `i18n.files`, look for a `json.query.namespaces[6]`

For `i18n.image`, look for `json.query.namespacealiases[6]`

For `i18n.users`, look for `json.query.namespacealiases[2]`

For `i18n.templates`, look for a `json.query.namespaces[]` entry with `canonical === 'Template'`. We might want to look for aliases too.

For `i18n.categories`, look for  a `json.query.namespaces[14]`. We might want to look for aliases too.

For `i18n.redirects`, look for  `json.query.agicwords[]` entry with `name === 'redirect'` and uses the `aliases`. It is case-sensitive if `case-sensitive` is defined (`===''`)

For `i18n.disambigs`,  look for  `json.query.agicwords[]` entry with `name === 'disambiguation'` and uses the `aliases`. It is case-sensitive if `case-sensitive` is defined (`===''`)

For infoboxes and sources, those have to be hard coded.

**Comment by spencermountain** [comment]
hey nice find!
I'd still like to store these in json, instead of requring a http-request to run each time.
if the i18n file gets too big, we can look at compressing it.
thanks!

**Comment by spencermountain** [comment]
holy, this has been really useful Daniel.
thank you again.
