### ISSUE TITLE
Extending export formats

### ISSUE THREAD

**Issue by niebert** [spencermountain/wtf_wikipedia#277]
Analysis of current code shows that the export of the generated [Abstract Syntax Tree](https://github.com/spencermountain/wtf_wikipedia/wiki/Abstract-Syntax-Tree-as-JSON) attaches `toHtml()`, `toMarkdown()`, `toLatex()` to all levels of the AST:
* `Document`
* `Section`
* `Paragraph`
* `Sentence`
For extending the capabilties of a `wtf`  as a wiki transformation framework  someone would install `npm install wtf_wikipedia` and then require the module in the extension with
```javascript 
const wtf = require('wtf_wikipedia');
```
Assume we want to add/replace the existing default one with another export format or add a new export format `my_format`, then the constructors need new export methods for the AST nodes - something like this: 
```javascript 
wtf.ast.Document.prototype.my_format =  function(options) {
   ....
    return doc_in_my_format;
  };

wtf.ast.Paragraph.prototype.my_format =  function(options) {
   ....
    return par_in_my_format;
  };
 
wtf.ast.Section.prototype.my_format =  function(options) {
   ....
    return sec_in_my_format;
  };

...
```
I guess the constructors for the AST nodes defined in `src` can be expanded for another format if the AST node constructor are accessible in the required `wtf_wikipedia` - i.e. the constructor e.g. of a `Document` node in `src/01-document/Document.js` is available in `wtf` at `wtf.ast.Document`. These access to the constructors could be  added at `src/index.js` with a require command. 
```javascript 
wtf.ast = require('astnodes');
```

Or is there a better way to add plugins or extension for new export formats to `wtf_wikipedia` without touching the current code base of `wtf_wikipedia`, Spencer?

Cheers Bert

**Comment by spencermountain** [comment]
hey Bert, yes that's right. You should be able to set new methods on `Document`, and access all the goodies it has. The only trick is that the classes aren't explicitly exported from wtf_wikipedia, like you mentioned.

It would be cool to have a better plugin architecture, but yeah, it boils-down to just setting things on the different classes, like that.

open to suggestions.

**Comment by niebert** [comment]
I would recommend to explicitly export the AST node constructors in `wtf` just by `wtf_wikipedia` in `src/index.js`. Suggestion: 
# bundle all constructors `Document`,`Section`,  `Paragraph`,  ... in one file `src/astnodes.js` 
# export the constructors in `wtf.ast` e.g. `wtf.ast.Doument`, `wtf.ast.Section`, ...
# create an `init(ast)`-method for the parser in which you pass the constructors to the parse environment. `init(ast)` substitutes/overwrites the AST node constructors and after the `init()`-call the parsing uses the new constructors with extended methods/export formats. `wtf.init(ast)` passes with `ast` a "pointer/reference" to the bundle of required AST node constructors.
# you can still require the constructors for the AST nodes (as you do it now e.g. in `src/01-document/index.js`), but `init()` call allows to overwriting/extending the constructors for the AST nodes before parsing is called. You could also decide to pass the AST node with `options` - e.g. with `options.ast` and if `options.ast` is not `null` then  e.g. the call of `wtf(my_wiki_source,options)` would use the new constructors. I would prefer the `init()` call because `options` are meant as options for the parsed wiki markdown source and not as options for core of the parser. 

That recommendation will not cause a refactoring of `wtf_wikipedia` because you make just the AST nodes processing concept accessible to programmers, that require `wtf_wikipedia`.

To design `wtf_wikipedia` as a Wiki Transformation Framework (WTF) means, that extensions can be made by requiring the `npm` module `wtf_wikipedia` without touching the "heart/core" of `wtf_wikipedia`and then extending the features. Just regard a  Wiki Transformation Framework (WTF)  more like chaining available wtf-module according to the applications needs. The processing chain starts in general with a fetch (e.g. `wtf_fetch`) or load of the wiki markdown file from the file system.

**Comment by niebert** [comment]
Would that be OK for you? Do you want me to create PR for that?

**Comment by spencermountain** [comment]
hey, yeah I agree that we should expose these classes. 

typically this is done through some kind of `.extend()` or `.plugin()` method.
like ...this?
```js
wtf.extend((nodes)=>{
  nodes.Infobox.toAscii=function(){ 
   ...
  }

  nodes.Image.getFileSize=function(){
     ....
  }
})

wtf('China').infobox0).toAscii()
```

i'd prefer something that looks like that, it's probably my 20's spent using jquery. what do you think?

**Comment by spencermountain** [comment]
what do you think? would that work for your purposes?

**Comment by niebert** [comment]
Hi Spencer, that is fine for me. It should fit into the overall philosophy of `wtf` you have in mind.
Let me understand that properly:
*  the `extend(nodes)` is called before `wtf` is parsing the wiki code.
* if someone extends `wtf` to a module `wtf_xt1` then additional method are available at each node e.g. `toAscii()` of `getFileSize()` that extend just one node type.
* Assume someone installs `wtf_xt1`  and extends additional methods `toReveal()` to `wtf_xt2`. Are previous extensions of  `wtf_xt1` lost because of an overwrite of `extend()` in the module `wtf_xt2`?
* Inheritance might be possible in analogy to the [JSONEditor by Jermey Dorn] (https://github.com/jdorn/json-editor/blob/master/src/class.js) uses  the following `extend()` of JS classes.  The [JSONEditor](http://jeremydorn.com/json-editor/) handles Editors for integer, strings, array, .... as  the tree nodes of a provided JSON. The `extend()`  looks like this. 
```javascript
/*jshint loopfunc: true */
/* Use JSONEditor by Jeremy Dorn
 *  Simple JavaScript Inheritance
 * By John Resig http://ejohn.org/
 * MIT Licensed.
 */
// Inspired by base2 and Prototype
var Class;
(function(){
  var initializing = false, fnTest = /xyz/.test(function(){window.postMessage("xyz");}) ? /\b_super\b/ : /.*/;
 
  // The base Class implementation (does nothing)
  Class = function(){};
 
  // Create a new Class that inherits from this class
  Class.extend = function extend(prop) {
    var _super = this.prototype;
   
    // Instantiate a base class (but only create the instance,
    // don't run the init constructor)
    initializing = true;
    var prototype = new this();
    initializing = false;
   
    // Copy the properties over onto the new prototype
    for (var name in prop) {
      // Check if we're overwriting an existing function
      prototype[name] = typeof prop[name] == "function" &&
        typeof _super[name] == "function" && fnTest.test(prop[name]) ?
        (function(name, fn){
          return function() {
            var tmp = this._super;
           
            // Add a new ._super() method that is the same method
            // but on the super-class
            this._super = _super[name];
           
            // The method only need to be bound temporarily, so we
            // remove it when we're done executing
            var ret = fn.apply(this, arguments);        
            this._super = tmp;
           
            return ret;
          };
        })(name, prop[name]) :
        prop[name];
    }
   
    // The dummy class constructor
    function Class() {
      // All construction is actually done in the init method
      if ( !initializing && this.init )
        this.init.apply(this, arguments);
    }
   
    // Populate our constructed prototype object
    Class.prototype = prototype;
   
    // Enforce the constructor to be what we expect
    Class.prototype.constructor = Class;
 
    // And make this class extendable
    Class.extend = extend;
   
    return Class;
  };
  
  return Class;
})();

```

**Comment by niebert** [comment]
Do you think that exposing the nodes by propgating them upwards from `Sentence` to `Document` will work?
e.g. in `src/04-sentence/index.js` 
```javascript 
module.exports = {
  parseSentences: parseSentences,
  oneSentence: oneSentence,
  addSentences: addSentences
  nodes:{
     Sentence:Sentence
  }
};
```
Then propagate the constructors for nodes further upward `src/03-sentence/index.js` by
```javascript 
const Paragraph = require('./Paragraph');
const Sentences = require('../04-sentence');
const parseSentences = Sentences.addSentences;
const nodes  = Sentences.nodes;
nodes.Paragraph = Paragraph;
....
module.exports = {
  parsev: parseParagraphs,
  nodes: nodes
};
```

**Comment by spencermountain** [comment]
ah yeah, that's right. if you were wanting to replace methods like parseSentence, we'd have to add them to the Class. Wasn't built that way now, but could be. I don't think there's any performance downside to chucking stuff like that onto the prototype, but it would require a refactor.

**Comment by niebert** [comment]
Excuse me Spencer, do not want to trigger a refactoring. Excuse me for that. Forgot about the fact that nodes like `Sentence` is called multiple times and the `require()` has to be adapted, if the export consists of just method. Would recommend to export always a hash with `module.export={...}`  so that expanding the export hash does require the adaptions of multiple `const mynode = require('0x-node')` imports. Thank you.

**Comment by spencermountain** [comment]
hey, this should all be possible now, as of v8!
https://github.com/spencermountain/wtf_wikipedia/#configuration
cheers
