### ISSUE TITLE
Can this be made to point at other wiki sites?

### ISSUE THREAD

**Issue by Shane-Neeley** [spencermountain/wtf_wikipedia#279]
Other wiki sites like https://hemonc.org/?

https://hemonc.org/wiki/Amsacrine_(Amsidine)

Would be really helpful

**Comment by spencermountain** [comment]
hey Shane, yeah it should be able to do this. By default wikis have their api turned on, (i think), but it appears this one has [theirs disabled](https://en.wikipedia.org/w/api.php?action=query&format=json&titles=Amsacrine_(Amsidine)&prop=categories).

It may be worth emailing the creators to ask them.

this is how it would normally work, in this library:
```
wtf.fetch('Amsacrine_(Amsidine)', {
  wikiUrl: 'https://hemonc.org/api.php'
}).then(function(doc) {
  console.log(doc.json())
})
```


worst case, you can manually grab the wikitext from the edit page, then add it to the library directly.
There may be some additional templates to parse, which I'd be happy to add.

lemme know how it goes
cheers

**Comment by PlNG** [comment]
This isn't listed anywhere in the documentation and really excites me, I thought it was Wikipedia only and that I would have to hack the functionality in. Making it visible would boost your library's popularity for sure.

**Comment by spencermountain** [comment]
hi @PlNG  you're right. This part needs some cleaning up, and is a priority going forward.
