### ISSUE TITLE
support {{formatnum}}

### ISSUE THREAD

**Issue by nico008** [spencermountain/wtf_wikipedia#282]
Hi,
This project looks good!
I need to access some information from infoboxes, example num_employees.
On some pages it works fine. On other pages I cannot find a way to get the value.
Example: https://en.wikipedia.org/wiki/Bonduelle has num_employees = {{formatnum:9569}}
In Mongo, in infoboxes I see:
"num_employees" : {
  "text" : "(in 2013/2014)"
}
In templates, I see:
"template" : "formatnum:9569"
Unfortunately I don't see a way to link the template to the num_employees, therefore it is of no use to me because I don't know which template relates to which property of the infobox.
Would it be possible to move the template inside each infobox properties? (or anything else it relates to).
Ex:
"num_employees" : {
  "text" : "(in 2013/2014)"
  "template" : "formatnum:9569"
}

It would be even better if we could render the text of the template, example:
"num_employees" : {
  "text" : "9569 (in 2013/2014)"
}
But some templates are more complex and can have multiple parameters (ex: currency code and value).

Thank you for your help!

**Comment by spencermountain** [comment]
hey @nico008 yeah, I think we just need to support this `formatnum` template.

**Comment by nico008** [comment]
Thank you for your quick reply.
I have seen many other templates, ex: https://en.wikipedia.org/wiki/Ptcl has | revenue = {{PKRConvert|117|b}}
And https://en.wikipedia.org/wiki/Template:US$
If you could show me a commit for one of them, I could try to help with some other.
Thank you in advance!

**Comment by spencermountain** [comment]
thanks nico, yeah it's really easy to add new templates, they're all [here](https://github.com/spencermountain/wtf_wikipedia/tree/master/src/templates). You're free to add any you'd like. PRs welcomed.

I just looked and i actually see [formatnum is there](https://github.com/spencermountain/wtf_wikipedia/blob/master/src/templates/formatting/misc.js). 
if you go to [this page](https://observablehq.com/@spencermountain/wtf_wikipedia) and type in `Bonduelle`, it looks like the infobox is getting parsed properly.

<img width="354" alt="image" src="https://user-images.githubusercontent.com/399657/59936982-468c2f00-941f-11e9-952a-03a86b5e9a8b.png">

which version of dumpster are you using?

**Comment by nico008** [comment]
Hi @spencermountain ,
You are absolutely right, it works perfectly now.
I assumed I had dumpster-dive 5.2.1 but in fact I had 2 different versions installed, and the dumpster command was using the wrong one.
I then uninstalled all of them and deleted files, then installed again and all worked.
Thanks!
