### ISSUE TITLE
&origin=* not added in fetch() when using wikiUrl

### ISSUE THREAD

**Issue by MrXyfir** [spencermountain/wtf_wikipedia#283]
https://github.com/spencermountain/wtf_wikipedia/blob/master/src/_fetch/_url.js#L30

I'm not sure what the purpose of this line is, especially when `category()` allows it

https://github.com/spencermountain/wtf_wikipedia/blob/c9cd5c234a99843d6dec4ee1cfac203c30964126/src/_fetch/category.js#L22

I'm assuming one or the other is a mistake?

**Comment by MrXyfir** [comment]
Hopefully you'll allow `origin=*` in `fetch()` like in `category()` because otherwise I'll be stuck with this amazingly awful hack to pass the URL but bypass the check:

```js
await wtf.fetch(
  'why',
  null,
  (() => {
    let runs = 0;
    const opt = {
      get wikiUrl() {
        if (++runs == 2) delete opt.wikiUrl;
        return 'https://en.wiktionary.org/w/api.php';
      }
    };
    return opt;
  })()
);

```

**Comment by spencermountain** [comment]
sure, i'd be happy to.

**Comment by spencermountain** [comment]
changed in `7.4.0`
