### ISSUE TITLE
infobox properties with quotes are not available

### ISSUE THREAD

**Issue by nico008** [spencermountain/wtf_wikipedia#284]
Hello,
I hope this has not been raised already but I could not find it.
In frwiki, it is very common to have single quote in the key of infobox properties (this is silly).

When I try Microsoft with language fr in https://observablehq.com/@spencermountain/wtf_wikipedia
Then "secteurs d'activités" and "chiffre d'affaires" are not showing in section Infobox data.
Ex: https://fr.wikipedia.org/w/index.php?title=Microsoft&action=edit

I understand quotes might cause issues in some places but would it be possible to encode them to &#39; to something similar?
Ideally, I would need this in dumpster-dive as well.

Thanks

**Comment by spencermountain** [comment]
oh! good find.
this should be an easy fix.
i bet it's just a sloppy`/[a-z_]*/` somewhere.
Happy to take a look

**Comment by spencermountain** [comment]
fixed on `7.4.0`
