### ISSUE TITLE
Max category length

### ISSUE THREAD

**Issue by Patrik-scelex** [spencermountain/wtf_wikipedia#292]
Hello, 
have found that some of the categories were not returned after parsing. 
For example: 
- 'Best Musical or Comedy Actor Golden Globe (television) winners'.

Found that you have limitations 60 symbols for categories, changed it to 178.
The longest category has 178 symbols: 
- 'Externally peer reviewed articles by Steve Nadler, Professor of Philosophy, and Max and Frieda Weinstein-Bascom Professor of Jewish Studies at the University of Wisconsin-Madison';

Please check PR https://github.com/spencermountain/wtf_wikipedia/pull/291

**Comment by spencermountain** [comment]
haha! that's amazing.
Thank you, very much.
