### ISSUE TITLE
support 'image2' property of Taxobox

### ISSUE THREAD

**Issue by daniel** [spencermountain/wtf_wikipedia#297]
doc.images() is empty for some pages that have images, e.g. https://sv.wikipedia.org/wiki/Gökärt

Code example:
https://codesandbox.io/s/wtf-wikipedia-no-images-23xxf

**Comment by spencermountain** [comment]
hey Daniel, thanks. It looks like that template is using 'image2' - which should be easy enough to support.
cheers

**Comment by spencermountain** [comment]
fixed in `7.7.1`.

**Comment by daniel** [comment]
Thanks!!!

**Comment by daniel** [comment]
It worked for that page, but now I found another page for which I get no images:
https://sv.wikipedia.org/wiki/Tjockbent_vargspindel

Code example:
https://codesandbox.io/s/wtf-wikipedia-no-images-ek5k4?fontsize=14

**Comment by spencermountain** [comment]
weird! That image doesn't seem to be anywhere on the page....

if you copy the page's wikitext to the sandbox, you'll see it doesn't render the image at all.

have a look around if there's a special swedish taxobox image thing. I will reopen this, but I don't have a clue. It must auto-fill it from the `taxon` property or something.

does it say anything [here](https://sv.m.wikipedia.org/wiki/Mall:Taxobox)?

**Comment by daniel** [comment]
It seems to be linked to a Wikidata object that has the image:
https://sv.wikipedia.org/w/index.php?title=Tjockbent_vargspindel&action=info
https://www.wikidata.org/wiki/Q1058708

**Comment by spencermountain** [comment]
ah, right. magic Wikidata content pops-up sometimes. I'm surprised wikipedia editors allow it.
I'm gonna close this, we're not gonna be able to support that.
cheers
