### ISSUE TITLE
Dot at the beginning of sentence

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#299]
Topic: https://en.wikipedia.org/wiki/West_Ham_United_F.C.
![2019-08-16_1356](https://user-images.githubusercontent.com/435827/63163260-a113c700-c02d-11e9-86f2-a9362a70ac10.png)

**Comment by spencermountain** [comment]
hi Yanosh, looks like this one is a mistake on wikipedia
![image](https://user-images.githubusercontent.com/399657/63185032-f0a2c480-c026-11e9-8ca5-03a2d5551db3.png)
you can fix it there.
cheers
