### ISSUE TITLE
Template:Portuguese name

### ISSUE THREAD

**Issue by grygoriy-pinkas-scx** [spencermountain/wtf_wikipedia#304]
Hello. When i parsing article "Cristiano Ronaldo" with version 7.7.1,  script perceive summary as the first paragraph.  
![Screen Shot 2019-09-12 at 14 55 56](https://user-images.githubusercontent.com/48279096/64783344-3d1ee880-d570-11e9-8e6a-386119eaf3fc.png)
![Screen Shot 2019-09-12 at 15 05 33](https://user-images.githubusercontent.com/48279096/64783463-8838fb80-d570-11e9-865e-de26603b5b29.png)

But in your demonstration site, it had parced correct.

![Screen Shot 2019-09-12 at 15 10 35](https://user-images.githubusercontent.com/48279096/64783519-aa327e00-d570-11e9-81a1-e780aa5a3f43.png)

Hope you will fix problem! Thanks!

**Comment by spencermountain** [comment]
hey @grygoriy-pinkas-scx this header-sentence is generated from the [portugues name template](https://en.wikipedia.org/wiki/Template:Portuguese_name).
we've added first, second suffix parsing to `v8.1.0`.

re-creating this text may become part of the [html-plugin](https://github.com/spencermountain/wtf-plugin-html) (or something?), in the future, but it's out of scope for now.
cheers
