### ISSUE TITLE
.plaintext() cuts text

### ISSUE THREAD

**Issue by yarl** [spencermountain/wtf_wikipedia#31]
Hi, straight to the point: `.plaintext("dom, kon. XIX w.")` returns `"dom, kon."` for me.

**Comment by spencermountain** [comment]
hi Paweł, which version are you using? I don't believe we have a `.plaintext()` method anymore.
you may want to use this:
```javascript
nlp.sentence('dom, kon. XIX w.').normal()
//dom kon xix w.
```
cheers

**Comment by yarl** [comment]
I was using [version from npm](https://www.npmjs.com/package/wtf_wikipedia).

**Comment by spencermountain** [comment]
ahhh. sorry. my brain... 
I'm maintaining [another software project](https://github.com/nlp-compromise/nlp_compromise), and got confused ;)
let me do this properly this weekend, when I have proper attention for this. It seems like a great, and solvable bug
cheers

**Comment by spencermountain** [comment]
sorry for the delay on this Paweł, I'm going to get to it this week.
thanks for your patience

**Comment by spencermountain** [comment]
hey Paweł, this was a good bug. got it, fixed in v4.0.1
thanks!
