### ISSUE TITLE
Wrong date parsing

### ISSUE THREAD

**Issue by pavlo-vasylkivskyi-scx** [spencermountain/wtf_wikipedia#312]
Hello. Currently in our project we use your module a lot. Thank you for your work. But I have bad news ;) Today we found a bug. If you will check topic https://en.wikipedia.org/wiki/Winston_Churchill there are some dates and your module when making parsing of that page not returned **30 November 1874 – 24 January 1965**, it returns dates in parsed like this **30 November 187424 January 1965**. Can you please check this issue. Thanks one more time.
![Screen Shot 2019-10-02 at 17 43 00](https://user-images.githubusercontent.com/50583998/66054076-2569cd00-e53c-11e9-8c93-f891b8bdb4c2.png)
![Screen Shot 2019-10-02 at 17 42 25](https://user-images.githubusercontent.com/50583998/66054077-2569cd00-e53c-11e9-88b0-6e201462c7b2.png)

**Comment by spencermountain** [comment]
thanks Pavlo, yes that does look like a bug. I'll check it out.
cheers
