### ISSUE TITLE
isDisambiguation() doesn't work for article Ho

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#313]
Hey, trying to find out which article is Disambiguation and for article https://en.wikipedia.org/wiki/Ho it returns false.
![image](https://user-images.githubusercontent.com/435827/66138610-94f8be80-e607-11e9-8508-8bbb9f875f3a.png)

**Comment by spencermountain** [comment]
weird. it seems to have the `{{disambiguation|geo|surname}}` template.
sounds like a bug.
