### ISSUE TITLE
Images in Infobox.logo property

### ISSUE THREAD

**Issue by pavlo-vasylkivskyi-scx** [spencermountain/wtf_wikipedia#314]
Hi again. Seems to have found a new bug. As a result of the Wikipedia article parsing (https://en.wikipedia.org/wiki/Wikipedia) does not have some pictures, I attach few links below
https://en.wikipedia.org/wiki/Wikipedia#/media/File:Wikipedia-logo-v2.svg
https://en.wikipedia.org/wiki/Wikipedia#/media/File:Wikipedia_wordmark.svg
https://en.wikipedia.org/wiki/Wikipedia#/media/File:Wikipedia_Main_Page.png
https://en.wikipedia.org/wiki/Wikipedia#/media/File:Jimmy_Wales_September_2015.jpg
https://en.wikipedia.org/wiki/Wikipedia#/media/File:L_Sanger.jpg
https://en.wikipedia.org/wiki/Wikipedia#/media/File:Jimbo_at_Fosdem_cropped.jpg

**Comment by spencermountain** [comment]
hey Pavlo, how did you get these results?
this seems to work for me:
```js
wtf.fetch('Wikipedia', 'en', function(err, doc) {
  console.log(doc.images().map(i => i.thumb()))
})
```
cheers

**Comment by pavlo-vasylkivskyi-scx** [comment]
Hello, here is my example of using your module and the result (It is red because of linter): where are not all pictures.
1) Screenshot how I am using module
2) your example 
3) result (in both cases is the same)
4) example of image that I need from 'Wikipedia' article

I don't know, maybe I am doing something wrong
But this code works well for all another topics - I getting all images that I need
![Screen Shot 2019-10-07 at 14 10 03](https://user-images.githubusercontent.com/50583998/66307237-962e3200-e90c-11e9-94ba-4efb3717fffb.png)

![Screen Shot 2019-10-07 at 13 50 28](https://user-images.githubusercontent.com/50583998/66307051-05efed00-e90c-11e9-9b4f-aa5f5bceb249.png)
![Screen Shot 2019-10-07 at 14 09 34](https://user-images.githubusercontent.com/50583998/66307092-20c26180-e90c-11e9-8867-ce3102f4befe.png)
![Screen Shot 2019-10-07 at 14 10 03](https://user-images.githubusercontent.com/50583998/66307138-48192e80-e90c-11e9-84cf-c1f7fd2add46.png)

**Comment by spencermountain** [comment]
ya, my guess is there's an issue with encoding, or how the page is getting loaded, if you're loading the document in a non-standard way. It may be the `#` in the url?
I've never seen that output format before. 
Take a look at [the api](https://observablehq.com/@spencermountain/wtf_wikipedia-api?collection=@spencermountain/wtf_wikipedia#image) for `.images()` results. You may be able to get what you need with a `.images().map(i=>i.data())` call.

cheers

**Comment by pavlo-vasylkivskyi-scx** [comment]
Hello, thank you for your response. I'm not sure that we are on the same page. Main issue here is that wtf_wikipedia does not return 2 images.
![Screen Shot 2019-10-08 at 13 18 23](https://user-images.githubusercontent.com/50583998/66388239-5596ed00-e9ce-11e9-8d09-f2d594fad7f0.png)
I have checked different properties (`.images().map(i=>i.data`) but it not there.
Maybe it could not parse because there are 2 images in one field 
![Screen Shot 2019-10-08 at 13 24 16](https://user-images.githubusercontent.com/50583998/66388509-f8e80200-e9ce-11e9-89a0-cfe0f15b5676.png)

**Comment by spencermountain** [comment]
ah, i see what you mean.
```js
let str = `{{Infobox website
  | name = Wikipedia
  | logo = [[File:Wikipedia-v2-logo.svg|150px|frameless|An incomplete sphere made of large, white, jigsaw puzzle pieces. Each puzzle piece contains one glyph from a different writing system, with each glyph written in black.]]<br />[[File:Wikipedia wordmark.svg|200px|The Wikipedia wordmark which displays the name Wikipedia, written in all caps. The W and the A are the same height and both are taller than the other letters, which are also all the same height.]]
}}`
// console.log(wtf(str).images())
let s = wtf(str)
  .infobox(0)
  .get('logo')
console.log(s.json())
```

yeah, this looks like a tricky case. We look for images in some infobox params, but `logo` doesn't appear to be one of them. Also, the inline images can't be parsed out of the infobox, because it returns Sentence objects. it's one big mess.

I'm looking at a medium-size refactor of this library this winter, and will include this in the planning for it.
Thanks

**Comment by pavlo-vasylkivskyi-scx** [comment]
Ok. I understand. Once again thank you for your work. Have a nice day

**Comment by spencermountain** [comment]
hey Pavlo, this works now, in `v8.0.0`
cheers
