### ISSUE TITLE
Missing categories

### ISSUE THREAD

**Issue by Patrik-scx** [spencermountain/wtf_wikipedia#315]
Hello @spencermountain, I hope you fine.

Could you please check how I can retrieve categories for [Sony Television](https://en.wikipedia.org/wiki/Sony_Television), as I can't get them with doc.categories();

**Comment by waldenn** [comment]
Hi Patrik. That article has no direct categories, see its [wiki-text](https://en.wikipedia.org/w/index.php?title=Sony_Television&action=edit).

The complex [{{SIA}}](https://en.wikipedia.org/w/index.php?title=Template:Set_index_article&action=edit) template seems to add a "Set indices" category.

**Comment by Patrik-scx** [comment]
Thanks @waldenn
