### ISSUE TITLE
korean wiki markdown text  parsing error

### ISSUE THREAD

**Issue by drumtj** [spencermountain/wtf_wikipedia#325]
hi
i'm TJ from south korea.

I'm having trouble parsing Korean Wiki search results.
Perhaps there is a difference between English and Korean in word-breaking regular expressions.

In wiki markdown text, the keyword "File:" appears as "파일:" in Korean, so you need to modify the regular expression.

Also, in word recognition regular expressions, \ b throws an exception in Korean.

I hope this tip helped you.

**Comment by spencermountain** [comment]
hey TJ! Yeah, it would be amazing (and it should be possible) to parse structured data out of ko-wikipedia. You're right, it may be some sloppy regular expressions.

I just played around a little bit and got images working by adding `'파일'` for file and `'분류'` for category [here](https://github.com/spencermountain/wtf_wikipedia/blob/dev/src/_data/i18n.js).

Can you help me find the terms for `Template, Infobox, and Disambig`? I'd be happy to release this improvement asap.
cheers

**Comment by spencermountain** [comment]
hey TJ, this has been massively improved in `v8.0.0`
please let me know if you see any missing translations in ko.wikipedia
thanks!
