### ISSUE TITLE
Wrong first paragraph for topic 2014

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#328]
Hey @spencermountain 
I've noticed that for topic 2014 https://en.wikipedia.org/wiki/2014 I get the wrong first paragraph
Actual:
![Screenshot 2020-01-02 at 11 54 32](https://user-images.githubusercontent.com/435827/71661430-cdb74980-2d56-11ea-8716-4b9943ae2732.png)
Expected:
![Screenshot 2020-01-02 at 11 55 54](https://user-images.githubusercontent.com/435827/71661461-e6276400-2d56-11ea-8b98-c3e479ec1839.png)

**Comment by spencermountain** [comment]
ah gross, it looks like that sentence is being transcluded from [this template](https://en.wikipedia.org/wiki/Template:Year_article_header)

You'll have to fetch it manually - I'm not sure we have a good solution to this problem right now.

**Comment by spencermountain** [comment]
merging with #223
