### ISSUE TITLE
Instruction for writing new templates

### ISSUE THREAD

**Issue by hpb-htw** [spencermountain/wtf_wikipedia#329]
I use this library to parse pages form https://de.wiktionary.org/ . They are in Germany and there are no t so many template for deutsche Wörterbuch. I read the code but find not so much about template with multiple lines like 

```
{{Bedeutungen}}
:[1] [[Lerntechnik]] zur aktiven Aneignung einer bestimmten Fertigkeit, das praktische [[üben|Üben]]
:[2] Anschauungsmaterial, Text oder Aufgabe zum Trainieren
:[3] {{K|Recht}} das übliche Vorgehen in einem bestimmten Bereich
:[4] {{K|Hochschule}} Lehrveranstaltung, in der die Anwendung theoretischer Kenntnisse auf praxisnahe und spezifische Problemstellungen erfolgt
```
can somebody show me how can I write extends code for those templates?

**Comment by spencermountain** [comment]
hi @hpb-htw , this is a good question.
That does look like a pretty weird template.
If I can remember, we support some of these with a straight-regexes, I looked briefly but couldn't find an example. 

In short, there's nothing helpful right now, but I'd be happy to support this. Can you give me an example of where you found it?

I've got some big plans for improving this process this year, so I hope this sort of thing becomes easier.
cheers

**Comment by hpb-htw** [comment]
> Can you give me an example of where you found it?

I found them for example here: https://de.wiktionary.org/wiki/%C3%9Cbung They (entries in https://de.wiktionary.org) have the same schema. They are also documented on the „Hilfe Seite“ https://de.wiktionary.org/wiki/Hilfe:Formatvorlage (in German). 

Some common multiple-line template are:
* `{{Worttrennung}}`
*  `{{Aussprache}}`
*  `{{Bedeutungen}}`
* `{{Herkunft}}`
*  und of course `{{Beispiele}}`

Some of other template are single-line, therefore they are relativ easy to implements. When I'm finish, with them, I'll make a pull request to master. :)

**Comment by spencermountain** [comment]
Thank you. That's helpful.
I'm looking at splitting-out wiktionary/other templates into a plugin, so that we can support the long-tail, like this. It may take me the winter, but this will ideally really help with this sort of thing.

if you need a quick+dirty solution, i can help you with a regex-based one.
cheers

**Comment by hpb-htw** [comment]
Hi, 
I have time. Now I write code for single-line template. So don't worry about it.

> I'm looking at splitting-out wiktionary/other templates into a plugin, so that we can support the long-tail, like this.
I think it is a good idea. There would be no One-size-fit-all Parser for all Wikipedia format.

**Comment by spencermountain** [comment]
hey @hpb-htw instructions for adding new templates [are here](https://github.com/spencermountain/wtf_wikipedia#configuration) as of v8.

handling templates that spawn multiple templates is still not supported, but will merge into #302
