### ISSUE TITLE
Complete url of images

### ISSUE THREAD

**Issue by soyjavi** [spencermountain/wtf_wikipedia#33]
any way to get the full url of the images?

best,

**Comment by spencermountain** [comment]
I really don't know what you're suggesting. Which images?

**Comment by soyjavi** [comment]
Sorry for my poor explanation about my issue. The attribute `images` holds something like: 

```
[ 
     'File:Leonardo DiCaprio.jpeg',
     'File:Leonardo DiCaprio 2002.jpg',
     'File:Leonardo DiCaprio by David Shankbone.jpg',
     'File:Leonardo DiCaprio (Berlin Film Festival 2010) 2 (cropped).jpg',
     'File:InceptionCastPremiereJuly10.jpg',
     'File:Leonardo DiCaprio avp 2013 3.jpg',
     'File:Leonardo DiCaprio.jpg',
     'File:Leonardo DiCaprio January 2014.jpg'
]
```

... and it will very helpful have the complete url of the file ('http://....')

best

**Comment by spencermountain** [comment]
ahh, yeah sorry.
I woke up in the night being like, -- oh that was the other repo -- 🐙 

yeah, from what i remember that's harder than it looks, but it would be really useful.
going from `File:Leonardo DiCaprio.jpeg`  to `https://upload.wikimedia.org/wikipedia/commons/f/f9/Leonardo_DiCaprio.jpeg`
means some funny business, and they get renamed and stuff. Do you know how it works?

**Comment by spencermountain** [comment]
i think i remember it being a hash of the filename or something [wanna check it out?](https://en.wikipedia.org/wiki/Help:File_page#File_page_location)

**Comment by soyjavi** [comment]
The problem is get the middle part, for example for the `https://en.wikipedia.org/wiki/File:Leonardo_DiCaprio.jpeg` the real url of the image is `https://upload.wikimedia.org/wikipedia/commons/f/f9/Leonardo_DiCaprio.jpeg` and I dont have idea how can I get `/f/f9` part. I read is

**Comment by spencermountain** [comment]
yeah, let me know if you can figure it out. From what i remember there was a need to call the wikipedia api *on each image* 😓 😓 

...ok, i've got a theory. md5 hash the string `Leonardo_...` and see if the first three characters are `ff9`. I think that's a *thing* for making directories smaller. Good luck!

**Comment by soyjavi** [comment]
Yes, looks like will be quite hard :( ... but if not `images` attribute don't have value :(

**Comment by zatteo** [comment]
a little late but the official explanation is here https://commons.wikimedia.org/wiki/Commons:FAQ#What_are_the_strangely_named_components_in_file_paths.3F

**Comment by spencermountain** [comment]
Théo you did it!
yeah, i'm happy to implement this.
f'in wikipedia... ;)

**Comment by spencermountain** [comment]
got it! check-out v0.5.0, when you have some time
cheers!

**Comment by spencermountain** [comment]
oop, 0.5.1

**Comment by zatteo** [comment]
yeah !

**Comment by soyjavi** [comment]
🖖
