### ISSUE TITLE
Image urls are restricted to server 'https://wikipedia.org/wiki'

### ISSUE THREAD

**Issue by lawrence-hoo** [spencermountain/wtf_wikipedia#330]
When fetching `doc`, one of the available options is to specify a `wikiUrl` in order to use this library to parse pages from various wikis which is awesome.

However, I've run into a small problem when it comes to getting image urls since they're always prefixed with 'https://wikipedia.org/wiki/Special:Redirect/file/'
https://github.com/spencermountain/wtf_wikipedia/blob/32da0b538cd0b2754dc15deef7a3337797d5d803/src/image/Image.js#L6
which doesn't appear to work if I've specified a different wiki in `wikiUrl`.

It would be great if there was a way to specify a different `server` string that ends up getting prefixed to the urls returned in `Image`'s `url()` and `thumbnail()` methods.
https://github.com/spencermountain/wtf_wikipedia/blob/32da0b538cd0b2754dc15deef7a3337797d5d803/src/image/Image.js#L55-L62

**Comment by spencermountain** [comment]
+1 
I completely agree.
Will add this to v8 milestone.
thanks

**Comment by spencermountain** [comment]
been thinking more about this - we should try to fit it automatically based on current wiki/url, but probably also allow it to be set using a parameter in `.images(imgUrl)`.

A lot like #260 . Title, lang, wiki url, and img url, ought to be known and easily configurable.

**Comment by spencermountain** [comment]
hey @lawrence-hoo out of curiosity, which wiki were you using?
I've looked at a few 3rd-party wikis, and the image paths seem to be all different. There seems to be some kind of cdn setup.

You can always call `.images().map(img=>img.json())` to get the filename information manually.
But I'd like to have a good solution to this, just may need some advice.
cheers

**Comment by lawrence-hoo** [comment]
Hey @spencermountain , I'm using Bulbapedia (url: `https://m.bulbapedia.bulbagarden.net` - I had to use the mobile path to be able to fetch the images when I access my app from my phone - but that's not really important to this).

To get the urls for the images I needed, I ended up just grabbing the image file name(s) from `doc.infobox().toJson()` and then prepending the correct image url path to it/them (that image url path being: `https://m.bulbapedia.bulbagarden.net/wiki/Special:Redirect/file/${imageFileName}`).

Since I ended up needing the rest of that infobox json data anyway, I don't actually stand to gain much from this issue's resolution anymore haha. That said, I'm of course happy to help with this issue/use case if I can be of any assistance :)

**Comment by spencermountain** [comment]
hey, this is implemented now in 8.4.0
```js
wtf.fetch('https://bulbapedia.bulbagarden.net/wiki/Aegislash_(Pok%C3%A9mon)', { path: 'w/api.php' }).then((doc) => {
  console.log(doc.images().map((j) => j.url()))
})
```
cheers

**Comment by lawrence-hoo** [comment]
@spencermountain Eyyyyy, that's awesome!

**Comment by niebert** [comment]
Hi Spence, this solution for images is also related to generic principle, how to treat URLs in wiki markdown. We need the server path with a prefix to expand relative links in Wiki markdown into absoltue links. So I guess, it makes sense to store the server path e.g. `https://bulbapedia.bulbagarden.net` or `https://de.wikiversity.org` into the `doc` object. This allows the expansion of URLs of links and image even in output by `doc.html({links:'absolute',images:'absolute'})` (default is `relative`. So 
* a relative link `[[Parser]]` will be expanded with the link prefix `/wiki/` to  `https://de.wikiversity.org/wiki/Parser` and 
* an image `my_image.jpg` will be expanded with the prefix `/wiki/Special:Redirect/file/` to  `https://de.wikiversity.org/wiki/Special:Redirect/file/my_image.jpg`

**Comment by spencermountain** [comment]
yeah, I like that solution too.
Seems pretty doable. I haven't done any work on the html plugin. It needs a lot of care.
