### ISSUE TITLE
how can i change it to work for https://commons.wikimedia.org/

### ISSUE THREAD

**Issue by aloukikomar** [spencermountain/wtf_wikipedia#331]
`wtf_wikipedia File:Vincent van Gogh - Sunflowers - VGM F458.jpg --json`

 {"title":"File:Vincent van Gogh - Sunflowers - VGM F458.jpg","pageID":43244283,"categories":[],"sections":[{"title":"","depth":0,"templates":[{"list":["Vase with Fifteen Sunflowers"],"template":"featuredpicture"},{"list":["2016-06-07"],"template":"picture of the day"}]}]}

**Comment by waldenn** [comment]
Hi Omar,

If you have the image-filename, you can get the JSON-data or directly access the image / thumbnail.

See the first two comments [here](https://discourse-mediawiki.wmflabs.org/t/accessing-a-commons-thumbnail-via-wikidata/499/2).

**Comment by aloukikomar** [comment]
hi @waldenn , i didnt understand , i am trying to change the wiki we use

**Comment by waldenn** [comment]
I don't think you can query wikicommons using wtf_wikipedia (perhaps I'm wrong on this).

You can use the [Commons API](https://commons.wikimedia.org/wiki/Commons:API/MediaWiki) and get back file metadata or use the [search API](https://stackoverflow.com/questions/51914653/searching-for-files-in-wikimedia-wikipedia/52005541#52005541) for finding certain files.

**Comment by spencermountain** [comment]
hey @aloukikomar , you're right, the image path is hard-coded right now to the main CDN, though this may not the best one to use.
We should make this easier in the upcoming releases this winter.

If I can remember, the url generation is quite involved. I remember it using md5 hashing, at some point, to determine the proper url. but the current url generation is done [here](https://github.com/spencermountain/wtf_wikipedia/blob/master/src/image/Image.js#L6) if you want to fork and poke around.

If you find a better way to retrieve images, I'd be happy to hear your results. We changed it in #86 .
cheers

**Comment by crystalfp** [comment]
And what about Wiktionary? For example, this word [entry](https://it.wiktionary.org/w/index.php?title=casa&format=printable) and the corresponding [raw](https://it.wiktionary.org/w/index.php?title=casa&action=raw) text?
Thanks for clarifying!
mario

**Comment by spencermountain** [comment]
ah, good point. ya it.wiktionary seems to work with the current url scheme:

https://upload.wikimedia.org/wikipedia/commons/2/24/Kohila_vesiveski2.jpg

but yes, i never thought about this either

**Comment by crystalfp** [comment]
Well, in `src/_fetch/_url.js` there is a reference to `options.wikiUrl` to change the url from `https://${lang}.wikipedia.org/w/api.php` So it seems doable, but where could I set this `wikiUrl`?
Thanks!
mario

**Comment by spencermountain** [comment]
hey mario, this should do the trick. Sorry for the undocumented dark-magic:
```js
wtf
  .fetch('casa', 'it', {
    wikiUrl: `https://it.wiktionary.org/w/api.php`
  })
  .then(function(doc) {
    console.log(doc.images().map(img => img.json()))
  })
```
cheers

**Comment by crystalfp** [comment]
Perfect! Now I have only to find how to extract the synonyms, but this is another problem.
Thanks!
mario

**Comment by spencermountain** [comment]
hey @aloukikomar you can do this now with v8 and `wtf-plugin-image`:
```js
const wtf = require('wtf_wikipedia')
wtf.extend(require('wtf-plugin-markdown'))

wtf.fetch('casa', 'it', { wiki: `wiktionary` }).then(async function(doc) {
  let image = doc.images(0)

  //instead of using the redirect api, generate a direct img url
  let url = image.commonsURL()
  //https://upload.wikimedia.org/wikipedia/commons/4/4e/RybnoeDistrict_06-13_Konstantinovo_village_05.jpg
})
```

**Comment by crystalfp** [comment]
Unfortunately wtf-plugin-markdown crashes. See #341
