### ISSUE TITLE
br tag breaks table parsing

### ISSUE THREAD

**Issue by tstibbs** [spencermountain/wtf_wikipedia#332]
I've noticed wtf_wikipedia doesn't support `br` tags in table rows. What seems to happen is that the br acts like a new line of markup, pushing the columns to the right.

I think what's going wrong is that [kill_xml](https://github.com/spencermountain/wtf_wikipedia/blob/fc8dba650a06143c0914744b290bb705a3583f74/src/01-document/preProcess/kill_xml.js#L46) replaces the br with a newline, but then the actual [table row parser](https://github.com/spencermountain/wtf_wikipedia/blob/fc8dba650a06143c0914744b290bb705a3583f74/src/02-section/table/parse/_findRows.js#L43) doesn't make any attempt recombine those elements into a single row.

Trying the below markup in the wikipedia sandbox results in the expected rendering whether it uses a `br` or a newline, so I don't think it's `kill_xml` that's at fault here - I think the row parser needs to be able to recombine multiple lines into a single column. I'm not confident enough that this is the right fix to submit a PR just yet, so I'd welcome some input from others. I'm also not sure how best to represent the newline within the column value - how is this handled elsewhere?

To reproduce run the following:

    const wtfWikipedia = require("wtf_wikipedia");

    let inputData = `
    {| class="wikitable"
    |-
    ! a
    ! b
    ! c
    |-
    | a
    | b1<br />b2
    | c
    |}
    `

    let doc = wtfWikipedia(inputData);
    console.log(doc.tables()[0].json()[0]);

expected output:

    {
      a: { text: 'a' },
      b: { text: 'b1<some kind of br tag or newline here>b2' },
      c: { text: 'c' }
    }
actual output:

    {
      a: { text: 'a' },
      b: { text: 'b1' },
      c: { text: 'b2' },
      col4: { text: 'c' }
    }

**Comment by spencermountain** [comment]
ah! good point. This makes perfect sense, and is a great issue. Thank you.
We should probably replace the br tag with a space. That wouldn't effect anything else, I don't think - the line-break isn't kept. 
what do you think?

**Comment by tstibbs** [comment]
Yes I think I agree we could just drop the newline - I think it would rarely have any semantic meaning in that context so would be fine to replace with a space.
