### ISSUE TITLE
Requests being blocked

### ISSUE THREAD

**Issue by tstibbs** [spencermountain/wtf_wikipedia#334]
Over the last few days I've started seeing that more than about 5 requests to wikipedia in the space of a minute get blocked with a 429 error and the following response:

    Scripted requests from your IP have been blocked, please contact noc@wikimedia.org, and see also https://meta.wikimedia.org/wiki/User-Agent_policy

Setting the `Api-User-Agent` as suggested in the docs doesn't seem to help. However setting the `User-Agent` header instead (testing by hacking [_request.js](https://github.com/spencermountain/wtf_wikipedia/blob/master/src/_fetch/_request.js#L8)) did seem to fix the issue. Can't explain why I've only suddenly started seeing this, but wondering if the header needs to change or a second header is needed?

**Comment by spencermountain** [comment]
i believe they have [a casual rate-limit](https://www.mediawiki.org/wiki/API:Etiquette) on their api.
I really don't know.

**Comment by tstibbs** [comment]
@spencermountain would you accept a PR to allow the `User-Agent` header to be set in addition to the `Api-User-Agent`? This does seem to fix it for whatever reason.

**Comment by spencermountain** [comment]
sure!
sorry about that first message, hadn't had my coffee yet.
