### ISSUE TITLE
Lists and sentences parsing error on topic "Meanings_of_minor_planet_names%3A_397001–398000"

### ISSUE THREAD

**Issue by pavlo-vasylkivskyi-scx** [spencermountain/wtf_wikipedia#338]
Hey,🤗 How are you? I recently found new issues with lists and sentences on the topic "[Meanings of minor planet names: 397001–398000](https://en.wikipedia.org/wiki/1808_United_States_House_of_Representatives_election_in_Connecticut)"
![Screen Shot 2020-03-05 at 17 32 05](https://user-images.githubusercontent.com/50583998/75997779-842adc80-5f08-11ea-9835-a521ae02b1f9.png)
![Screen Shot 2020-03-05 at 17 32 44](https://user-images.githubusercontent.com/50583998/75997781-842adc80-5f08-11ea-8aba-a77a52cc0978.png)

And sentences are empty 

![Screen Shot 2020-03-05 at 17 43 06](https://user-images.githubusercontent.com/50583998/75998048-e257bf80-5f08-11ea-9b75-c26042bf9cc5.png)
![Screen Shot 2020-03-05 at 17 43 38](https://user-images.githubusercontent.com/50583998/75998050-e388ec80-5f08-11ea-9084-8f58333d6c9e.png)

It would be nice if you could fix these issue
Thank you for your work 🙏 and have a nice day 😊

**Comment by spencermountain** [comment]
hey @pavlo-vasylkivskyi-scx i don't see any bgcolor syntax in that article, are you sure it's the right one?
maybe it has changed.
thanks
