### ISSUE TITLE
Another issue with sentences

### ISSUE THREAD

**Issue by pavlo-vasylkivskyi-scx** [spencermountain/wtf_wikipedia#339]
Hey 🤗 It's me again 😩
I found another issue with sentences parsing on topic Editing No. 44 Squadron RAF.
wtf_wikipedia is cutting the first sentence 😢

![Screen Shot 2020-03-06 at 13 29 01](https://user-images.githubusercontent.com/50583998/76080029-b2fb8e00-5fae-11ea-9c17-276fdafe346f.png)

![Screen Shot 2020-03-06 at 13 28 38](https://user-images.githubusercontent.com/50583998/76080036-b55de800-5fae-11ea-922a-ab82bfa31b8c.png)

**Comment by spencermountain** [comment]
fixed on dev, will release as 8.1.0
cheers
