### ISSUE TITLE
Infobox parsing failure

### ISSUE THREAD

**Issue by d1231** [spencermountain/wtf_wikipedia#34]
Hi,

I using the library and I found issue with the infobox. 

There are some pages where not all infobox data is parsed, for example the following page: https://en.wikipedia.org/wiki/Boudewijn_Zenden
Many keys are missing for example: club1, birthday

I managed to find the reason for the issue, for some keys (detonated by '|') there is no leading \n and  some values are contains '|' or '=' and so the library don't parse it.

I fixed it, using regex and iterating over all possible keys. If you want I could make a pull request or give you my code.

Thanks

**Comment by spencermountain** [comment]
hey! yes ofcourse!
