### ISSUE TITLE
Null Return Value

### ISSUE THREAD

**Issue by arvinkx** [spencermountain/wtf_wikipedia#348]
Hi - I seem to have an issue retrieving a specific template. Using the observable demo for coronavirus data located at https://observablehq.com/@spencermountain/parsing-wikipedias-coronavirus-outbreak-data?collection=@spencermountain/wtf_wikipedia and replacing the fetch string and putting "Template:2019–20 coronavirus pandemic data/United States/California medical cases chart" in place doesn't return any data. The page I'm looking at is: https://en.wikipedia.org/wiki/Template:2019%E2%80%9320_coronavirus_pandemic_data/United_States/California_medical_cases_chart. 

The doc object returned seems to be null even though other templates work. Is there something preventing the retrieval of this specific template or am I making an error in usage? Thanks

**Comment by spencermountain** [comment]
oh hey Arvin, thanks for this. These templates keep changing at a high speed.
You're right, there's a bug. I'll try to fix it today.

**Comment by spencermountain** [comment]
fixed in `8.1.2`
thanks for the headsup.

**Comment by spencermountain** [comment]
to get the data for that template:
```js
wtf.fetch('Template:2019–20 coronavirus pandemic data/United States/California medical cases chart').then((doc) => {
  console.log(doc.template('medical cases chart'))
})
```

**Comment by arvinkx** [comment]
Works great - thanks for the quick fix. I very much appreciate it.

**Comment by arvinkx** [comment]
I've run into this issue again - it seems as though that chart is not able to be fetched the same way anymore. Is there a way to more permanently fetch the CA chart? When I try to fetch the template, "medical cases chart" no longer exists but when I navigate to the actual wikipedia site, it is there.

**Comment by spencermountain** [comment]
oh, looks like they've added an `#Invoke` label on the template.
will try to fix this tomorrow.

**Comment by spencermountain** [comment]
Invoke syntax now supported.
template works again in `8.2.1`.
cheers

**Comment by arvinkx** [comment]
Fantastic - thanks again for the help and the wonderfully, helpful library.
