### ISSUE TITLE
make template position (using the section title) work again

### ISSUE THREAD

**Issue by waldenn** [spencermountain/wtf_wikipedia#350]
Hey,

I'm trying to create a PR to make the template position (using the section title) work again, as I your major update broke that feature and my project requires that to work.

I looked through the code and found I could do:

```js
  var allTemplates = function allTemplates(section) {
    var wiki = section.wiki; // nested data-structure of templates
    var list = find(wiki, section.title);
```
To have the section titles for each template. The issue I still have is how to get the template-object calls to use that info:

`var parser = function parser(tmpl, order, fmt )`

("tmpl" is the template-body-text here, as you ofcourse know)

Side note: I personally prefer to add objects as arguments (and preferably only one single-argument if possible). This avoids argument ordering issues and allows the input of a function to grow without modifying all the callers each time some extra info is added. So eg.: function parser( { text: '...', order: '...', fmt: '...', pos: '...' } );

What would be a a good way to add to the template-position again for these template calls from [here](https://github.com/spencermountain/wtf_wikipedia/blob/c37f07f82f9866c26c1b80c15567c0f027f853bc/src/template/parse.js)?

Thanks!

**Comment by spencermountain** [comment]
hey, I like the new rebrand!
I apologize for the breaking change, i'm not fully clear about what the template position is - are you looking for character offsets or something?
you can get the section each template is in with:
```js
doc.sections().forEach(s=> {
  s.templates().forEach(t=>{
    console.log(s.title(), t.template)
  })
})
```
i feel like i've mis-understood the question though.

ya, feel free to clean-up any of the function calls - I agree that there's a lot of mess in there. prs always welcome

**Comment by waldenn** [comment]
> hey, I like the new rebrand!
> I apologize for the breaking change, i'm not fully clear about what the template position is - are you looking for character offsets or something?

No problem, great to just see you keep working on this library!

I just needed the section each template is in. Nothing complicated.

> you can get the section each template is in with:
> 
> ```js
> doc.sections().forEach(s=> {
>   s.templates().forEach(t=>{
>     console.log(s.title(), t.template)
>   })
> })
> ```

Hmm, maybe thats a much better/easier solution indeed (which I overlooked), I will try this soon. If it works I'll close the issue. Thanks man!

> ya, feel free to clean-up any of the function calls - I agree that there's a lot of mess in there. prs always welcome

Yes, I will take a look. Though I get confused a bit in all the calls and some duplicate function names like "parseTemplate". Some dev-docs would be a very good thing I think, to make it easier for others to get into the structure and data flow.

**Comment by waldenn** [comment]
Is it possible to not use "require()" when including plugins? (I have the "wtf-plugin-html.js" already loaded.)

> wtf.extend(require('wtf-plugin-html'))

**Comment by spencermountain** [comment]
yeah, the plugin should be set on `window.wtfHtml`, although you may need to update to `0.1.2`, as I wasn't exporting that properly until, like, just now.

**Comment by waldenn** [comment]
Ok, great. (I will upgrade my tooling to use some builder soon, but ran into some issues with one or two libraries, and just skipped that whole build toolchain thing, need to get that fixed.) 

So after calling: wtf.extend( window.wtfHtml ). I get this error when using toHtml():

> TypeError: can't convert undefined to object wtf-plugin-html.js:[354](https://github.com/spencermountain/wtf_wikipedia/blob/cbb3ea359f2a5259a1a84d360155ba7318e736fd/plugins/html/builds/wtf-plugin-html.js#L354):12

wtf.fetch() does work fine.

**Comment by waldenn** [comment]
Ok, issue fixed.. my bad. It was caching the wtf library (even with a hard-refresh). Many thanks for the help Spencer!
