### ISSUE TITLE
v9: Wikivoyage (etc) template coverage as plugins

### ISSUE THREAD

**Issue by davelowndes** [spencermountain/wtf_wikipedia#354]
Comes from WikiVoyage page 'Lewisburg (West Virginia)', wiki markup below.

I believe the content should be in a list or in a paragraph, but not both? Is it expected (or known) behaviour? I'll try and debug if I can find time, some hints on what's possibly causing it would help. 

Thanks

```
===Events===

* {{do
| name=The Battle of Lewisburg | alt= | url=http://www.battleoflewisburg.org/ | email=
| address= | lat= | long= | directions=
| phone = +1 304-645-6910 | tollfree= | fax=
| hours= | price=
| content=Held in late May. Living history and re-enactment of the 1862 Battle of Lewisburg. Historical exhibits, recreated military camp and lantern tours, period dress events, dance, parades.
}}
* '''The Shanghai Parade,'''
A 150-year tradition held at New Year's Day, this parade is a relic of the Old Christmas celebrations before the calendar switched over. An excellent glimpse of the past with people dressing in costumes and marching downtown. Shops are open!

* {{listing | type=do
| name=West Virginia State Fair | alt= | url=http://statefairofwv.com | email=
| address=107 W Fair Street | lat= | long= | directions=
| phone= | tollfree=
| hours=M-F 8AM-11PM, Sa Su 8AM-midnight | price=
| content=Held in mid-August. Live music and entertainment, carnival rides, juried competitions, talent contest, harness racing, West Virginia showcase, concessions. Admission $9.
}}
* '''Taste of Our Towns''', downtown Lewisburg. Held one Saturday in October. Sample regional foods plus specialties from the Greenbrier, Tamarack and local restaurants.

```

![listing_para](https://user-images.githubusercontent.com/327084/80207243-eccd4480-8681-11ea-8fbb-0aa9b968bc0b.PNG)

**Comment by spencermountain** [comment]
hey @davelowndes ya, it looks like those wikivoyage templates `do` and `listing` just create astrix lists from their properties- I'd like to learn the major properties of wikivoyage et al.
 but for now you should be able to do something like this:
That's the best way to handle this properly,
but for now you could rig-up something like this:
```
wtf.extend((_, templates) => {
  templates.listing = function (tmpl) {
    // parse it here
  }
})
```
will try to support these 2 templates -  if there are other high-priority ones, let me know

**Comment by FunMiles** [comment]
I am not sure if this could be covered in the same way, but in wikivoyage, some of the list parse into 2 separate arrays. Re-constructing the binding between items in the two arrays is a bit of a pain. I am surprised it is not a single array with two children. One for the `marker` template item and one with the text.
Example: the following code:
```
*{{marker|type=city|name=[[Thimphu]]|url=|lat=27.466667|long=89.641667|wikidata=Q9270}} (Dzongkha: ཐིམ་ཕུ) – The capital city
*{{marker|type=city|name=[[Jakar]]|url=|lat=27.55|long=90.733333|wikidata=Q2468415}} (Dzongkha: བྱ་ཀར) – An administrative town in the north and the birthplace of Buddhism in Bhutan.
*{{marker|type=city|name=[[Mongar]]|url=|lat=27.275|long=91.24|wikidata=Q2582611}} (Dzongkha: མོང་སྒར) – One of the largest towns in east Bhutan.
*{{marker|type=city|name=[[Paro]]|url=|lat=27.433333|long=89.416667|wikidata=Q862041}} (Dzongkha: སྤ་རོ་) – The location of the international airport and Taktsang Monastery.
*{{marker|type=city|name=[[Punakha]]|url=|lat=27.616667|long=89.866667|wikidata=Q826112}} (Dzongkha: སྤུ་ན་ཁ་) – A former winter capital of Bhutan.Still hosts the Monastic Body in Winter.
*{{marker|type=city|name=[[Phuentsholing]]|url=|lat=26.85|long=89.383333|wikidata=Q856162}} (Dzongkha: ཕུན་ཚོགས་གླིང་) – A town on the Indian border. The point of entry for travellers arriving by bus from [[Kolkata]].
*{{marker|type=city|name=[[Samdrup Jongkhar]]|url=|lat=26.916667|long=91.616667|wikidata=Q2380103}} (Dzongkha: བསམ་གྲུབ་ལྗོངས་མཁར་) – An administrative town in the southeast, near the Indian border.
*{{marker|type=city|name=[[Trashigang]]|url=|lat=27.333333|long=91.566667|wikidata=Q1149819}} (Dzongkha: བཀྲ་ཤིས་སྒང་།) – A picturesque administrative town in the east.
*{{marker|type=city|name=[[Trongsa]]|url=|lat=27.516667|long=90.5|wikidata=Q1019534}} (Dzongkha: ཀྲོང་གསར) – A small administrative town famous for its dzong and the Tower of Trongsa
```
Parses into the following graph:
<img width="787" alt="Screen Shot 2021-02-02 at 9 14 58 AM" src="https://user-images.githubusercontent.com/7741038/106628535-20a19880-6537-11eb-82eb-71ae176f5f28.png">

**Comment by spencermountain** [comment]
@FunMiles thanks. yeah, that is a good example. We can properly support the {{Marker}} template, which could add a `Thimphu` link, which could make it slightly easier for you, but yeah - you're still going to need to perform the join in some way.

We tried to mitigate this a few versions ago by moving templates data to Section - so you can grab only the templates in that part of the page, but going further and pairing templates to particular sentences would be pretty tricksy. The same problem occurs when people try to match references, or citation-needed templates to sentences - we're just not there yet.

I'll add {{marker}} support to the next release, which should be in mid-February.
cheers

**Comment by FunMiles** [comment]
@spencermountain I appreciate this parser and even if I have to do some _reconstruction_ work, it is very valuable for what I am embarking on. I had started a project ages ago on Android and wrote a wiki parser and know what a mess wikimedia is in... I am moving to a PWA with javascript, and after trying an other parser, this one is way move useful. Thanks for the work. I will probably be able to contribute to the code base once I am further in my project.
Thanks for the hard work. In just a few hours of playing around I already had the parser used in my code.

**Comment by FunMiles** [comment]
@spencermountain, coming back on the marker and link, how would the link work? Would it be placed in the text?
Currently the following, which also has a `{{marker}}` template parses into a text `The , as well as its...`
```
===Theatres===
The {{marker|type=do|name=[[Paris/9th arrondissement#Q187840|Paris Opera]]|lat=48.871944|long=2.331667|image=Paris Opera full frontal architecture, May 2009.jpg}}, as well as its associated ballet company, the Paris Opera Ballet, are considered to be among the premier classical performance companies in the world.
``` 
So without a correctly placed link, I cannot reconstruct the correct text.
Right now the parsing has sentences and sentences have a `formatting` such as italic, which repeats the text being italicized. I wonder if having a series of attributes (including `italic`) having pairs of indices into the text would be a better way to handle thing. In fact, when I saw earlier the stylistic attribute repeating the text, I wonder what happens if the same text appears more than once. Using pairs of indices would avoid this issue.

**Comment by spencermountain** [comment]
yeah, the future version will return `The [[Paris Opera]] as well as`
and `.templates()` will return `{template:'marker', link:'Paris Opera'}` or something like that
and connecting them will be a for-loop or something.

If you want to support the template right now, you can do it with [a plugin](https://observablehq.com/@spencermountain/wtf-wikipedia-plugins)
```js
  wtf.extend((models, templates)=>{
    templates.marker = function(tmpl, list){
    // parse it with a regex here
    list.push({template:'marker', link:'Paris Opera'})
  })
})
```
I know it's not nice, but that should do the trick
cheers

**Comment by FunMiles** [comment]
@spencermountain Thanks. I just experimented and I can certainly tune it for what I need. 
Reading the standard `wikivoyage.js` template parsing source code, I see it calls a function `parse` (`const parse = require('../_parsers/parse')`) Is that function accessible? It seems it would help simplify my coding a bit.

**Comment by spencermountain** [comment]
started new wikivoyage plugin [here](https://github.com/spencermountain/wtf_wikipedia/tree/master/plugins/wikis/wikivoyage)
templates now add the parser function as the 3rd param
enjoy!
