### ISSUE TITLE
how to get cli command working with the options: --html --markdown or --latex?

### ISSUE THREAD

**Issue by waldenn** [spencermountain/wtf_wikipedia#359]
The command works fine with the other output formats, but I see no info on how to use the other formats. Perhaps this broke with moving to the plugin structure and needs some new integration?

Also, the error output mentions the CLI tool is called "wtf_wikipedia":

> throw new Error('Usage: wtf_wikipedia Toronto Blue Jays --plaintext')

Should this not be "cli.js" currently?

I don't use this tool much myself, but thought it was worth an issue.

**Comment by spencermountain** [comment]
good catch, removed the flags on dev.
cheers
