### ISSUE TITLE
single item lists remain unformatted

### ISSUE THREAD

**Issue by waldenn** [spencermountain/wtf_wikipedia#361]
[example](https://conze.pt/app/wtf-debug/?text=*%20baz%0A%0A*%20foo%0A*%20bar%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

This seems to _only_ happen with lists consisting of a single item.

**Comment by spencermountain** [comment]
oh hey, that's a neat tool for debugging.

yeah, i think this was intentional, but may not be ideal. Maybe it's just a safeguard against other uses of astrix.

Is there any examples of this in wikipedia?
cheers

**Comment by waldenn** [comment]
Hey, thanks! Yes, I see many cases like this, especially in "external links" section of articles. Eg. [here](https://en.wikipedia.org/wiki/Constructed_wetland#External_links)

**Comment by wvanderp** [comment]
I think this one is fixed
