### ISSUE TITLE
Support `: foo` syntax as indention

### ISSUE THREAD

**Issue by waldenn** [spencermountain/wtf_wikipedia#362]
[example](https://conze.pt/app/wtf-debug/?text=*%20foo%0A*%20bar%0A%0A%3A%20this%20indentation%20is%20missing%20in%20action%0A%0Abut...%0A%0A%3A%20here%0A%3A%20is%20something%20(just%20out%20of%20order%20also)&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master) 

I suspect this issue is due to some lists not being contained in a section. I have seen this issue also with other elements, eg. the math and chemical tags. This causes only the _inline_ math-tags to be parsable as templates, not the free-standing ones. All content _should_ be in a container section I feel.

**Comment by spencermountain** [comment]
hey @waldenn I've added support for single-item lists, which fixes this issue, but may have some unintended consequences. Let me know if you see anything.
released in `8.3.0`
thanks.

**Comment by waldenn** [comment]
Nice!
