### ISSUE TITLE
tool for linking to render-issues

### ISSUE THREAD

**Issue by waldenn** [spencermountain/wtf_wikipedia#365]
<strike>Would it not be useful to be able to link to an up-to-date wtf_wikipedia rendered HTML page from here? It does not needs to be styled, just a way to see the HTML output for use in discussions like this. Even better: a side-by-side wiki-text to html snippet renderer. </strike>

Ok, I created "**[wtf-debug](https://github.com/waldenn/wtf-debug)**" using [marked](https://github.com/markedjs/marked) and the latest wtf_wikipedia version. Cool thing is that you can link to a document using a [content URL](https://conze.pt/app/wtf-debug/?text=%7B%7BInfobox%20number%0A%7Cnumber%20%3D%201729%0A%7C%20divisor%20%3D%201%2C%207%2C%2013%2C%2019%2C%2091%2C%20133%2C%20247%2C%201729%0A%7C%20unicode%20%3D%20%0A%7C%20greek%20prefix%20%3D%20%0A%7C%20latin%20prefix%20%3D%20%0A%7Cfactorization%3D%20%7D%7D%0A%27%27%271729%27%27%27%20is%20the%20%5B%5Bnatural%20number%5D%5D%20following%20%5B%5B1728%20(number)%7C1728%5D%5D%20and%20preceding%201730.%20It%20is%20a%20%5B%5Btaxicab%20number%5D%5D%2C%20and%20is%20variously%20known%20as%20the%20Ramanujan%27s%20number%20and%20the%20Hardy%E2%80%93Ramanujan%20number%2C%20after%20an%20anecdote%20of%20the%20British%20mathematician%20%5B%5BG.%20H.%20Hardy%5D%5D%20when%20he%20visited%20Indian%20mathematician%20%5B%5BSrinivasa%20Ramanujan%5D%5D%20in%20hospital.%20He%20related%20their%20conversation%3A%3Cref%3E%5Bhttp%3A%2F%2Fwww-gap.dcs.st-and.ac.uk%2F~history%2FQuotations%2FHardy.html%20Quotations%20by%20Hardy%3C!--%20Bot%20generated%20title%20--%3E%5D%20%7B%7Bwebarchive%7Curl%3Dhttps%3A%2F%2Fweb.archive.org%2Fweb%2F20120716185939%2Fhttp%3A%2F%2Fwww-gap.dcs.st-and.ac.uk%2F~history%2FQuotations%2FHardy.html%20%7Cdate%3D2012-07-16%20%7D%7D%3C%2Fref%3E%3Cref%20name%3D%22BBC-Futurama%22%3E%7B%7Bcite%20news%7Curl%3Dhttps%3A%2F%2Fwww.bbc.co.uk%2Fnews%2Fmagazine-24459279%7Ctitle%3DWhy%20is%20the%20number%201%2C729%20hidden%20in%20Futurama%20episodes%3F%7Cwork%3DBBC%20News%20Online%7Cfirst%3DSimon%7Clast%3DSingh%7Cauthorlink%3DSimon%20Singh%7Cdate%3D15%20October%202013%7Caccessdate%3D15%20October%202013%7D%7D%3C%2Fref%3E%3Cref%3E%7B%7Bcite%20book%20%7Ctitle%3DRamanujan%20%7Curl%3Dhttps%3A%2F%2Farchive.org%2Fdetails%2Fpli.kerala.rare.37877%20%7Clast%3DHardy%20%7Cfirst%3DG%20H%20%7Clocation%3DNew%20York%20%7Cpublisher%3DCambridge%20University%20Press%20(original)%20%7Cyear%3D1940%20%7Cpage%3D%5Bhttps%3A%2F%2Farchive.org%2Fdetails%2Fpli.kerala.rare.37877%2Fpage%2Fn17%2012%5D%7D%7D%3C%2Fref%3E%3Cref%3E%7B%7Bcitation%7Cfirst%3DG.%20H.%7Clast%3DHardy%0A%7Ctitle%3DSrinivasa%20Ramanujan%0A%7Cjournal%3DProc.%20London%20Math.%20Soc.%20%7Cyear%3D1921%7Cvolume%3D%20s2-19%20%7Cissue%3D1%7Cpages%3Dxl%E2%80%93lviii%7Cdoi%3D10.1112%2Fplms%2Fs2-19.1.1-u%7Curl%3Dhttps%3A%2F%2Fzenodo.org%2Frecord%2F1447788%0A%7D%7D%20The%20anecdote%20about%201729%20occurs%20on%20pages%20lvii%20and%20lviii%3C%2Fref%3E%0A%7B%7Bquote%7CI%20remember%20once%20going%20to%20see%20him%20when%20he%20was%20ill%20at%20Putney.%20I%20had%20ridden%20in%20taxi%20cab%20number%201729%20and%20remarked%20that%20the%20number%20seemed%20to%20me%20rather%20a%20dull%20one%2C%20and%20that%20I%20hoped%20it%20was%20not%20an%20unfavourable%20omen.%20%22No%2C%22%20he%20replied%2C%20%22it%20is%20a%20very%20interesting%20number%3B%20it%20is%20the%20smallest%20number%20expressible%20as%20the%20sum%20of%20two%20cubes%20in%20two%20different%20ways.%22%7D%7D%0A%0AThe%20two%20different%20ways%20are%3A%0A%0A%3A%201729%20%3D%201%3Csup%3E3%3C%2Fsup%3E%20%2B%2012%3Csup%3E3%3C%2Fsup%3E%20%3D%209%3Csup%3E3%3C%2Fsup%3E%20%2B%2010%3Csup%3E3%3C%2Fsup%3E%0A%0AThe%20quotation%20is%20sometimes%20expressed%20using%20the%20term%20%22positive%20cubes%22%2C%20since%20allowing%20negative%20perfect%20cubes%20(the%20cube%20of%20a%20%5B%5Bnegative%20number%7Cnegative%5D%5D%20%5B%5Binteger%5D%5D)%20gives%20the%20smallest%20solution%20as%20%5B%5B91%20(number)%7C91%5D%5D%20(which%20is%20a%20%5B%5Bdivisor%5D%5D%20of%201729)%3A%0A%0A%3A91%20%3D%206%3Csup%3E3%3C%2Fsup%3E%20%2B%20(%E2%88%925)%3Csup%3E3%3C%2Fsup%3E%20%3D%204%3Csup%3E3%3C%2Fsup%3E%20%2B%203%3Csup%3E3%3C%2Fsup%3E%0A%0ANumbers%20that%20are%20the%20smallest%20number%20that%20can%20be%20expressed%20as%20the%20sum%20of%20two%20cubes%20in%20%27%27n%27%27%20distinct%20ways%3Cref%3E%7B%7Bcite%20book%20%7Ctitle%3DNumber%20Story%3A%20From%20Counting%20to%20Cryptography%20%7Clast%3DHiggins%20%7Cfirst%3DPeter%20%7Cyear%3D2008%20%7Cpublisher%3DCopernicus%20%7Clocation%3DNew%20York%20%7Cisbn%3D978-1-84800-000-1%20%7Cpage%3D13%20%7D%7D%3C%2Fref%3E%20have%20been%20dubbed%20%22%5B%5Btaxicab%20number%5D%5Ds%22.%20The%20number%20was%20also%20found%20in%20one%20of%20Ramanujan%27s%20notebooks%20dated%20years%20before%20the%20incident%2C%20and%20was%20noted%20by%20%5B%5BFr%C3%A9nicle%20de%20Bessy%5D%5D%20in%201657.%20%20A%20commemorative%20plaque%20now%20appears%20at%20the%20site%20of%20the%20Hardy%E2%80%93Ramanujan%20incident%2C%20at%202%20Colinette%20Road%20in%20%5B%5BPutney%5D%5D.%3Cref%3E%7B%7Bcite%20web%20%7Clast1%3DMarshall%20%7Cfirst1%3DMichael%20%7Ctitle%3DA%20black%20plaque%20for%20Ramanujan%2C%20Hardy%20and%201%2C729%20%7Curl%3Dhttps%3A%2F%2Fgoodthinkingsociety.org%2Fa-black-plaque-for-ramanujan-hardy-and-1729%2F%20%7Cwebsite%3DGood%20Thinking%20%7Caccessdate%3D7%20March%202019%7D%7D%3C%2Fref%3E%0A%0AThe%20same%20expression%20defines%201729%20as%20the%20first%20in%20the%20sequence%20of%20%22Fermat%20near%20misses%22%20%7B%7BOEIS%7Cid%3DA050794%7D%7D%20defined%2C%20in%20reference%20to%20%5B%5BFermat%27s%20Last%20Theorem%5D%5D%2C%20as%20numbers%20of%20the%20form%201%26nbsp%3B%2B%26nbsp%3B%27%27z%27%27%3Csup%3E3%3C%2Fsup%3E%20which%20are%20also%20expressible%20as%20the%20sum%20of%20two%20other%20cubes.%0A%0A%3D%3DOther%20properties%3D%3D%0A1729%20is%20also%20the%20third%20%5B%5BCarmichael%20number%5D%5D%2C%20the%20first%20Chernick%E2%80%93Carmichael%20number%20%7B%7BOEIS%7CA033502%7D%7D%2C%20and%20the%20first%20absolute%20%5B%5BEuler%20pseudoprime%5D%5D.%20%20It%20is%20also%20a%20%5B%5Bsphenic%20number%5D%5D.%0A%0A1729%20is%20a%20%5B%5BZeisel%20number%5D%5D.%3Cref%3E%7B%7BCite%20OEIS%7C1%3DA051015%7C2%3DZeisel%20numbers%7Caccessdate%3D2016-06-02%7D%7D%3C%2Fref%3E%20It%20is%20a%20%5B%5Bcentered%20cube%20number%5D%5D%2C%3Cref%3E%7B%7BCite%20OEIS%7C1%3DA005898%7C2%3DCentered%20cube%20numbers%7Caccessdate%3D2016-06-02%7D%7D%3C%2Fref%3E%20as%20well%20as%20a%20%5B%5Bdodecagonal%20number%5D%5D%2C%3Cref%3E%7B%7BCite%20OEIS%7C1%3DA051624%7C2%3D12-gonal%20(or%20dodecagonal)%20numbers%7Caccessdate%3D2016-06-02%7D%7D%3C%2Fref%3E%20a%2024-%5B%5Bpolygonal%20number%7Cgonal%5D%5D%3Cref%3E%7B%7BCite%20OEIS%7C1%3DA051876%7C2%3D24-gonal%20numbers%7Caccessdate%3D2016-06-02%7D%7D%3C%2Fref%3E%20and%2084-gonal%20number.%0A%0AInvestigating%20pairs%20of%20distinct%20integer-valued%20%5B%5Bquadratic%20form%5D%5Ds%20that%20represent%20every%20integer%20the%20same%20number%20of%20times%2C%20Schiemann%20found%20that%20such%20quadratic%20forms%20must%20be%20in%20four%20or%20more%20variables%2C%20and%20the%20least%20possible%20%5B%5Bdiscriminant%5D%5D%20of%20a%20four-variable%20pair%20is%201729%20%7B%7BHarv%7CGuy%7C2004%7D%7D.%0A%0ABecause%20in%20base%2010%20the%20number%201729%20is%20divisible%20by%20the%20sum%20of%20its%20digits%2C%20it%20is%20a%20%5B%5BHarshad%20number%5D%5D.%20It%20also%20has%20this%20property%20in%20%5B%5Boctal%5D%5D%20(1729%26nbsp%3B%3D%26nbsp%3B3301%3Csub%3E8%3C%2Fsub%3E%2C%203%26nbsp%3B%2B%26nbsp%3B3%26nbsp%3B%2B%26nbsp%3B0%26nbsp%3B%2B%26nbsp%3B1%26nbsp%3B%3D%26nbsp%3B7)%20and%20%5B%5Bhexadecimal%5D%5D%20(1729%26nbsp%3B%3D%26nbsp%3B6C1%3Csub%3E16%3C%2Fsub%3E%2C%206%26nbsp%3B%2B%26nbsp%3BC%26nbsp%3B%2B%26nbsp%3B1%26nbsp%3B%3D%26nbsp%3B19%3Csub%3E10%3C%2Fsub%3E)%2C%20but%20not%20in%20%5B%5Bbinary%20numeral%20system%7Cbinary%5D%5D%20and%20%5B%5Bduodecimal%5D%5D.%0A%0AIn%20%5B%5Bduodecimal%7Cbase%2012%5D%5D%2C%201729%20is%20written%20as%20%5B%5B1001%20(number)%7C1001%5D%5D%2C%20so%20its%20reciprocal%20has%20only%20%5B%5Bperiod%20length%7Cperiod%5D%5D%206%20in%20that%20base.%0A%0A1729%20is%20the%20lowest%20number%20which%20can%20be%20represented%20by%20a%20%5B%5BLoeschian%20number%7CLoeschian%5D%5D%20quadratic%20form%20%27%27a%C2%B2%20%2B%20ab%20%2B%20b%C2%B2%27%27%20in%20four%20different%20ways%20with%20%27%27a%27%27%20and%20%27%27b%27%27%20positive%20integers.%20The%20integer%20pairs%20(%27%27a%27%27%2C%27%27b%27%27)%20are%20(25%2C23)%2C%20(32%2C15)%2C%20(37%2C8)%20and%20(40%2C3).%3Cref%3E%7B%7Bcite%20web%7Curl%3Dhttps%3A%2F%2Flatticelabyrinths.wordpress.com%2F2017%2F02%2F25%2Ftessellating-the-hardy-ramanujan-taxicab-number-1729-bedrock-of-integer-sequence-a198775%2F%7Ctitle%3DTessellating%20the%20Hardy-Ramanujan%20Taxicab%20Number%2C%201729%2C%20Bedrock%20of%20Integer%20Sequence%20A198775%7Caccess-date%3D19%20July%202018%7Cdate%3D25%20February%202017%7Cauthor%3DDavid%20Mitchell%7D%7D%3C%2Fref%3E%3C!--%20not%20any%20of%20the%20famous%20David%20Mitchells%20--%3E%0A%0A1729%20has%20another%20mildly%20interesting%20property%3A%20the%201729th%20digit%20is%20the%20beginning%20of%20the%20first%20consecutive%20occurrence%20of%20all%20ten%20digits%20without%20repetition%20in%20the%20decimal%20representation%20of%20the%20%5B%5Btranscendental%20number%5D%5D%20%5B%5Be%20(mathematical%20constant)%7C%27%27e%27%27%5D%5D.%3Cref%3E%5Bhttp%3A%2F%2Fwww.mathpages.com%2Fhome%2Fkmath028%2Fkmath028.htm%20The%20Dullness%20of%201729%3C!--%20Bot%20generated%20title%20--%3E%5D%3C%2Fref%3E%0A%0A%5B%5BMasahiko%20Fujiwara%5D%5D%20showed%20that%201729%20is%20one%20of%20four%20positive%20integers%20(with%20the%20others%20being%20%5B%5B81%20(number)%7C81%5D%5D%2C%20%5B%5B1458%20(number)%7C1458%5D%5D%2C%20and%20the%20trivial%20case%20%5B%5B1%20(number)%7C1%5D%5D)%20which%2C%20when%20its%20digits%20are%20added%20together%2C%20produces%20a%20sum%20which%2C%20when%20multiplied%20by%20its%20reversal%2C%20yields%20the%20original%20number%3A%0A%0A%3A%201%20%2B%207%20%2B%202%20%2B%209%20%3D%2019%0A%3A%2019%20%C3%97%2091%20%3D%201729%0A%0AIt%20suffices%20only%20to%20check%20sums%20congruent%20to%200%20or%201%20(mod%209)%20up%20to%2019.%0A%0A%3D%3DSee%20also%3D%3D%0A*%20%27%27%5B%5BA%20Disappearing%20Number%5D%5D%27%27%2C%20a%202007%20play%20about%20Ramanujan%20in%20England%20during%20World%20War%20I.%0A*%20%5B%5BBerry%20paradox%5D%5D%0A*%20%5B%5BInteresting%20number%20paradox%5D%5D%0A*%20%5B%5BTaxicab%20number%5D%5D%0A*%20%5B%5B4104%20(number)%7C4104%5D%5D%2C%20the%20second%20positive%20integer%20which%20can%20be%20expressed%20as%20the%20sum%20of%20two%20positive%20cubes%20in%20two%20different%20ways.%0A%0A%3D%3DReferences%3D%3D%0A*%7B%7BCitation%7Clast%3DGardner%7Cfirst%3DMartin%7Cauthor-link%3DMartin%20Gardner%7Cyear%3D1973%7Ctitle%3DMathematical%20Puzzles%20and%20Diversions%7Cpublisher%3DPelican%20%2F%20Penguin%20Books%7Cedition%3DPaperback%7Cisbn%3D0-14-020713-9%7D%7D%0A*%7B%7BCitation%7Clast%3DGuy%7Cfirst%3DRichard%20K.%7Cauthor-link%3DRichard%20K.%20Guy%7Cyear%3D2004%7Ctitle%3DUnsolved%20Problems%20in%20Number%20Theory%7Cpublisher%3DSpringer%7Cedition%3D3rd%7Cseries%3DProblem%20Books%20in%20Mathematics%2C%20Volume%201%7Cisbn%3D0-387-20860-7%7Curl%3Dhttps%3A%2F%2Fwww.springer.com%2Fmathematics%2Fnumbers%2Fbook%2F978-0-387-20860-2%7D%7D%20-%20D1%20mentions%20the%20Hardy%E2%80%93Ramanujan%20number.%0A%0A%3D%3DNotes%3D%3D%0A%7B%7Breflist%7D%7D%0A%0A%3D%3DExternal%20links%3D%3D%0A*%20%5Bhttp%3A%2F%2Fmathworld.wolfram.com%2FHardy-RamanujanNumber.html%20MathWorld%3A%20Hardy%E2%80%93Ramanujan%20Number%5D%0A*%20%5Bhttp%3A%2F%2Fwww.bbc.co.uk%2Fradio4%2Fscience%2Ffurther5.shtml%3Frhppromo%20BBC%3A%20A%20Further%20Five%20Numbers%5D%0A*%20%7B%7Bcite%20web%7Clast%3DGrime%7Cfirst%3DJames%7Ctitle%3D1729%3A%20Taxi%20Cab%20Number%20or%20Hardy-Ramanujan%20Number%7Curl%3Dhttp%3A%2F%2Fwww.numberphile.com%2Fvideos%2F1729taxicab.html%7Cwork%3DNumberphile%7Cpublisher%3D%5B%5BBrady%20Haran%5D%5D%7Cauthor2%3DBowley%2C%20Roger%7Caccess-date%3D2013-04-02%7Carchive-url%3Dhttps%3A%2F%2Fweb.archive.org%2Fweb%2F20170306141337%2Fhttp%3A%2F%2Fnumberphile.com%2Fvideos%2F1729taxicab.html%7Carchive-date%3D2017-03-06%7Curl-status%3Ddead%7D%7D%0A*%20%5Bhttp%3A%2F%2Fio9.com%2Fwhy-does-the-number-1729-show-up-in-so-many-futurama-ep-1445512975%20Why%20does%20the%20number%201729%20show%20up%20in%20so%20many%20Futurama%20episodes%3F%5D%2C%20io9.com%0A%0A%5B%5BCategory%3AIntegers%5D%5D%0A%5B%5BCategory%3ASrinivasa%20Ramanujan%5D%5D%0A&options=&version=master) and then live edit.

Satisfying to see the "disappearing one item indent" confirmed by adding another indented item :-)

There is a "wtf object" view now using [NeatJSON](http://phrogz.net/js/neatjson/neatjson.html), but not yet able to get all the values out of the wtf object structure. Getting all the object data into string form is not so easy it seems. Tips or ideas for fixing this appreciated. 

More ideas: 
  * Allow for wikimedia-project URL input (and extract the language, title, etc.)
  * Would be nice I think if we could link to the latest wtf_wikipedia files (including the plugins) from some CDN, so these files only need to be updated in one place for each new release. Any thoughts on this?

**Comment by spencermountain** [comment]
neat stuff -  you can use unpkg as a cdn, like this
`https://unpkg.com/wtf-plugin-person`
that will import the latest release each time
cheers
