### ISSUE TITLE
support for some html tags

### ISSUE THREAD

**Issue by waldenn** [spencermountain/wtf_wikipedia#374]
Some often used HTML elements like: super, sub, strong, em are not preserved in the HTML output: [example](https://conze.pt/app/wtf-debug/?text=ATP%20%2B%20H%3Csub%3E2%3C%2Fsub%3EO%20%2B%203H%3Csup%3E%2B%3C%2Fsup%3E%0A%0A%3Cstrong%3Ebold%3F%3C%2Fstrong%3E%0A%0A%3Cem%3Ebold%3F%3C%2Fem%3E%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

See also: [wiki page on allowed HTML elements](https://en.wikipedia.org/wiki/Help:HTML_in_wikitext)

Especially "sub" and "sup" are often seen in the chemical formulas and other science articles: [example](https://en.wikipedia.org/w/index.php?title=ATP_synthase&action=edit).

Are all HTML-tags currently removed from wtf_wikipedia? Any idea how to best preserve the most useful in the HTML output? Eg. pre-processing and substituting the start/end HTML-tags with start/end templates? I think supporting at least the above HTML-elements would be nice.

**Comment by spencermountain** [comment]
yeah, I see what you mean - one solution could be to turn these into templates, or some kind of json response, just like we do for bold and italics.
given that almost-full css is supported, we'll never get it all - but I agree sub and sup, and others would be good to support.

**Comment by waldenn** [comment]
Ok, thanks. I will check the bold and italics code and submit a PR.

**Comment by waldenn** [comment]
I am wondering how to simply replace a start or end HTML tag using the wtf_wikipedia template system.

I added the following lines to "wtf_wikipedia/src/01-document/preProcess/index.js" 
(and then added the parsers for those templates in "wtf_wikipedia/src/template/templates/wikipedia/page.js"):

```js

  // <strong> html formatting
  wiki = wiki.replace(/<strong>/g, "'''")
  wiki = wiki.replace(/<\/strong>/g, "'''")

  // <em> html formatting
  wiki = wiki.replace(/<em>/g, "'''")
  wiki = wiki.replace(/<\/em>/g, "'''")

  // <sub> html formatting
  wiki = wiki.replace(/<sub>/g, "{{sub-start}}")
  wiki = wiki.replace(/<\/sub>/g, "{{sub-end}}")

  // <super> html formatting
  wiki = wiki.replace(/<super>/g, "{{sup-start}}")
  wiki = wiki.replace(/<\/super>/g, "{{sup-end}}")
```

For the math-tags I am currently adding a unique string around the start end end tag, which then gets replaced in my project code to a span-element with some class, which then gets rendered by the math-rendering JS library. The string position is important here.

What is the best way to simply replace these start and end templates directly with a corresponding HTML tag, while keeping the position within a sentence?

**Comment by spencermountain** [comment]
yep, i like that approach. Good idea.
Really neat work with conzept
Pr welcome!

**Comment by spencermountain** [comment]
sorry -  to answer your question, I don't think we have a way to preserve the string position at that point in the parser.
[here](https://github.com/spencermountain/wtf_wikipedia/blob/master/src/01-document/preProcess/index.js) (as you prob know) is where we simply throw the html away, which is very early in the process.
If we swap those with more-standard formatting, it should work as expected.
...MAYBE... 😉

**Comment by waldenn** [comment]
Ok, thanks. I'll have a further look into this. I am starting feel that some kind of 'standard hack' for ***simple*** positional replacements might be nice to have in the library (until we have some more sophisticated perhaps, but maybe this is not even needed when we have such a hack).

Thanks for the praise Spencer. Much appreciated!

**Comment by spencermountain** [comment]
b, i, sub, and sup tags are now supported in 8.4.0.
b and i are found in Sentence.formatting and sub and sup are found in .templates()

cheers

**Comment by waldenn** [comment]
The sup/sub elements are still not transformed in-place right?

**Comment by spencermountain** [comment]
yep. i suppose the html plugin etc should transform them
