### ISSUE TITLE
Interwiki link edge cases

### ISSUE THREAD

**Issue by shreyasminocha** [spencermountain/wtf_wikipedia#378]
```js
wtf('[[Wiktionary:fr:bonjour]]')
	.links().map((link) => link.json())
```

This is, of course, valid [wikitext syntax](https://en.wikipedia.org/wiki/Help:Wikitext#Interwiki_link) *sigh*.

![Linking to a page on another wiki in another language. All of these forms lead to the URL http://fr.wiktionary.org/wiki/bonjour. Simple link: `[[Wiktionary:fr:bonjour]]`, Without prefix: `[[Wiktionary:fr:bonjour|]]`, Named link: `[[Wiktionary:fr:bonjour|bonjour]]`](https://user-images.githubusercontent.com/11537232/89725321-d2836080-d9fd-11ea-96c7-5645470709fd.jpg)

### Actual

```js
[
  { text: undefined, type: 'internal', page: 'Wiktionary:fr:bonjour' }
]
```

### Expected

```js
[
  {
    text: 'hello',
    type: 'interwiki',
    wiki: { wiki: 'wiktionary' lang: 'fr' }, // I think this will work as a parameter for `wtf.fetch`
    anchor: 'anchor'
  }
]
```

To make matters worse, `[[s:de:Hauptseite]]`, ~~`[:en:n:Main page]]` (???)~~— who came up with this :poop:?!

And of course, `[[Wiktionary:fr:bonjour#anchor]]`, `[[Wiktionary:fr:bonjour|text]]`, `[[Wiktionary:fr:bonjour#anchor|]]` etc too.

I'll be happy to work on a PR. I think `parseInterwiki` in `src/link/interwiki.js` will need edits?

**Comment by spencermountain** [comment]
whoa! thank you Shreyas - I didn't know about this one.

yes, you're right. adding another regex to [/src/link/parse.js](https://github.com/spencermountain/wtf_wikipedia/blob/master/src/link/parse.js)  or `parseInterwiki` should do the job!
happy to help. i've got a busy week, but can do a release this week for this, if it helps.
cheers!
