### ISSUE TITLE
403 Forbidden on NodeJS

### ISSUE THREAD

**Issue by risingjason** [spencermountain/wtf_wikipedia#384]
Hi, I am trying to run a simple fetch to `https://oldschool.runescape.wiki/w/Abyssal_whip` with this code.

```js
  let page = await wtf.fetch('Abyssal whip', {
    domain: 'oldschool.runescape.wiki',
  });
  console.log(page);
```

After running the script, I would run into an error like this. 

```js
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/mnt/c/Users/Jason/Desktop/develop/clue-scroll-solver/backend/node_modules/wtf_wikipedia/builds/wtf_wikipedia.js:8720:29)
```

After investigating the file the stack trace refers to, I was able to find out that when trying to
fetch from `https://oldschool.runescape.com` I would receive the below response.

```html
<html>
<head><script async src="https://www.googletagmanager.com/gtag/js?id=UA-126479006-1"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag("js",new Date());gtag("config","UA-126479006-1");</script><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

I've changed my user agent a few times to see if that would be the culprit, with no success.

With all that being said, the exact same code would work on the browser.

**Comment by risingjason** [comment]
After some investigation, a member of the OldSchool Runescape Wiki Discord channel explained that the website's Origin header needs to not be `*`.

Here's an example of the header sent that would normally cause a 403.
```json
{
  method: 'GET',
  headers: {
    'Content-Type': 'application/json',
    'Api-User-Agent': 'i am testing this functionality',
    'User-Agent': 'i am testing this functionality',
    Origin: '*'
  },
  redirect: 'follow'
}
```

After manually editing `build/wtf_wikipedia.js` and changing Origin to `https://oldschool.runescape.wiki`, the request was able
to return successfully. Also, removing Origin from headers allowed it to work.

```json
{
  method: 'GET',
  headers: {
    'Content-Type': 'application/json',
    'Api-User-Agent': 'i am testing this functionality',
    'User-Agent': 'i am testing this functionality',
    Origin: 'https://oldschool.runescape.wiki'
  },
  redirect: 'follow'
}
```

**Comment by spencermountain** [comment]
hey! that's amazing.
Thank you for doing this.
(and thank the runescape people too!)
