### ISSUE TITLE
reformat sections as ordered array

### ISSUE THREAD

**Issue by spencermountain** [spencermountain/wtf_wikipedia#39]
right now article headings are being organized as an object, but 
[it appears](https://runkit.com/573ce319691f641100ad9989/57d87261d21b671400de1798) we're loosing their ordering this way.
Given this is important, it probably oughta be rendered as an array.
¯_(ツ)_/¯

**Comment by atralice** [comment]
Hi, Spencer.
I changed the output object to be a [Map()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) which maintains the order of the properties. 

All the tests are passing. I built the demo page and it also works good.

**Comment by spencermountain** [comment]
fancy! :heart_eyes: 
thanks Toni, happy to merge 'er

**Comment by atralice** [comment]
One concern is about compatibility, because now wtf.parse(...).text  is now a Map().
wtf.plaintext is still returning a String.

**Comment by spencermountain** [comment]
yeah, I'm not hot on using the Map() either tbh. 
i wanna support IE9, and who knows what babel does with it..
Let's turn it into an array again, in the next release.

**Comment by spencermountain** [comment]
hey, this is an array of objects now, with depth information and stuff.
`v1.0.0` :rocket:
