### ISSUE TITLE
doc.infobox().json() response contains incomplete/inconsistent property values

### ISSUE THREAD

**Issue by malcolmcameron** [spencermountain/wtf_wikipedia#390]
Example:
url: https://en.wikipedia.org/wiki/LVMH
`traded as` within `infobox` on page:

<img width="290" alt="Screen Shot 2020-09-18 at 1 22 52 PM" src="https://user-images.githubusercontent.com/64438899/93626873-1335a880-f9b2-11ea-889e-57f2198b701c.png">

```
wtf_wikipedia response:
wtf.fetch("LVMH").then((doc) => {
  console.log(doc.infobox().json());
})
```

<img width="270" alt="Screen Shot 2020-09-18 at 1 25 50 PM" src="https://user-images.githubusercontent.com/64438899/93627149-7f181100-f9b2-11ea-8677-26eb449e2f1b.png">

the response is missing some data (Euronext Paris: MC).

 Noticed this in several other infobox responses.

**Comment by spencermountain** [comment]
merging this one with #391
