### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by wvanderp** [spencermountain/wtf_wikipedia#394]
Another day, another message.

Today I looked at fixing the code coverage. And I have questions and a plan.

Questions first:
- What is currently broken about the coverage?
- Are you still happy with codecov? If yes we will continue using it. If not then what do you want to use instat?
- Will you be including the coverage in the pull request process
- What tests will count against the coverage?
- Are there any other big changes you want to make? Like switching frameworks or reporting style 

And now my answers:
- Hard to say al little to a lot
  - They are not run automatically
  - They don't cover all test
  - They don't use the new test script 
- Looks like nothing wrong with it
- Perhaps
- I'm thinking that the main tests count and that the plugins are mabey counted separately.
- I don't think so. 

And then lastly my plan:
- Update the coverage shelljs script.
- Add a github action for calculating coverage
- Maybe adding coverage to the pull request process
- And then in the future upping the coverage

I'm curious what you are thinking

-wvanderp

**Comment by spencermountain** [comment]
hey wouter, thanks for checking.
A github action sounds like a great idea, and any service you choose should be good. I don't remember what happened with codecov.

Right now there's a github action that runs each time it gets merged to master. That would work. I think `test` and `test:fetch` should probably both run.

sounds good to me!
