### ISSUE TITLE
Calling plaintext on a redirect causes error

### ISSUE THREAD

**Issue by robertkeizer** [spencermountain/wtf_wikipedia#4]
[L538](https://github.com/spencermountain/wtf_wikipedia/blob/755384b3c3b9aef705fa674e58b9ceb0251ff424/index.js#L538) makes use of `data.text`; This doesn't exist in certain cases as [this redirect clause](https://github.com/spencermountain/wtf_wikipedia/blob/755384b3c3b9aef705fa674e58b9ceb0251ff424/index.js#L410) exists in `main`.

I've gotten around this by adding more logic in my code that utilizes `wikipedia.parse` and checks if `.text` exists.

**Comment by spencermountain** [comment]
fixed in 0.1.3. thanks man!
