### ISSUE TITLE
Clarify which Parsoid GPL code is used

### ISSUE THREAD

**Issue by legoktm** [spencermountain/wtf_wikipedia#407]
Hi,
In the README it says:
> This library has (lovingly) borrowed a lot of code and data from the parsoid project, and is gracious to those contributors.

Parsoid is [licensed](https://gerrit.wikimedia.org/g/mediawiki/services/parsoid/) under the GPL v2 (or at your option, any later version) license, while this library is released under MIT. I haven't actually looked at what code has been copied, but whatever has been "borrowed" from Parsoid needs to retain the GPL license, not MIT.

**Comment by spencermountain** [comment]
hey Kunal, thank you.
Let me try and pull-up some old commits. I've never understood software licencing very well.
If you saw that hnews post, please know I'm a huge fan of your work, and the WMF in general. I remember your 'Why am I still here?' post, a few years back. Thank you for your work!

**Comment by matkoniecz** [comment]
> The MIT license is compatible with many copyleft licenses, such as the GNU General Public License (GPL); MIT licensed software can be re-licensed as GPL software, and integrated with other GPL software, but not the other way around

https://en.wikipedia.org/wiki/MIT_License


> but whatever has been "borrowed" from Parsoid needs to retain the GPL license, not MIT.

My understanding is that if GPL code was used than entire project code becomes GPL.

You cannot take GPL code and legally incorporate it into MIT code (though you can take MIT code and incorporate it into GPL code).

https://en.wikipedia.org/wiki/GNU_General_Public_License#Compatibility_and_multi-licensing

**Comment by matkoniecz** [comment]
And as GPL (not LGPL) was used it means that all program written with wtf_wikipedia are also GPL ( https://en.wikipedia.org/wiki/Viral_license )

**Comment by matkoniecz** [comment]
As I understand it you have two options: 

(1) remove all Parsoid code, and all code derived from Parsoid code, write this from scratch without using Parsoid code as a base

(2) relicense `wtf_wikipedia` as GPL v2 or later and try to notify all library users that it applies also to old versions and that their program are also GPLv2 or later.

(3) ignore problem, but that that means that your code is in violation of copyright law and breaks Parsoid license.

(4) convince Parsoid to relicense to MIT or MIT-compatible license

**Comment by einSelbst** [comment]
Hey @spencermountain ,
I'm thinking about creating a bubble plugin based on your library and for this reason would like to know if there is still "borrowed parsoid code" in this project?
Thank you for this awesome library!

**Comment by spencermountain** [comment]
Hey @einSelbst yup - I can confirm there is no parsoid code, thanks for double-checking.
Cheers
