### ISSUE TITLE
wtf_wikipedia removes () that are usefull

### ISSUE THREAD

**Issue by zatteo** [spencermountain/wtf_wikipedia#41]
Hi, I'm back with an other issue :D

I use your API with this page :  https://fr.wikipedia.org/wiki/J%C3%A9r%C3%B4me_Cahuzac

but the infobox.image.text is wrong after the parsing. It is `{ text: 'Jérôme Cahuzac cropped.jpg', links: undefined }` whereas it should be  `Jérôme Cahuzac (2012) cropped.jpg` according to the markup.

After some investigations, I think that the reason is this line `line = line.replace(/\([^a-z]{0,8}\)/, "");
` (/src/parse/parse_line.js:38) but I don't know if this line is important (can I remove it ?).

Thanks a lot and have a nice day !

**Comment by spencermountain** [comment]
hey Théo, good find. I think that line was a left-over from a personal project. Wanna remove it? I'd be happy to aswell.

**Comment by spencermountain** [comment]
hey, this is working now, as of `v8.3.0`
cheers!
