### ISSUE TITLE
How to set Accept-Encoding: gzip

### ISSUE THREAD

**Issue by Vacilando** [spencermountain/wtf_wikipedia#412]
https://www.mediawiki.org/wiki/API:Etiquette#Request_limit recommends to set Accept-Encoding: gzip

Is there a way to do it using wtf.fetch()?
Can the third parameter - an object containing e.g. Api-User-Agent (cf https://github.com/spencermountain/wtf_wikipedia#good-practice) contain also Accept-Encoding: gzip?

**Comment by spencermountain** [comment]
hi Tomáš - yes of course. This is a good idea. 
I need to clean-up this http interface a bit, and am not good at this stuff - Let me merge this into #410 
any help here is appreciated.
