### ISSUE TITLE
How to retrieve an extract from a Wikipedia page

### ISSUE THREAD

**Issue by Vacilando** [spencermountain/wtf_wikipedia#413]
summary() for https://en.wikipedia.org/wiki/Richard_Feynman retrieves just

> American theoretical physicist (1918-1988)

How to get a full extract (intro) of an article the way Google and others are doing it? (cf https://stackoverflow.com/questions/8555320/is-there-a-wikipedia-api-just-for-retrieve-content-summary/28401782#28401782 -> https://en.wikipedia.org/w/api.php?format=json&action=query&prop=extracts&exintro&explaintext&redirects=1&titles=Richard%20Feynman)

**Comment by spencermountain** [comment]
hey Tomáš
```js
wtf.fetch('Richard_Feynman').then((doc) => {
  console.log(doc.sections(0)[0].text())
})
```
cheers

**Comment by Vacilando** [comment]
@spencermountain it looks promising but for

`doc.sections(0)[0].text()`

I get

> TypeError: Cannot read property 'text' of undefined

**Comment by spencermountain** [comment]
sorry bout that- 
```js
wtf.fetch('Richard_Feynman').then((doc) => {
  console.log(doc.sections(0).text())
})

```

**Comment by Vacilando** [comment]
Makes sense — and works! Thanks!
