### ISSUE TITLE
wtf-plugin-html includes images

### ISSUE THREAD

**Issue by Vacilando** [spencermountain/wtf_wikipedia#415]
When we fetch the extract of https://en.wikipedia.org/wiki/Cosmology as HTML

`doc.sections(0).html()`

there's also an image included. 

We would expect that a section only retrieves the text. 

What's the best action - filter the image out in wtf-plugin-html, or do that manually in each site?

**Comment by spencermountain** [comment]
yep - you can do `.html({ images: false })`
cheers

**Comment by Vacilando** [comment]
Excellent! Thanks.
