### ISSUE TITLE
V9: Provide json for custom templates

### ISSUE THREAD

**Issue by tomasz13nocon** [spencermountain/wtf_wikipedia#420]
Wouldn't it be a good idea to expose the internal template parser function through this object for example: https://github.com/spencermountain/wtf_wikipedia/blob/805d725abf4ec0574616356daea5e762f2dcf347/src/index.js#L13
, so that it's availible in `extend`? Currently the only way seems to be `import parse from "wtf_wikipedia/src/template/_parsers/parse"` which relies on the internal file structure.

Btw there doesn't seem to be comment functionality there so I'll mention it here. [This page](https://observablehq.com/@spencermountain/wtf-wikipedia-plugins) provides an example of parsing a custom template except in the example the "}}" is included in the output which doesn't seem intentional.

**Comment by spencermountain** [comment]
hey @tomasz13nocon yeah neat idea.
I'm curious, what's your motivation for replacing the whole template parser? You can add new templates with a plugin. If you were adding a cool new feature, I'd love to hear about it.

Your timing is good. I'm working on this right now - and the `./_parsers/parse` path will break in the upcoming version.
I'm on-board with supporting more parts of the lib getting swapped-out with plugin
Let me know
cheers

**Comment by tomasz13nocon** [comment]
I'm not sure I understand.

I'm working with a Fandom wiki so I need to add a bunch of different templates. I don't want to replace the parser, on the contrary I want to use the parser, that is in `src/template/_parsers/parse` instead of writing a new one. My understanding is that adding templates is done with the `extend` function, but there doesn't seem to be a way to use that parser since it isn't exposed to the outside.

**Comment by spencermountain** [comment]
ahh - haha, this is infact the thing I was working on yesterday!

it's a big refactor, to swap the params for all the templates. I've been wanting to do it for ages.
but yes, in v9, you'll have parsed json data provided to the template functions. I think it will be the first parameter.

You could potentially use the dev branch, once it's ready. I'll give you a heads-up once this lands. 
cheers

**Comment by spencermountain** [comment]
hi, this is supported now:
```js
wtf.extend((models, templates) => {
  templates.foo = (tmpl, list, parse) => {
    let obj = parse(tmpl)
    list.push(obj)
    return 'new-text'
  }
 }
  ```
cheers
