### ISSUE TITLE
Parser silently ignores unsupported templates

### ISSUE THREAD

**Issue by tstibbs** [spencermountain/wtf_wikipedia#432]
E.g. if you run
```
wtf(`
{{unbullet|string 1|string 2}}
`).text()
```
it returns an empty string, because it doesn't know how to parse `unbullet`.

I don't expect it to be able to support every template out of the box, but some kind of warning that it's hit an unsupported template would be extremely useful. Perhaps a strict mode that errors in this case?

**Comment by spencermountain** [comment]
yeah, this was an older feature that was intentionally removed. 
Originally we hand-crafted every template, and then built a generic parser that does unknown ones pretty-well. So now it's rare that the library just bails on a template completely.

For some personal analytics, i put a logger [somewhere in here](https://github.com/spencermountain/wtf_wikipedia/blob/7f08539402dd9dd2a154a591932ba91b2decbdeb/src/template/parse/index.js#L64) although I admit the logic is a little complicated because they're recursive.
cheers

**Comment by tstibbs** [comment]
Would you be open to a PR that adds a strict mode which throws an error in the event that it does hit an unsupported template?

**Comment by spencermountain** [comment]
erm, I think the issue is that there's no clear way to decide if something is supported or unsupported.
I agree though, it would be nice to have more insight into templates that were missed.
You can see I once did [this](https://github.com/spencermountain/wtf_wikipedia/blob/master/src/01-document/Document.js#L51) so you could retrieve a list of templates we used a fallback rule for.

If you were to throw an error on every page that has a template not included in the custom templates list, I doubt any page would finish parsing right now.

**Comment by spencermountain** [comment]
curious - what's your use-case? are you writing new templates?
open to ideas, for improving this!

**Comment by tstibbs** [comment]
My use case is simply that I was trying to pull some info out of a page and found that some things were just completely missing, e.g. I was calling `infobox.keyValue()` but any entries in the infobox that used the `unbullet` template were missing (i.e. there wasn't even a key in the object returned from keyValue). Because there's no logging or anything like that, it look me quite a long time to work out that the problem was that unbullet wasn't supported (now fixed by my other PR). It's possible this is a rare case, I'm not sure.

My assumption was that if we ended up at [/src/template/parse/index.js#L64](https://github.com/spencermountain/wtf_wikipedia/blob/7f08539402dd9dd2a154a591932ba91b2decbdeb/src/template/parse/index.js#L64) then that meant we'd hit an unknown template though I admit I'm not completely clear exactly what data we're keeping or losing in that situation.

If you think this would lead to most pages being unparseable then a throw probably isn't helpful. Perhaps a log is still useful, if controlled by a config switch so you didn't have to suffer the log spam if you didn't want to.

**Comment by spencermountain** [comment]
yep - exactly. Pr welcomed, if you'd like to fish for a good solution.
cheers!

**Comment by spencermountain** [comment]
apologies in advance - the template parse logic is a real nest. Feel free to move things around as you see fit.

**Comment by tstibbs** [comment]
Not had a huge amount of time to look at this so have pushed my work in progress in case anyone wants to have a look: https://github.com/tstibbs/wtf_wikipedia/tree/feature/432-strict-template-mode

There are a few issues what I've done so far:
* 62 out of 71 articles in the cache folder have unrecognised templates, so based on that I suspect this feature is likely to break parsing of most things. It would only be any use for parsing small chunks of markup.
* Currently only works for `parseTemplate` calls that pass in a Document object - others don't but should perhaps still have the same behaviour.
* `wtf.fetch` will return null when the strict mode error kicks in (though will log it) but `wtf` directly (i.e. parsing a string template) will actually throw the error, which makes the two ways of parsing markup inconsistent. Changing this would be a fairly major change to the API (people will be checking for null being returned but not necessarily handling the error being thrown).
* The error message is a bit vague at the moment - I'm slightly unclear about the precise impact of a missing template (e.g. data seems to end up in the json model but not in the text returned).

**Comment by spencermountain** [comment]
Hey thanks, yeah the long-tail of these templates is really something. We're never gonna be able to manually address all of them, or a small % of them even.

Luckily they largely follow some standards. Maybe it would be helpful to log templates that are really long and look-like they have data, but return nothing? I don't know. But ya - I don't think throwing an error is gonna be much help. We're playing whackamole right now.

If you have any ideas, they are welcome.
Cheers

**Comment by ddevault** [comment]
Any reason not to fetch Template:Whatever and execute it normally?

**Comment by spencermountain** [comment]
hey @marcelogp i'd love to hear more about your suggestion.
We currently support [ad-hoc parsing using a plugin](https://github.com/spencermountain/wtf_wikipedia#adding-new-templates) - would your scheme be more flexible than that?
you can render text, or throw an error like that.
cheers

**Comment by marcelogp** [comment]
Yes, I'm already using this mechanism of adding custom template parsers but there are some limitations:

- You need to define the template name beforehand. This makes it hard to implement "generic" templates. For example, the French Wikipedia often uses many [ordinal templates](https://fr.wikipedia.org/w/index.php?title=Sp%C3%A9cial:Pages_li%C3%A9es/Mod%C3%A8le:Documentation_abr%C3%A9viation_ordinale_en_chiffres_arabes&namespace=10&hideredirs=1&hidelinks=1&limit=500) for each number from 1 to 1000 and other special cases. It's easier to write a single function that detects this situation given the template name.
- Adding a custom template mutates a private object inside `wtf` that can't be easily reset to its original state. For example, I need to process Wikipedia articles for different languages and I want to use a specific set of custom templates for each language.
- There's no way of rendering text for an "unknown" template. I'd like to have a fallback function when there's no template handler so I can dynamically decide whether to render some text and maybe log a warning.

My proposal is basically adding a check [right here](https://github.com/spencermountain/wtf_wikipedia/blob/7f08539402dd9dd2a154a591932ba91b2decbdeb/src/template/parse/index.js#L64) to call the fallback function (if set in the options object) and render the template text or just fallthrough. I would also keep the current mechanism for custom templates. Makes sense?
