### ISSUE TITLE
Unbulleted list template handling is inconsistent

### ISSUE THREAD

**Issue by tstibbs** [spencermountain/wtf_wikipedia#433]
Afaiks the templates `ubl`, `ublist` and `unbullet` should all be identical (if I'm reading https://en.wikipedia.org/wiki/Template:Unbulleted_list correctly). However, they're handled differently.

Test case:
```
import wtf from 'wtf_wikipedia'

wtf(`
{{ubl|a|b}}
{{ublist|c|d}}
{{unbullet|e|f}}
`).text()
```

Expected result (ignoring whitespace):
```
a b
c d
e f
```

Actual result:
```
a

b c|d
```

The inconsistency is that:
* `ubl` is handled correctly (it's aliased to `collapsible list`: [aliases.js#L55](https://github.com/spencermountain/wtf_wikipedia/blob/7f08539402dd9dd2a154a591932ba91b2decbdeb/src/template/custom/aliases.js#L55))
* `ublist` is handled incorrectly (aliased to `plainlist`: [aliases.js#L51](https://github.com/spencermountain/wtf_wikipedia/blob/7f08539402dd9dd2a154a591932ba91b2decbdeb/src/template/custom/aliases.js#L51))
* `unbullet` is just ignored.

The full list of unbulleted list templates would appear to be listed by looking at https://en.wikipedia.org/w/index.php?title=Special%3AWhatLinksHere&hidetrans=1&hidelinks=1&target=Template%3AUnbulleted+list&namespace= which would suggest that there's a whole load of others that are missing too. Given the results above I'm _assuming_ that these all need to be aliased to `collapsible list`? I'm happy to submit a PR doing that if that sounds like the right thing to do.

**Comment by spencermountain** [comment]
hey @tstibbs yeah I'd love some help. Prs welcomed.
a few ublist templates just [alias onto](https://github.com/spencermountain/wtf_wikipedia/blob/7f08539402dd9dd2a154a591932ba91b2decbdeb/src/template/custom/aliases.js#L51) [plainlist](https://github.com/spencermountain/wtf_wikipedia/blob/7f08539402dd9dd2a154a591932ba91b2decbdeb/builds/wtf_wikipedia.js#L4909) which is pretty basic and could use some improvements.

go nuts! 
as long as the tests still pass, I have no feelings on the matter.
cheers
