### ISSUE TITLE
Missing a disambiguation page of letter-number 

### ISSUE THREAD

**Issue by akav1sh** [spencermountain/wtf_wikipedia#439]
Hi @spencermountain, 
I'm using your great parser, found it after trying to parse wikitext by myself for college final project and it saved me!
I stumbled upon a missing DAB (doc.isDisambiguation() returns false for it) in this page and few more:
https://en.wikipedia.org/wiki/E400

{{Letter-NumberCombDisambig}}

Thanks!

**Comment by spencermountain** [comment]
oh hey! good find. I can add it to [our list](https://github.com/spencermountain/wtf_wikipedia/blob/master/src/_data/disambig_templates.js)
cheers!

**Comment by spencermountain** [comment]
this is added in 10.0.0
cheers
