### ISSUE TITLE
upgrade peer dependency in wtf-wikipedia-api

### ISSUE THREAD

**Issue by sandro-pasquali** [spencermountain/wtf_wikipedia#444]
Aloha!

Can you bump the peer dep on `wtf_wikipedia` to `9.0.1` and publish?: `https://github.com/spencermountain/wtf_wikipedia/blob/master/plugins/api/package.json`

Various build issues re: mismatch when using latest `wtf_wikipedia` and the `wtf-plugin-api`

**Comment by spencermountain** [comment]
hey Sandro, sure. The release is stuck behind a couple small things. Will try and do it today.
cheers

**Comment by spencermountain** [comment]
released as 9.0.2 - sorry for the delay
cheers
