### ISSUE TITLE
wtf-plugin-html dependency problem with wtf_wikipedia v9

### ISSUE THREAD

**Issue by Vacilando** [spencermountain/wtf_wikipedia#449]
When trying to use wtf_wikipedia we run into the following dependency problem with wtf-plugin-html (and perhaps other ones):

```
npm ERR! Found: wtf_wikipedia@9.0.3
npm ERR! node_modules/wtf_wikipedia
npm ERR!   wtf_wikipedia@"^9.*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer wtf_wikipedia@"^8.0.0" from wtf-plugin-html@0.2.3
npm ERR! node_modules/wtf-plugin-html
npm ERR!   wtf-plugin-html@"^0.*" from the root project
```

**Comment by spencermountain** [comment]
hey Tomáš, yeah you'll need to use version > 9.0 for that version of wtf-plugin-html
sorry for the tricky-business.

**Comment by Vacilando** [comment]
@spencermountain sounds definitely as the way to go, but how do I get wtf-plugin-html and wtf-plugin-summary that are compatible with wtf_wikipedia v9?

Up to now I fetches these from
- https://www.npmjs.com/package/wtf-plugin-summary
- https://www.npmjs.com/package/wtf-plugin-html
but the versions seems to be too low to support wtf_wikipedia v9.

**Comment by spencermountain** [comment]
hey @wvanderp - you have any feelings on this?

**Comment by wvanderp** [comment]
I don't see why we didn't update the peer dependencies. 

the test will run with the new build. this will give some guarantees that it will work. any problems will need to be found by other people.

**Comment by Vacilando** [comment]
So the current plugins should work with v9? Great!

Could you please update the peer dependencies in package.json in the plugins from `"wtf_wikipedia": "^8.0.0"` to `"wtf_wikipedia": "^9.0.0"`?
- https://github.com/spencermountain/wtf_wikipedia/blob/master/plugins/summary/package.json
- https://github.com/spencermountain/wtf_wikipedia/blob/master/plugins/html/package.json
- https://github.com/spencermountain/wtf_wikipedia/blob/master/plugins/image/package.json 
- ...

Because now when I try to install any of the plugins I am required to use v8 of wtf_wikipedia.

**Comment by spencermountain** [comment]
good catch - i've bumped all plugins to `>=9.0.0`
thanks
