### ISSUE TITLE
[wtf-plugin-summary] tmpl.json is not a function

### ISSUE THREAD

**Issue by Vacilando** [spencermountain/wtf_wikipedia#450]
When I use wtf-plugin-summary v0.3 from NPM with wtf_wikipedia v8 I get `tmpl.json is not a function`.

> ERROR
> 
> tmpl.json is not a function
> 
>   TypeError: tmpl.json is not a function
> 
>   - index.js:4 fromTemplate
>     [mysite]/[wtf-plugin-summary]/src/template/index.js:4:21
> 
>   - index.js:29 Document.models.Doc.summary
>     [mysite]/[wtf-plugin-summary]/src/index.js:29:13

The problem disappears when I downgrade back to wtf-plugin-summary v0.2 from NPM.

**Comment by spencermountain** [comment]
hey Tomáš, is there any reason you're not updating to v9? I'm not sure why this issue is happening, but I'm not sure debugging issues with prior versions is effective use of my time.
cheers

**Comment by Vacilando** [comment]
@spencermountain would love to but the summary and html plugins (at least) have wtf_wikipedia v8 as dependency, could you have another look at https://github.com/spencermountain/wtf_wikipedia/issues/449#issuecomment-998242941
