### ISSUE TITLE
How to get license and attribution?

### ISSUE THREAD

**Issue by FFatur** [spencermountain/wtf_wikipedia#451]
Hello,
First of all thank you to Spencer and all the other contributors to this amazing library!
I'm trying to get the license and attribution for the images via their commons page,
what I'm doing now is making the commons URL first and then trying to find the information from that page. however, I'm not sure how to advance.
as an example getting the second image's info from "Alexander the Great" wiki article:

```js
  wtf.fetch('Alexander the Great').then(doc => {
    let commonsPageURL = `https://commons.wikimedia.org/wiki/${doc.images()[1].file()}`
    wtf.fetch(commonsPageURL, {wiki:"commons.wikimedia"}).then(doc => {
      console.log(doc.tables()) // nothing
      console.log(doc.section("summary")) // nothing
      console.log(doc.section("licensing")) //nothing
      console.log(doc.sections()) // two sections with templates
    })
  })
```

Am I going about this in the wrong way?

**Comment by spencermountain** [comment]
hey @FFatur - that is a very clever solution, and a cool way to use the api.
Yeah- they sure don't make it easy. That image is using the [self](https://commons.wikimedia.org/wiki/Template:Self) template, and I've seen a lot of images use the [pd-self](https://commons.wikimedia.org/wiki/Template:PD-self) template.
Looks like there's also licence info in the [Information template](https://commons.wikimedia.org/wiki/Template:Information), like [this one](https://commons.wikimedia.org/w/index.php?title=File:Citrus_Cty_Crths_Inverness01.jpg&action=edit)

```js
wtf.fetch('https://commons.wikimedia.org/wiki/File:ACMA_1331_Alexander_2.JPG').then(doc => {
  let res = doc.templates().map(t => t.json())
  res = res.filter(o => o.template === 'self' || o.template === 'pd-self' || o.template === 'information')
  console.log(res)
})
```

oof - i'd be happy to work on improving this with you. If you got a sense for where the bulk of the licence data is, maybe we could add a `Image.licence()` method, or something?
cheers

**Comment by FFatur** [comment]
Thank you @spencermountain, yeah I'd like that! I'll let you know

**Comment by FFatur** [comment]
I think we need license info for two things: the general text of the wiki and the media.

- for a wiki's text, based on [here](https://www.mediawiki.org/wiki/API:Licensing) we can:
  [https://en.wikipedia.org/w/api.php?action=query&meta=siteinfo&siprop=rightsinfo](https://en.wikipedia.org/w/api.php?action=query&meta=siteinfo&siprop=rightsinfo)
- for media, based on [here](https://www.mediawiki.org/wiki/Extension:CommonsMetadata) we can:
  [https://commons.wikimedia.org/w/api.php?action=query&titles=File:ACMA%201331%20Alexander%202.JPG&prop=imageinfo&iiprop=extmetadata](https://commons.wikimedia.org/w/api.php?action=query&titles=File:ACMA%201331%20Alexander%202.JPG&prop=imageinfo&iiprop=extmetadata)

as for the related templates besides the ones above, I've found these:
[Machine readable data set by license templates](https://commons.wikimedia.org/wiki/Commons:Machine-readable_data#Machine_readable_data_set_by_license_templates)
[Credit line](https://commons.wikimedia.org/wiki/Commons:Credit_line)
[Copyright tags](https://commons.wikimedia.org/wiki/Commons:Copyright_tags)
[License templates](https://www.mediawiki.org/wiki/Category:License_templates)

**Comment by spencermountain** [comment]
oh hey, that's great. thank you for doing that.
we can add a call to `prop=imageinfo&iiprop=extmetadata` in the [images plugin](https://github.com/spencermountain/wtf_wikipedia/tree/master/plugins/image) - would that work for you?
cheers

**Comment by FFatur** [comment]
no problem,
absolutely, I'd make a PR but I don't know whether to use images plugin's server.js or the main doc's isomorphic-unfetch, among other things. Let me know if I could do something to help.
cheers mate

**Comment by spencermountain** [comment]
hey, sorry for the delay. 
Whatever you want! - I'm super easy.
If we added a method [here](https://github.com/spencermountain/wtf_wikipedia/blob/master/plugins/image/src/index.js) we could do  `doc.image(0).licence()` - that would be awesome.

Ha- i'm confused by the client-side http stuff too. Don't sweat it. Anything you'd like to do, feel free.
I can add this at the end of the month, otherwise.
thanks!

**Comment by FFatur** [comment]
Hey brother
so it's almost ready, but a question first
is the  [.images(clue)](https://github.com/spencermountain/wtf_wikipedia/blob/f5b2400a9c70312ef2dcbd5f6976dfeee761e405/src/01-document/Document.js#L308-L342) method supposed to return an array with one member after passing a clue? it's JSDoc seems to differ too.
some other methods do the same.

**Comment by spencermountain** [comment]
good question. Yeah, i was originally supporting `.images(0).json()`, as a supposedly-cleaner version than `.images()[0] ...` with null-checking. But the main library's been turning-back from that. The plugins should follow.
Like you said, it makes the typescript a mess. Feel free to change it - it just means a major version for the breaking change.
cheers
