### ISSUE TITLE
How to pass Api-User-Agent

### ISSUE THREAD

**Issue by Vacilando** [spencermountain/wtf_wikipedia#454]
Section https://github.com/spencermountain/wtf_wikipedia#good-practice contains:
```javascript
wtf
  .fetch(['Royal Cinema', 'Aldous Huxley'], 'en', {
    'Api-User-Agent': 'spencermountain@gmail.com',
  })
  .then((docList) => {
    let links = docList.map((doc) => doc.links())
    console.log(links)
  })
```

However, the third fetch parameter can now only be a callback.
Is it correct to assume that it now should be:
```javascript
wtf
  .fetch(['Royal Cinema', 'Aldous Huxley'], {
    lang: 'en',
    'Api-User-Agent': 'spencermountain@gmail.com',
  })
  .then((docList) => {
    let links = docList.map((doc) => doc.links())
    console.log(links)
  })
```

**Comment by spencermountain** [comment]
thanks @Vacilando - wanna make a PR?
there are some steps [here](https://github.com/spencermountain/wtf_wikipedia/wiki/Contributing) I can help if you'd like.
cheers

**Comment by spencermountain** [comment]
docs fixed - thank you for the heads-up!
