### ISSUE TITLE
Birth date and date of death disappeared

### ISSUE THREAD

**Issue by fchanson** [spencermountain/wtf_wikipedia#46]
Hi,

i use the plaintext method to retrieve the text of the article about people.
When this text contains the birth date and/or the date of death, these dates are missing.

For example in the article : 

Raoul Dautry est un ingénieur, dirigeant d'entreprises publiques et homme politique français, né le **16 septembre 1880** à Montluçon (Allier) et décédé le **21 août 1951** à Lourmarin (Vaucluse).

And the query result is : 

Raoul Dautry est un ingénieur, dirigeant d'entreprises publiques et homme politique français, né le à Montluçon (Allier) et décédé le à Lourmarin (Vaucluse).

The two dates are missing.

Is it an error or I need to do something to have the dates ?

Thanks.

**Comment by spencermountain** [comment]
hi Frédéric, yeah, i removed this intentionally, but you know what, i think somebody just removed that regex a few weeks ago
i may not have updated it, one sec

**Comment by spencermountain** [comment]
will you try it on wtf_wikipedia@0.7.0?

**Comment by fchanson** [comment]
my version is 0.6.1

**Comment by fchanson** [comment]
let me check with the version 0.7.0

**Comment by fchanson** [comment]
it is the same with the version 0.7.0

**Comment by spencermountain** [comment]
ok, i'll look at this later today

**Comment by fchanson** [comment]
thanks for your help

**Comment by spencermountain** [comment]
hey, got it.
`wtf_wikipedia@0.7.1`
cheers

**Comment by fchanson** [comment]
Thanks a lot spencermountain !!
It works now.
Have a nice day.
