### ISSUE TITLE
Reason behind limited regex length?

### ISSUE THREAD

**Issue by tomasz13nocon** [spencermountain/wtf_wikipedia#462]
Across the parser there are regexes like:
https://github.com/spencermountain/wtf_wikipedia/blob/f5b2400a9c70312ef2dcbd5f6976dfeee761e405/src/reference/index.js#L34
Is there any reason behind the arbitrary 1800 number? Mediawiki is able to handle much more than that (I don't think there is a limit at all).
This caused me trouble by not parsing a reference that was just a little longer than 1800 characters, but I saw regexes like this in other parts of the parser too. Should the `{0,1800}` be changed to `*`?

**Comment by spencermountain** [comment]
hey, yeah you're right. it's totally arbitrary, and pretty sloppy.
I've been slowly expanding them over the years, when i see a real-life example. Not too smart.

The danger is just that without it, a typo can destroy the whole page.
But yeah -  like you said, an unclosed ref tag will not render anything on wikipedia? so we should follow suit.
changes welcome!
thanks

**Comment by FFatur** [comment]
I'm having the same issue with bold text, the most number of characters I've seen is 1500, though it can go higher. does 2500 sound reasonable for these?:
https://github.com/spencermountain/wtf_wikipedia/blob/f5b2400a9c70312ef2dcbd5f6976dfeee761e405/src/04-sentence/formatting.js#L7-L26

**Comment by spencermountain** [comment]
Sure! Sounds good to me.
