### ISSUE TITLE
'poem' xml 

### ISSUE THREAD

**Issue by FFatur** [spencermountain/wtf_wikipedia#463]
`poem` xml is necessary in [here](https://en.wikipedia.org/wiki/Genghis_Khan#Positive) (the noble king...).
Would deleting `poem` from [here](https://github.com/spencermountain/wtf_wikipedia/blob/e702419c8ac8bb2b16965a46e3ac3b52b218ddcf/src/01-document/preProcess/kill_xml.js#L17) mess things up?

**Comment by spencermountain** [comment]
ooh! good catch. yeah we should definitely keep the inside of this xml.

yeah - in that file, if I remember, the xml *tags* will get deleted once they pass-through. 
good idea!
