### ISSUE TITLE
Looks typos

### ISSUE THREAD

**Issue by mikeda37** [spencermountain/wtf_wikipedia#474]
https://github.com/spencermountain/wtf_wikipedia/blob/476c7c17526538ff1c31ba3bd18310cfd5766a28/src/03-paragraph/Paragraph.js#L76
Do you mean `citations: 'citation'` ?

**Comment by spencermountain** [comment]
yep! good find. thank you
prs welcomed, or I can add it to the next release.
cheers

**Comment by mikeda37** [comment]
I tried fixing and push changes but I got permission error.
do you have any idea?
thanks!
```
remote: Permission to spencermountain/wtf_wikipedia.git denied to mikeda37.
fatal: unable to access 'https://github.com/spencermountain/wtf_wikipedia.git/': The requested URL returned error: 403
Pushing to https://github.com/spencermountain/wtf_wikipedia.git
```

**Comment by spencermountain** [comment]
hey @mikeda37 - yeah, you'll have to make a pull-request. Annoyingly, if you cloned this repo, you may have to create a fork, and then clone it and make your change again.
On your fork, i think there will be a button to make a PR.

I've got some [instructions here](https://github.com/spencermountain/wtf_wikipedia/wiki/Contributing) - but it's still a bit of a learning-curve 
let me know if I can help further,
cheers

**Comment by mikeda37** [comment]
oh i see, I need to fork before clone.
thanks for your kind help.  this is really good experience for me!
