### ISSUE TITLE
Japanese characters are not grabbed with this regex?

### ISSUE THREAD

**Issue by mikeda37** [spencermountain/wtf_wikipedia#475]
https://github.com/spencermountain/wtf_wikipedia/blob/476c7c17526538ff1c31ba3bd18310cfd5766a28/src/list/index.js#L6
Does this regex pattern grab Japanese characters?

**Comment by spencermountain** [comment]
oh, good catch. no it doesn't.
we should probably start using [the \p{Letter} syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes) - both here and elsewhere!
prs welcomed.
thanks

**Comment by mikeda37** [comment]
@spencermountain 
ok, i understand using **Unicode property escapes** but i just wonder if this filtering is necessary.
https://github.com/spencermountain/wtf_wikipedia/blob/476c7c17526538ff1c31ba3bd18310cfd5766a28/src/list/index.js#L42
can you please tell me what this is for?  i tried reading code but it's hard for me!
thanks

**Comment by spencermountain** [comment]
hey mikeda37, good question. I don't remember. 
If it's killing-off japanese language lists, feel free to remove or change it. My policy is that if the tests pass, it's good!

The [number of list formats](https://en.wikipedia.org/wiki/Help:List) is completely nuts, if you're digging around in that code, there's a lot of random template bits.

Lastly, if you're making a pr, I've been converting dev branch to use es-modules. I was gonna ship it today, but you're not supposed to do releases on fridays. So i may do that on monday. it may make sense to wait until then.
cheers

**Comment by mikeda37** [comment]
ok, you don't remember! 😄   i understand your policy!
i tested omiting the line but some unit tests fail here.
https://github.com/spencermountain/wtf_wikipedia/blob/a3abfaa394e3efcaa10a5fe3b4d4599b565e53f1/tests/unit/Document.test.js#L680
https://github.com/spencermountain/wtf_wikipedia/blob/a3abfaa394e3efcaa10a5fe3b4d4599b565e53f1/tests/unit/Document.test.js#L699
you dont't remember these tests too?  do you think i can remove these tests?

if you want to keep those tests, i would think of using unicode property for filtering and then i need a few weeks until pr.
you can work for es-modules convertings soon!
but in case you approve to remove those two tests, i can make a pr in a few days!
thanks

**Comment by spencermountain** [comment]
ok, 10.0.0 is released, you'll need to update before making a PR, let me know if I can help.
cheers

**Comment by mikeda37** [comment]
ok, i got it!
how do you think about deleting those two tests?   I did't understand those tests contents..
do you think we should keep them? or you think I have to analyze and judge?
thanks

**Comment by spencermountain** [comment]
hey - in the anarchism page, there are a bunch of lists with citations, with render no text, so they are empty lists.
the tests are correct - we need to filter them out. Feel free to come up with whatever solution you'd like
cheers

![image](https://user-images.githubusercontent.com/399657/161840555-5a53fd87-b5d8-43f7-a56f-e2c74058c977.png)

**Comment by mikeda37** [comment]
@spencermountain, thanks for your explanation!
I see, those filtering is to remove empty lists, right?
So I won't delete the filtering and instead, I will fix this regex pattern `/[a-z_0-9\]}]/i ` as removing empty lines but not to kill the unicode characters.  is it fine?

by the way, the test fails with the latest source!
cheers

**Comment by spencermountain** [comment]
yep, that sounds good.
thanks

**Comment by spencermountain** [comment]
hi @mikeda37 i've added unicode support to the list regex you found in `10.0.2` - please let me know if you find any others
cheers

**Comment by mikeda37** [comment]
hi, @spencermountain  sorry for leaving the task and thanks for the fix!
I will try the fixed code when I got time.
thanks
