### ISSUE TITLE
Question: How performant / fast is the parser?

### ISSUE THREAD

**Issue by lightningboss** [spencermountain/wtf_wikipedia#48]
Hello,

I want to build something like a WikiGame, but with custom styles for the article. Do you think this is a good use case for the library or should I just fetch the rendered html from the API and style that myself?
Is this library fast enough to parse the html from a browser of a huge Wikipedia page or is it rather inefficient?

Thanks,
Marc

**Comment by spencermountain** [comment]
hey Marc, yeah that's a good question.
I wouldn't worry about performance really, it's all speedy regex and never more than a few milliseconds i bet. The choice is really what kinda transforms you'd like to do to the page. If it can be done with css and a couple selectors, I'd say go with that.

**Comment by spencermountain** [comment]
if you are looking for a parsed structure of the data on the page, this will do that for you
cheers
