### ISSUE TITLE
Disambiguation check fails for https://en.wikipedia.org/wiki/22

### ISSUE THREAD

**Issue by p-himik** [spencermountain/wtf_wikipedia#485]
The root cause is that the pattern at https://github.com/spencermountain/wtf_wikipedia/blob/master/src/01-document/isDisambig.js#L17 doesn't have one of the spaces around `(also)?` within those parentheses.
Meaning, `"may[space]refer to"` doesn't match while `"may[space][space]refer to"` does.

**Comment by spencermountain** [comment]
good catch - fixed in `10.0.1`
thanks!

**Comment by p-himik** [comment]
Just found a false positive - https://en.wikipedia.org/wiki/Taraxacum
It matches because its hatnote says: 
> "Dandelion" redirects here. **It may refer to** any species of the genus Taraxacum or specifically to [Taraxacum officinale](https://en.wikipedia.org/wiki/Taraxacum_officinale). For similar plants, see [False dandelion](https://en.wikipedia.org/wiki/False_dandelion). For other uses, see [Dandelion (disambiguation)](https://en.wikipedia.org/wiki/Dandelion_(disambiguation))

Not sure what the best way to handle it would be. Do proper or improper disambiguation pages every have an infobox?

**Comment by spencermountain** [comment]
thanks, good catch

**Comment by spencermountain** [comment]
thanks Eugene, both have been fixed now on 10.0.2, but please let me know if you see any others - we may find that the 'may refer to' heuristic is too sloppy, in the end.
cheers
