### ISSUE TITLE
Skip red links

### ISSUE THREAD

**Issue by Patrik-scx** [spencermountain/wtf_wikipedia#487]
Hi there!

Found that red links are coming from .links() method, but they actually doesn't link to any topic.
Is there a way to filter them?

https://en.wikipedia.org/wiki/Cup_of_Excellence

![image](https://user-images.githubusercontent.com/41302223/172662840-626da40b-7686-498c-b38f-bdf5ca3bab81.png)

![image](https://user-images.githubusercontent.com/41302223/172662666-5d0afc99-6238-40a2-8b16-ea1a55fa3c4b.png)

**Comment by spencermountain** [comment]
hi Ivan, yeah that would be neat. it's not possible without downloading the [list of pages](https://dumps.wikimedia.org/wikidatawiki/20220520/#:~:text=wikidatawiki%2D20220520%2Dall%2Dtitles%2Din%2Dns0.gz) and redirects. Luckily these files are not too big.

You could also do it by scraping the html. it must be done internally at render-time.
cheers

**Comment by Patrik-scx** [comment]
@spencermountain , thank you for workaround:)
