### ISSUE TITLE
Section heading parsing only first template

### ISSUE THREAD

**Issue by marcelogp** [spencermountain/wtf_wikipedia#489]
Some section heading may contain more than one template but only the first one is being parsed. For example in https://fr.wikipedia.org/wiki/Michael_Jackson

```
==== Désunion des Jacksons, ''{{langue|en|Northern Songs}}'' et ''{{langue|en|Captain Eo}}'' (1984-1986) ====
```

A solution would be using this implementation in `heading.js`:

```js
const doInlineTemplates = function (wiki) {
  let list = getTemplates(wiki)
  list.forEach((item) => {
    let [txt] = parseTemplates(item)
    wiki = wiki.replace(item.body, txt)
  })
  return wiki
}
```

**Comment by spencermountain** [comment]
thank you Marcelo! great idea, wanna make a PR?
I can add this in, otherwise.
cheers
