### ISSUE TITLE
Origin is not allowed by Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by Residu** [spencermountain/wtf_wikipedia#49]
Got "Origin is not allowed by Access-Control-Allow-Origin, Origin 'null' is therefore not allowed access." when trying to call mediawiki API.
I am actually trying it on localhost (with my etc/hosts edited to have a 'real' url). 

Is it possible to add an option to use anonymous call with origin: * ?

See https://www.mediawiki.org/wiki/Manual:CORS for further information.

Thanks for your help.

**Comment by spencermountain** [comment]
Hey, thanks. Never thought of that. 
Will check it out this afternoon

**Comment by Residu** [comment]
Thanks for your reactivity!
Got any news about this bug fix?

**Comment by spencermountain** [comment]
hey Residu, yeah you're right about how half-baked the client-side fetch stuff is on my side.
we were using the raw api, not the mediawiki api, and both have pretty-fun cors rules.
for what it's worth, you can get it to work right now on the client-side like this:
```js
      var url="https://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvlimit=1&rvprop=content&format=json&origin=*&titles=Radiohead"
      $.get(url, function(data){
        var str=data.query.pages['38252'].revisions[0]['*']
        console.log(wtf_wikipedia.parse(str))
      })
```
where 382... is the pageId. :sweat: 

so i'm gonna look at getting this new strategy into the lib. little busy this week, but hope that helps
cheers

**Comment by spencermountain** [comment]
just looking at that example now. I'm not a judgy computer programmer, but man...
what a total nightmare.

**Comment by spencermountain** [comment]
hey, i got this working in `v0.8.0`
it should 'just work' from the client-side now.
you can see it making cross-origin reqs [here](https://rawgit.com/spencermountain/wtf_wikipedia/master/demo/fetch.html)
cheers

**Comment by Residu** [comment]
Thank you for your work dude ! Gonna try it soon !
