### ISSUE TITLE
Broken i18n aliases for "small" template 

### ISSUE THREAD

**Issue by marcelogp** [spencermountain/wtf_wikipedia#490]
While using the `wtf-plugin-i18n`, I came across a [page](https://pt.wikipedia.org/wiki/Mariah_Carey) containing the `pequeno` template which causes a crash. The problem is that it is assumed that `small` is a function-based template while it's actually a "zero" template.

```
TypeError: templates[k] is not a function
        at Object.templates.<computed> [as pequeno] ([...]/wtf-plugin-i18n.cjs:890:30)
```

**Comment by spencermountain** [comment]
hey thank you Marcelo, this is a good bug.
yeah, you're right - the i18n plugin should learn to ingest the template shorthand.
I've got a quick fix on dev, but should change this properly in the i18n method.
in the meantime, you can do something like this:
```js
wtf.extend((models, templates) => {
  templates.small = (tmpl) => {
    let obj = parse(tmpl)
    if (obj.list && obj.list[0]) {
      return obj.list[0]
    }
    return ''
  }
)
```
thanks!

**Comment by marcelogp** [comment]
Thanks, but unfortunately I just found another [case](https://fr.wikipedia.org/wiki/Shania_Twain): the `prononciation api` template as an alias for `ipa`. So I'd rather have a general solution

**Comment by marcelogp** [comment]
Sorry, I had actually added an override for the `ipa` template, so it's not the case
