### ISSUE TITLE
export Image module

### ISSUE THREAD

**Issue by Patrik-scx** [spencermountain/wtf_wikipedia#496]
Hello @spencermountain ,

currently i'm working a lot with your library and there is a case i need **src/image/Image** to be exported.
Previously i could do it like this:
const Image = require('wtf_wikipedia/src/image/Image');

But with latest version i can't have access to it because of ERR_PACKAGE_PATH_NOT_EXPORTED.

I have tried to do PR, but i couldn't achieve it:)

![image](https://user-images.githubusercontent.com/41302223/182664775-4d668dda-2269-4c66-a82d-20a1f6acc645.png)

Could you please export your Image module or even all modules?

**Comment by spencermountain** [comment]
hey @Patrik-scx yeah, that sounds doable like this:
```js
wtf.extend((models) => {
  models.Image.prototype.isCool = function () {
    console.log('true')
  }
})
let doc = wtf('[[File:myImg.png]]')
doc.image().isCool()
//true
```
lemme know if that does the trick
cheers

**Comment by Patrik-scx** [comment]
Yeah, it works.

Thank you for a quick response and pointing to right direction!
