### ISSUE TITLE
extra dot of link type `wikipedia` ?

### ISSUE THREAD

**Issue by KKzLEO** [spencermountain/wtf_wikipedia#510]
there is an extra `.` of link type `wikipedia`

in `interwiki.js`

![image](https://user-images.githubusercontent.com/26006239/209655034-6f5e691a-df17-4403-b8b9-e569d186592b.png)

```
const wp = '.wikipedia.org/wiki/$1'
```

that will become `en..wikipedia.org`

**Comment by spencermountain** [comment]
Agh Thank you, I will fix this in the next few days in the next release
Cheers

**Comment by spencermountain** [comment]
fixed in 10.1.0 - thank you!
