### ISSUE TITLE
template text removed from sections

### ISSUE THREAD

**Issue by rg3h** [spencermountain/wtf_wikipedia#512]
I am not sure if this is a bug or an unavoidable effect from templates.
For wikipedia entry December_30 there is a line item in the event section:
*  2006   &ndash; The Indonesian passenger ferry {{MV|Senopati Nusantara}} sinks in a storm, resulting in at least 400 deaths.

In Section.js the constructor calls parseTemplates() which appears to remove the {{...}} and so the name of the ferry is lost and the results become:  The Indonesian passenger ferry sinks in a storm, resulting in at least 400 deaths.

I am wondering if it is possible to have the text "Senopati Nusantara" retained?

**Comment by spencermountain** [comment]
hey rich - good find. Looks like we've missed a few ship templates
I'll add these to the next release, but in the meantime, you can do this:
```js
wtf.extend((models, templates) => {
  templates.mv = 0 // support this new template
})
```
https://runkit.com/spencermountain/63b1ffef955fc900081d3304
cheers

**Comment by rg3h** [comment]
Got it, thanks, it works!

[image: d30b4204-5427-44e3-a3ba-f42a66a2ff57.png]

I don't know templates, have to check them out.   I wonder if I can turn
the ship into a link [[Senopati Nusantara]] and then be able to reference
the ship for an image.  Either way, this extend method worked like a charm
until you update the code. Thanks!

rich

**Comment by spencermountain** [comment]
hey Rich, this should be working now in `10.1.1`
lemme know if you spot any others. Thanks

**Comment by rg3h** [comment]
Thanks! Will do!
