### ISSUE TITLE
Not picking up US Senator designations via "jr/sr" 

### ISSUE THREAD

**Issue by tmtmtmtm** [spencermountain/wtf_wikipedia#518]
US Senators used to be designated in their infobox via a "jr/sr" parameter. This is now deprecated, but remnants of it still remain, and it resurfaces from time to time — for example it's [currently included in Joe Biden's](https://en.wikipedia.org/w/index.php?title=Joe_Biden&oldid=1142686646):

```
| jr/sr3              = United States Senator
| state3              = [[Delaware]]
| term_start3         = January 3, 1973
| term_end3           = January 15, 2009
| predecessor3        = [[J. Caleb Boggs]]
| successor3          = [[Ted Kaufman]]
```

But wtf_wikipedia (as of 10.1.2) skips the 'jr/sr3' value, leaving this section with no "key" to say what sort of role it is:

```json
          "successor2": {
            "text": "Mike Pence",
            "links": [
              {
                "type": "internal",
                "page": "Mike Pence"
              }
            ]
          },
          "state3": {
            "text": "Delaware",
            "links": [
              {
                "type": "internal",
                "page": "Delaware"
              }
            ]
          },
          "term_start3": {
            "text": "January 3, 1973"
          },
```

Even though this probably _shouldn't_ be appearing (and will probably get removed again), it would be good if wtf_wikipedia could handle it in the cases where it _does_, especially as these tend to be quite high-profile pages.

**Comment by spencermountain** [comment]
good catch! got a fix on dev branch, will be in the next release.
thanks

**Comment by spencermountain** [comment]
should work now, in 10.1.3
