### ISSUE TITLE
getCategoryPages doesn't return sub-categories

### ISSUE THREAD

**Issue by tstibbs** [spencermountain/wtf_wikipedia#521]
I'm trying to upgrade some of my code from version 8.4.0 to latest, and seeing that the way to fetch pages in a category has changed, and I don't think the doc is correct (and I'd happily fix it but I can't work out what it needs to say!).

In 8.4.0, you could call `wtf.category` and it would return you all pages in that specific category, plus any subcategories (see https://runkit.com/tstibbs/wtf-wikipedia-categories---8-4-0/1.0.2). This allowed you to go through all the subcategories recursively and fetch all the pages sitting in the hierarchy under that category.

In the latest version, this has all moved into the plugin api. However just calling `getCategoryPages` only returns pages directly in that category, not in sub-categories (see https://runkit.com/tstibbs/wtf-wikipedia-categories---latest/1.0.0). The doc (https://github.com/spencermountain/wtf_wikipedia/blob/72df97699380e415b94154afc0b5566df5afb5a5/plugins/api/README.md?plain=1#L128) says that you can request categories to a specific depth (which would be perfect for my use-case), but it doesn't explain how. I've had a quick look through the code and can't see anything that would allow you to specify the depth.

As a slight aside, the main readme still appears to have the old way of getting categories: https://github.com/spencermountain/wtf_wikipedia/blob/72df97699380e415b94154afc0b5566df5afb5a5/README.md?plain=1#L368 - I'll fix this in a PR along with whatever needs changing above.

If I've missed something obvious please accept my apologies in advance...

----

Edit:

Interestingly, removing the `cmnamespace` param (https://github.com/spencermountain/wtf_wikipedia/blob/72df97699380e415b94154afc0b5566df5afb5a5/plugins/api/src/getCategory.js#L8) does allow the subcategories to be returned.

https://lists.wikimedia.org/pipermail/mediawiki-api-announce/2011-October/000025.html suggests that `cmnamespace=0` is already implied by `cmtype=page` which we're already specifying. However that link does suggest that it might bring in more page types than that (e.g. namespace 2 AKA user pages, according to https://www.mediawiki.org/wiki/Manual:Namespace). This may or may not be a problem (in my case I only want 'real' content articles but other users might want to be able to get meta pages that are in categories).

However this still doesn't recursively bring back all pages within all subcategories (as implied by the docs) so I'm still not sure if this is the intended behaviour or not.

**Comment by tstibbs** [comment]
Just realised that a simpler fix is to change the requested namespace to `0|14` (real content articles and category pages), which shouldn't bring in any more results than previously (apart from the category pages). This still doesn't align it with the doc that talks about a specific depth though, but I'm increasingly thinking that the doc is just plain wrong. Unless anyone has any strong opinions to the contrary, I'll raise a PR to change the namespace and fix the docs to bring them in to line with the current behaviour.

**Comment by spencermountain** [comment]
hey @tstibbs - that would be amazing. Yeah, the api plugin is a mess, and needs a lot of love. Please take it for a spin, and add any features you think it is missing. 
You're right - these things were split from the main lib mostly for filesize. There's plenty of room now, to implement things properly, in the api plugin. Let me know if I can help out, in any way. I'm getting smoked this week, but can lend a hand.
cheers!

**Comment by tstibbs** [comment]
Cool, my plan is to fix the namespace bug and align the docs first - then I'll look at adding the recursive fetching as a separate task if/when I can find time.

In the meantime, PR to fix a minor issue with the custom user agent being ignored in this plugin: https://github.com/spencermountain/wtf_wikipedia/pull/522

**Comment by spencermountain** [comment]
hey - i copied `_headers.js` over just cause it's been a long week ;)
released as wtf-plugin-api@2.0.0 👌👌
