### ISSUE TITLE
HTML comments and other template issues.

### ISSUE THREAD

**Issue by andremacola** [spencermountain/wtf_wikipedia#536]
I ended up creating an internal script that saves all possible terms/urls from Wikipedia with potential problems in Wikitext to a database. So far, I've found around 1500 articles with some peculiarities in the Portuguese Wikipedia.

Shouldn't WTF remove HTML comments within Wikitext? Check out the example of doc.text() on this page: https://pt.wikipedia.org/wiki/Elei%C3%A7%C3%B5es_legislativas_na_Tun%C3%ADsia_em_2019

There are some pages that caught my attention and have similar problems to a previous issue (https://github.com/spencermountain/wtf_wikipedia/issues/532), but I think they involve other templates issues:
- https://pt.wikipedia.org/wiki/Darling_in_the_Franxx
- https://pt.wikipedia.org/wiki/Tokyo_Waterfront_Area_Rapid_Transit
- https://pt.wikipedia.org/wiki/Makoto_Shinkai
- https://pt.wikipedia.org/wiki/Caso_Bruce

I'm still getting familiar with templates in Wikitext, but if you point me in the right direction, I can start creating patches for each problem found.

**Comment by spencermountain** [comment]
this is great. thank you

**Comment by spencermountain** [comment]
hey, fixed the long-comment regex, and added support for `Nihongo` template in Portuguese.
You'll have to update both wtf_wikipedia and use `wtf-plugin-18n`

I think the last one is ill-formed wikiscript.
<img width="388" alt="image" src="https://github.com/spencermountain/wtf_wikipedia/assets/399657/fac66b0e-3453-480d-ac6b-9fd0fcdabfd0">

Would love some help to improve Portuguese wp support.
cheers
