### ISSUE TITLE
Improve error handling: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by MarketingPip** [spencermountain/wtf_wikipedia#547]
When WTF-Wikipedia fetches and makes a good connection it will try to to convert things into a object.

A error should be thrown in cases where it is NOT able to convert it into an object.

Un-handled Errors: 

```js
/node_modules/wtf_wikipedia/src/_fetch/index.js:71:18
TypeError: Cannot convert undefined or null to object
```
Now obviously this is due to a URL being provided that is not a Wiki page etc. But still should be handled.

I will see if I can possibly get around to making a PR for this (feel free to do this before me), but leaving this here for now.

**Comment by spencermountain** [comment]
Good idea - PR welcomed for this.

**Comment by MarketingPip** [comment]
Closing issue as PR was made that addresses this.
