### ISSUE TITLE
Parse each table entry into object

### ISSUE THREAD

**Issue by cckelly21** [spencermountain/wtf_wikipedia#56]
Hey there! Right now each table cell gets parsed into it's own key in the Map that gets returned, would be great to get the entire entry as an object and grab the columns from there.

**Comment by spencermountain** [comment]
hey Charles, yeah. this is a good idea. 
We're due for a [whole](https://github.com/spencermountain/wtf_wikipedia/issues/39) [result](https://github.com/spencermountain/wtf_wikipedia/pull/55) reformat. what would be the best shape for it?
cheers

**Comment by cckelly21** [comment]
Using the 'Licensed Games' as an example from https://en.wikipedia.org/wiki/List_of_Nintendo_Entertainment_System_games, it could return something along the lines of:

```javascript
{
  { 'Title': '10-Yard Fight', 'Publisher': 'Nintendo' },
  { 'Title': '1942', 'Publisher': 'Capcom' }
  etc
}
```
Thoughts?

**Comment by spencermountain** [comment]
yeah. that's way better. i agree.
lemme see what i can do

**Comment by cckelly21** [comment]
Sweet! Looking forward to it, let me know if I can help.

**Comment by spencermountain** [comment]
hey, this is done now in `v1.0.0`, can you check it out?

**Comment by cckelly21** [comment]
Will do!
