### ISSUE TITLE
[Issue]: Missing text value's when parsing Wikivoyage children

### ISSUE THREAD

**Issue by MarketingPip** [spencermountain/wtf_wikipedia#560]
When using .sections() normally, you can see the templates with text properly parsed from Wiki Markup. But when calling using .children() values are returning as ```''```.

**Comment by spencermountain** [comment]
Thanks Jared, can you give an example so I can reproduce this?
Thanks

**Comment by MarketingPip** [comment]
My apologizes - I was making improper usage of "wtf_wikipedia". I was calling .children() & "text" key(s) are returning empty in "_templates" for the objects.

Which I should have been calling  ```doc.children()[my_index_here].json()``` to access the templates instead of  ```doc.children()[my_index_here].json()```

My stupidity. 

Thanks for quick reply & hope you had an awesome thanksgiving Spencer, cheers!
