### ISSUE TITLE
Thoughts regarding paid bubble.io plugin based on wtf_wikipedia

### ISSUE THREAD

**Issue by einSelbst** [spencermountain/wtf_wikipedia#566]
As mentioned in the other issue I'm thinking about creation a plugin for bubble.io.

I would like to get your thoughts regarding making this a paid plugin. Since everything here seems to be MIT licensed it would probably be fine from this perspective.

However, I wouldn't make a paid plugin if you're not d'accord.

I could imagine partially feeding back the income to you as a sponsor if you so desire. 

Please let me know your opinion. Thanks, Silvio

PS: I think, it could also be an interesting option if you yourself would consider making a paid bubble.io plugin out of this library.

**Comment by spencermountain** [comment]
Sure! Let me know if i can help in any way.
