### ISSUE TITLE
Parsing sentences (Wikivoyage)

### ISSUE THREAD

**Issue by wginsberg** [spencermountain/wtf_wikipedia#575]
First - thanks for this project!

I noticed that there is an issue parsing the sentences on the Wikivoyage page for [Sault Sainte Marie (Ontario)](https://en.wikivoyage.org/wiki/Sault_Sainte_Marie_(Ontario))

Using the following code:
```
wtf(text)?.sentences()?.[0]?.text()
```

I am getting the result 
```
'''[https://saulttourism.com/ Sault Ste.
```

Obviously looks like the period is being interpreted as the end of the sentence, but i do not have the same problem with other pages. E.g. [St. Clairsville (Ohio)](https://en.wikivoyage.org/wiki/St._Clairsville_(Ohio)) comes back as expected:
```
St. Clairsville is a city of 5,100 people (2020) in western Belmont County, Ohio.
```

This is the only instance of the issue I have found so far, so I guess it is not a huge deal. Though I wonder if it would be a nice feature to have a set of strings to pass to `sentences()` that would prevent breaking?

I.e. calling
```
doc.sentences(["string including a. period"])
```
Would guarantee that no sentence would break across that string? Just a thought.

**Comment by spencermountain** [comment]
hey Will, ya, you're right.
we have [a list](https://github.com/spencermountain/wtf_wikipedia/blob/dev/src/04-sentence/_abbreviations.js) of hard-coded abbreviations, and no way to augment it on the fly right now, and that's a lousy solution.
Happy to take a look at this. A proper solution may require a breaking change. A quicker one may just be adding 'ste' to the list.
cheers

**Comment by spencermountain** [comment]
hey Will, I've added `ste` and a known abbreviation, and am putting augmenting this list as a table-stakes feature for v11.
you should see the change in `10.3.2`.
cheers
