### ISSUE TITLE
support es6 package.json entries

### ISSUE THREAD

**Issue by spartanPAGE** [spencermountain/wtf_wikipedia#58]
I'm using your library with angular-cli generated project. It works flawlessly locally in dev mode, but when trying to generate production build i get this:
```
ERROR in vendor.167aea1ea9373484afbe.bundle.js from UglifyJs
Unexpected token: name (url) [vendor.167aea1ea9373484afbe.bundle.js:15769,6]
```
and it starts to work again after removing even the most basic form of import, i.e. `import 'wtf_wikipedia';`

If you want to reproduce the problem, here's the code: https://bitbucket.org/spartanPAGE/notes-assistant/src/e1705786b5452ec25609c35846fa2ed543b5c15e

**Comment by derhuerst** [comment]
For a production build, you should consider transpiling the `import` statement using e.g. [Babel](http://babeljs.io). Also, what is you UglifyJS version? Are you using `uglify-js@2` or `uglify-es@3`?

**Comment by derhuerst** [comment]
@spencermountain It might also be nice to include more entry points in `package.json`, so that users with a transpiling setup get to transpile the `src` code, whereas all other get to bundle the code in `build`. See also https://github.com/ternjs/acorn/issues/305.

**Comment by spencermountain** [comment]
hey Patryk, sorry about this, just got back from vacation.
yeah, like Jannis said, i suspect it's a uglify-babel plugin/pre-parser you'll need for your build, and not an issue with this library, which just uses the old-school require statements. 

yeah @derhuerst, `jsnext:main` sounds like a good idea to me. :rocket:
