### ISSUE TITLE
strange error related to keys on node 8 

### ISSUE THREAD

**Issue by saurabhvyas** [spencermountain/wtf_wikipedia#61]
let arr = Object.keys(data.sections).map(k => {
                   ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.plaintext (/home/saurabh/node_modules/wtf_wikipedia/src/index.js:25:20)
    at onFileContent (/home/saurabh/Desktop/comprehension_burden/wikipedia_w2v/wiki_xml_to_jsonv2.js:10:22)
    at /home/saurabh/Desktop/comprehension_burden/wikipedia_w2v/wiki_xml_to_jsonv2.js:45:9
    at tryToString (fs.js:513:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12)

 Update : Here is it's stackoverflow question I posted along with code 
https://stackoverflow.com/questions/45839226/easiest-way-to-convert-wikitext-to-plaintext

**Comment by spencermountain** [comment]
hey Saurabh, yeah, looks like even the tests are failing on master, i should've checked the last PR.
will look at it today, thanks.

**Comment by saurabhvyas** [comment]
cool , great work though , I really appreciate the hard work you have put it , to make it :)

**Comment by spencermountain** [comment]
hey do you happen to know which article it trips on?
can you do a `console.log(file)` and see where it stops?

**Comment by spencermountain** [comment]
hey, if you get a chance, you can try the latest on master, it should work like a charm.
I'm waiting to publish it until the return format stabilizes a little bit, we just changed a bunch of stuff.
lemme know if you run into something. 
cheers

**Comment by saurabhvyas** [comment]
Yes Thanks , I'll close this for now then
