### ISSUE TITLE
Long tables parsed incorrectly

### ISSUE THREAD

**Issue by tstibbs** [spencermountain/wtf_wikipedia#62]
It appears that large tables can fail to be parsed. 

This is about the most minimal workable example I can come up with:
````javascript
const wtfWikipedia = require('wtf_wikipedia')

function areTablesParsedCorrectly(charCount) {
    const longString = 'a'.repeat(charCount)

    const input = `
{| class="wikitable"
|-
| ${longString}
|}`

    var obj = wtfWikipedia.parse(input)
    return obj.tables.length > 0
}

console.log(areTablesParsedCorrectly(7975))
console.log(areTablesParsedCorrectly(7976))
````

Based on the numbers above, I think this happens when the markup between the braces hits 8000 chars (ignoring newlines). The expected behaviour is that the contents of the table is parsed into the 'tables' element. The actual behaviour (when above this string length) is that the table contents is parsed into sections/list/text.

Reproduced with wtf_wikipedia version 1.0.1, node v7.4.0.

**Comment by tstibbs** [comment]
On a whim tried searching the codebase for 8000 - looks like there's a regex in [table.js](https://github.com/spencermountain/wtf_wikipedia/blob/5b8d41e3d421379c5465eed9fe6772e925932412/src/parse/table.js#L4) which limits a table match to 8000 non-whitespace chars.

So looks like this is a similar issue to #23. Not sure what to suggest this should be changed to. For context I noticed the failure while trying to parse the first table in https://en.wikipedia.org/wiki/List_of_RNLI_stations, so their definitely are tables out there that exceed the current limit.

**Comment by spencermountain** [comment]
ha! thanks Timothy, you win the prize for most well-reported bug.
yea, it looks like a poorly-chosen arbitrary number that should be fixed.
i've got `v2` with a bunch of fixes/changes on it, and i can increase the number there.
alternatively, i'd be open to making the table-parsing smarter too, if you have any ideas.
cheers!

**Comment by spencermountain** [comment]
oh, v2 is actually on master, if you wanted to make a PR.
software engineering!

**Comment by tstibbs** [comment]
It's tricky choosing a sufficiently large number. I understand from #23 that these limits are to stop it over-matching on a page with badly formed markup. However, if you set the number to be large enough to match the largest table on wikipedia, there's a good chance that this will be more characters than the entire page for many of the other pages on wikipedia, which would make the number useless for most cases.

So I guess the question is do we want to support badly-formed markup at the expense of being able to correctly parse larger pages? If so, the current solution is fine. If not, the numbers possibly need to go.

Another option might be to do the full match, then look at what it matched to try to detect if we've over-matched, and if so apply a regex with some limits in. If the limits come in to play then the likelihood is that it would parse the page wrongly anyway, so the limits really are a last resort.

**Comment by spencermountain** [comment]
hey, think i got this, wanna check it on v2.0?
