### ISSUE TITLE
{{coords}} template

### ISSUE THREAD

**Issue by Amantel** [spencermountain/wtf_wikipedia#65]
There is ` <text xml:space="preserve">{{pagebanner|Moscow Banner.jpg|disambig=yes}}"` in XML, but I can not find it anywhere after running the script

**Comment by spencermountain** [comment]
hey @Amantel never heard of that template, you know anything about it?
cheers

**Comment by Amantel** [comment]
Hallo! 

It is wikivoyage template - https://en.wikivoyage.org/w/index.php?title=Moscow&action=edit (top of the editing block).

BTW, I simply modified to populate r.pagebanner using regexp before first preProcess call and it works, but maybe there is another, better method. 

There are same (?) problems with getting coordinates from Wikipedia articles too
https://en.wikipedia.org/w/index.php?title=Tretyakov_Gallery&action=edit 
{{Authority control}}
{{coord|55|44|29|N|37|37|13|E|region:RU_type:landmark|display=title}}


All and all, of cause this is not a problem of wtf_wikipedia, that there are some elements that are needed by some applications, but some text guide, how to get them will be nice :)

**Comment by spencermountain** [comment]
yeah, you're right. thank you. There should be a clever way to add a hook somehow, to support new templates. It's never gonna have them all.

yeah, {{template:coord}} should definitely be supported top-level. That's a huge one, thanks for showing me.

-those are nice images on that template. maybe we should add support for this, if it's gonna become popular. prs welcome!

**Comment by Amantel** [comment]
Alright!

**Comment by spencermountain** [comment]
hey, what result format were you thinking of for `{{coord}}`?
i've never understood lat/lng vs minutes/seconds, etc
[check it out](https://en.wikipedia.org/wiki/Template:Coord)?

**Comment by Amantel** [comment]
Hallo! 

I propose next format for `{{coord}}`

`
coordinates: 
    type: either minutes or normal coordinates
    lat: float, positive or negative 
    lng: float, positive or negative
    arc: null or object(not sure it have to be called like this)  
        lat: 
                degrees
                minutes
                seconds
        lng: 
                degrees
                minutes
                seconds
    params: - array of additional parameters line `dim` or `scale`
`
Basically we are looking for 3 types of structures:
1. Normal coordinates (with positive or negative float values)
2. Normal coordinates (with N/W/S/E and only positive float values - that we should convert to 1
3. Degrees, Minutes and Seconds (optional)

If there is nothing like it `{{coord}}` element is malformed, screw it.

I hope I understood your question correctly. 

*****
My thought on this:

I am more interested in coordinates of objects, and they are pretty straightforward like 
`{{Listing|name=Lisboa Ask Me Centre|address=Pç. do Comércio|phone=+351 21 031-2815|hours=open 09:00-20:00 daily|lat=38.70788 | long=-9.13786|content=The sparkling new centre will help you find accommodation and the staff are happy to dispense advice, maps and brochures. Smaller '''Ask Me Lisboa kiosks''' are dotted about the Rossio district and airport and their multilingual staff also have maps and brochures.}}
`  (https://en.wikivoyage.org/w/index.php?title=Lisbon&action=edit&section=10)

So if we see long=something or lat=something that is pretty clear.

When we are talking about `coord` you mentioned it is getting much worse (like most things with wiki). 

I do not completely understand lat/lng vs minutes/... too (even after trying to read this https://en.wikipedia.org/wiki/Latitude#Length_of_a_degree_of_latitude), but I think this is not our place to decide anything for final user. 
We have clear distinction between latitude and minutes (and stuff)
**Former**: `Coord|57|18|22|N|4|27|32|W`  - 3 items (more then 1 to be more exact) between Coord and N and three between N and W. That's degrees, minutes, and seconds of arc, so we can just store them as an object with this properties. If somebody wish to use it (or have no way to avoid it) - that's there problem to convert that variables to proper coordinates, if needed;

**Later**: `Coord|44.112|N|87.913|W|` - one "float" item between each pipes, which can be only positive or `Coord|44.112|-87.913|`  - where they can be positive or negative. And they are basically the same, where first value is latitude, and second one is longitude.

**Comment by spencermountain** [comment]
hey @Amantel thanks for your help.
So i nearly fell out of my chair when i found out these formats are in fact, just some basic arithmetic away from each other. I [stole some code](https://github.com/spencermountain/wtf_wikipedia/blob/master/src/lib/convertGeo.js) from a couple geo conversion-libraries, and you  [can see](https://github.com/spencermountain/wtf_wikipedia/blob/master/tests/coord.test.js) it actually converting minute/second form to basic lat/longs. Wanna try it out and kick the tires a bit?
there's definitely gonna be bugs, but i like the idea of normalizing it into one format for people.
cheers

**Comment by spencermountain** [comment]
coords template, even from inside a infobox, now is being parsed in v2.2.0.
there's probably a bunch of issues, but i tested it a fair amount.
lemme know if you see anything.
cheers
