### ISSUE TITLE
Removing valid listings during  parse.infobox stage

### ISSUE THREAD

**Issue by Amantel** [spencermountain/wtf_wikipedia#66]
**Example setup**
Information from https://en.wikivoyage.org/w/index.php?title=Barcelona&action=edit&section=5

```
===Visitor information===
* {{listing
| name=Tourist office at Plaça de Catalunya | alt= | url=http://www.barcelonaturisme.com/wv3/en/page/38/tourist-information-points.html | email=
| address=Plaça de Catalunya, 17-S | lat=41.3868027 | long=2.1707225 | directions=Metro: L1, L3. Bus: 9, 22, 28, 42, 47, 58, 66, 67, 68. Train: R4
| phone= | tollfree= | fax=
| hours=8:30am-8:30pm | price=
| lastedit=2015-10-22
| content=This is the main tourist office in the city.
}}

The other tourist offices can be found at Plaça de Sant Jaume, Ciutat, 2 Ajuntament de Barcelona. (City Hall.) Opening time: Monday to Friday: 8.30am-8.30pm. Saturday: 9am-7pm. Sunday and public holidays: 9am-2pm.; Estació de Sants, Plaça dels Països Catalans. How to get there: Metro: L5,L3. Bus: 63,68. Opening time:  daily, 8am-8pm. and Aeroport del Prat. Terminal 1 and 2. Opening time: Daily, 9am-9pm.  All are closed on 1st January and 25th December. For a full list of tourist information points check the link above.

The department store El Corte Ingles publishes a free street map for tourists. You can pick a copy at the store, or at one of the many hotels in the city.
Turisme de Barcelona
```

Converts to http://i.imgur.com/6qB3Vz2.png 

All information from this {{listing}} is nowhere to be found after "infobox stage". I guess the part where we remove templates. 

Normal ```*``` lists are ok - we save them, to list array of section.

In short: 
We lose a lot of information about nice objects from {{}} templates - "do", "see" etc.

**Comment by Amantel** [comment]
From 

> if it's not a known template, but it's recursive, remove it

 pharse I guess somehow I should add this see,do,listings and few others as know templates.

**Comment by inquire** [comment]
@Amantel where did you add the listing in the i18n file? i wanted to parse those and they always get skipped, unless there is an update i'd happy try your workaround. :)

**Comment by spencermountain** [comment]
nice! 
yeah, just started this morning on handling custom-templates, like this:
```js
var wtf=require('wtf_wikipedia')
wtf.custom({
  listting:function(str){
   //do whatever you want here
  }
})
wtf.parse(myString)
//{sections:[...], custom:{listing:'myVal'}}
```
what do you guys think?

**Comment by spencermountain** [comment]
maybe it should be like this instead, so you can remove the template from the text, after parsing it
```js
  listing:function(templ, document)
    document=document.replace(templ, '')
  }
```

**Comment by Amantel** [comment]
@inquire SPOILER - this is super crude, @spencermountain is on creating better solution.
Still, the answer is:
wtf_wikipedia/src/data/i18n.js > add to i18n object array with the data (with templates) you want to parse. 
Like: 
```
  ,reginfo: [
    'do',
    'see',
    'listing'
  ]
```
It works, of cause, but requires much more tinkering.

BTW, this is how I hunt for pagebanner and regions (regions are special for wikivoyage, so do not mind them).

```
  //bannerhunting code
  var str = wiki;
  var re = /{{pagebanner\|(.*?)\|/;
  var foundBanners = re.exec(str);
  if (foundBanners && foundBanners.length > 1)
    r.pagebanner = foundBanners[1].replace(new RegExp(" ", 'g'), "_");
  //region gathering code
  str = wiki;
  re = /region\d*name=\[\[(.*?)\|/g;
  var foundRegions = re.exec(str);
  var regions = [];
```
This before ```wiki = preProcess(wiki);```

**Comment by Amantel** [comment]
@spencermountain  I like second solution :)

**Comment by inquire** [comment]
This works for now, but I think i will spend some time to look into ways of making this a bit more resilient and worth of a MR/PR

**Comment by Amantel** [comment]
@inquire That is exactly my idea. I think @spencermountain way will be a nice solution to this

**Comment by spencermountain** [comment]
yeah, i've made some progress on this *plugin/custom-templates* idea. it's on master, and you can see it running [here](https://github.com/spencermountain/wtf_wikipedia/blob/master/tests/custom.test.js) if you wanted to play with it. 
It needs some hardening and a could use a pair of eyes. I'm goin away for the weekend so will resume next week.
cheers

**Comment by spencermountain** [comment]
`.custom()` shipped in v2.2.0, check it out!
https://github.com/spencermountain/wtf_wikipedia#custom

**Comment by Amantel** [comment]
Sorry, for being late, but I can not make it work. Really sorry - I should tested it earlier. 
I better put it here, then create another issue.

From example: 
```
var str = `{{myTempl|cool data!}} Whistling is a sport in some countries...`;
wtf.custom({
  mine: (str) => {
    let m = str.match(/^\{\{myTempl\|(.+?)\}\}$/);
    if (m) {
      return m[1];
    }
  }
});
var r=wtf.parse(str)
console.log(r);
```

I get http://i.imgur.com/UYeqQEm.png (screen to save markdown)
In short - I am not sure this is what is wished for.
Cheers!

**Comment by spencermountain** [comment]
hey @Amantel , i think you're just missing a `r.custom`. it works [here](https://runkit.com/spencermountain/5a16033b011a2c0012519629)!

**Comment by Amantel** [comment]
It works there. It has to something with my setup then. I modify ./bin/parse.js and launch it. It is mostly the same (except first strings)
```
#!/usr/bin/env node

'use strict';
var wtf = require('../src/index');



var str = `{{myTempl|cool data!}} Whistling is a sport in some countries...`;
wtf.custom({
  mine: (str) => {
    let m = str.match(/^\{\{myTempl\|(.+?)\}\}$/);
    if (m) {
      return m[1];
    }
  }
});
var r=wtf.parse(str)
console.log(r.custom);
```
And get undefined. Weird.
