### ISSUE TITLE
Problem parsing sortable lists

### ISSUE THREAD

**Issue by alexmilde** [spencermountain/wtf_wikipedia#67]
thanks for this awesome parser. helped me a lot!

i ran into a problem parsing sortable lists:
eg.
https://en.wikipedia.org/wiki/List_of_largest_cities
i can access the "meta information" but not the content itself.

`wtf.from_api("List_of_largest_cities", "en", function(markup) {
  var data = wtf.parse(markup);
  console.log(data.sections[5].lists);
});`

not shure wether to file this as an issue or a feature request.
cheers and thanks for all your work

**Comment by spencermountain** [comment]
hey Alex, yeah you're right. Looks like it's getting tripped-up on that style syntax.
`| style="text-align:left" | content`
pretty doable. I can try it early next week. prs welcomed otherwise.
cheers

**Comment by alexmilde** [comment]
hey spencer,
thanks for the confirmation.
as im on holiday the next week am more than happy to wait :)

cheers

**Comment by spencermountain** [comment]
hey, know what, it just tripped-up because it is a very-long table, and there was some max-length set. I removed it, and now this is behaviour on master, and in the next version:
```js
wtf.from_api('List_of_largest_cities', 'en', function(markup) {
  var data = wtf.parse(markup);
  console.log(data.sections[5].tables[0][5]);
});
/*{ City: { text: 'Mumbai' },
  Nation: { text: '{{IND}}' },
  Image: { text: 'Worli_skyline_with_BSWL.jpg' },
  Population: { text: '21247844' },
  'col-4': { text: '21771200' },
  'col-5': { text: '22748395' } }
*/
```
cheers!
