### ISSUE TITLE
wiktionary

### ISSUE THREAD

**Issue by juanlanus** [spencermountain/wtf_wikipedia#7]
This is simply a question, before doing my own tests: is this library supposed to also parse the wiktionary entries?  
I didn't find any confirmation that the format is the same, besides the general messy appearance.

**Comment by spencermountain** [comment]
hey juan, yes this is a good question - it will do some parsing, the headings, links, etc. But i think wiktionary has a lot of good templates it could parse.

you can see it leaves a lot to be desired:
```wtf_wikipedia.from_api("nabob", 'enwiktionary', function(s){console.log(wtf_wikipedia.parse(s)) })
```
maybe we should look at better supporting this. What are the major templates you'd like?
cheers

**Comment by juanlanus** [comment]
Hi Spencer,
Thanks for being so helpful so quickly!

I don't know yet about the *templates* thing, so in short what I need for
now is to enumerate the acceptions of a word grouping nouns, verbal forms,
and *other*.
Can't tell, for now, the templates involved. Where do I study about them?

I'm about to build a JS app for browsers to add tags to the words pointing
to their specific meaning in the current context (as opposed to show *all* the
word meanings and let the reader find out which is the good one.

Regards,
--
Juan

**Comment by spencermountain** [comment]
hey, cool. the word-sense problem is a great one to crack.
Yeah, if you could, go to a wiktionary page for something you'd like, then click edit, and take a look at how the data you'd like is structured. templates are just things in {{curly quotes}}. 
wiktionary, as you said, is really messy. I'm not very familiar with it, but i'm happy to add some support for it
cheers

**Comment by juanlanus** [comment]
Oh "that" templates, like mustache and so on!
OK, will try to do something.
Yes, I can scratch some pieces of a page, my problem is that I'm always
afraid of unknowingly losing interesting parts of the data.
..

**Comment by spencermountain** [comment]
hey juan, I've added some quite complicated support for `term, ipa, sense, translation, and etyl` templates, it's on master, but i haven't published to npm yet. Let me know if you find any issues. I imaging there are A LOT! ;)
