### ISSUE TITLE
Saving info about wiki/language and article in main object

### ISSUE THREAD

**Issue by Amantel** [spencermountain/wtf_wikipedia#70]
Hello! 

What do you think about saving both input parameters (article and wiki/language) at main object, or should it be done outside this library?

**Comment by Amantel** [comment]
Created a pr on this

**Comment by spencermountain** [comment]
💥 💪

**Comment by spencermountain** [comment]
hey, sorry about that. got mixed-up with the custom stuff.
fixed in `wtf_wikipedia@2.2.1`
