### ISSUE TITLE
support Links with #Hash anchors

### ISSUE THREAD

**Issue by fractalien** [spencermountain/wtf_wikipedia#84]
There is a Wikipedia-internal link with an anchor link in the first paragraph of the DE article for "Köln", like [[a#b|c]] (see the API output [here](https://de.wikipedia.org/w/api.php?action=query&prop=revisions&rvlimit=1&rvprop=content&format=json&origin=*&titles=K%C3%B6ln) and search for "Gemeinden"). Contrary to expectation, this does not get properly parsed as "c" but is essentially returned as it is.

**Comment by spencermountain** [comment]
ah, nice find.

**Comment by xeladotbe** [comment]
Hey @spencermountain, any news? Had the same problem with "Albert Einstein (DE)"
```

let fragment = wtf('Durch Geburt besaß er die [[Königreich Württemberg|württembergische]] [[Deutsche Staatsangehörigkeit#Rechtspolitische Geschichte der deutschen Staatsangehörigkeit|Staatsbürgerschaft]].')

fragment.text()

```
returns 'Durch Geburt besaß er die württembergische [[Deutsche Staatsangehörigkeit#Rechtspolitische Geschichte der deutschen Staatsangehörigkeit|Staatsbürgerschaft]].'

**Comment by spencermountain** [comment]
oh my goodness, this german+wikiscript combo is doing me in!

@fractalien's original `[[a#b|c]]` is working already, it seems that link fails because the annchor text is so long.

**Comment by xeladotbe** [comment]
Found another (long) link! :)

`[[Liste der Städte und Gemeinden in Nordrhein-Westfalen#Größte und kleinste Kommunen|bevölkerungsreichste Stadt]]`

**Comment by spencermountain** [comment]
yeah, this one didn't make it in the current release. 
these links are amazing. we should support them. lemme know if you find some others

**Comment by spencermountain** [comment]
got this example working now - `5.3.0`
