### ISSUE TITLE
redirects in image url paths

### ISSUE THREAD

**Issue by ben-lei** [spencermountain/wtf_wikipedia#86]
For example when I get the page "Cross_Game" the image URL "https://upload.wikimedia.org/wikipedia/commons/7/71/Cross_Game_v01_cover_by_Mitsuru_Adachi.jpg" is provided, when it should really be "https://upload.wikimedia.org/wikipedia/en/7/71/Cross_Game_v01_cover_by_Mitsuru_Adachi.jpg"

What do I have to do to get the real URL of the image(s) from a Wikipedia page?

**Comment by spencermountain** [comment]
hi Ben, thanks. good find.
rats, i'm not sure how to tell when an image is in the commons, and when it's in the en namespace - 
do you know how wide-spread this problem is?

**Comment by ben-lei** [comment]
I'm not sure, was using your module for the first time when I noticed this.

**Comment by niebert** [comment]
```Images Download ___wget___```

* The link https://en.wikipedia.org/wiki/Special:Redirect/file/Annweiler_Rathaus.JPG refers to the current version of the image Annweiler_Rathaus.JPG.
* Size of image can be determined by http://en.wikipedia.org/wiki/Special:FilePath/Annweiler_Rathaus.JPG?width=300 (here resize the width to 300 pixels.

**Comment by spencermountain** [comment]
oh hey! @niebert should we change all our image links to point at `Special:Redirect`?

that worked for all the examples I tried!

any objections to this, from the others?

**Comment by spencermountain** [comment]
i can't believe how good this is.
I think we can remove that insane crypto library we're depending on, to do this image path stuff ourselves
nice find @niebert !!

**Comment by niebert** [comment]
Thank you, just a minor contribution to your great library, Spencer.

**Comment by spencermountain** [comment]
;) got paragraph support working for ya on the dev branch. Almost ready!

**Comment by spencermountain** [comment]
all images now point to the redirect url in `6.0.0`.
please let me know if anybody finds some funky image urls that don't work.
cheers
