### ISSUE TITLE
<onlyinclude> is not parsed away

### ISSUE THREAD

**Issue by fractalien** [spencermountain/wtf_wikipedia#87]
A part of [this article](https://de.wikipedia.org/wiki/Gerhard_Gruber) is enclosed in `<onlyinclude>...</onlyinclude>`. But the parse function keeps these tags as such in the sentences.

I should probably add that, prior to parsing, I remove the disambiguation tag (`{{Begriffsklärung}}`) because I want the options' descriptions, not just a list of links. When I try using the disambiguation parsing, those links are missing the first one, perhaps because of the `<onlyinclude>` that precedes the first "*".

**Comment by spencermountain** [comment]
Yeah, the dev branch is gonna be smarter about disambiguation pages. Current results are pretty weird.

What is onlyinclude supposed to do, in a perfect world?

**Comment by fractalien** [comment]
It looks like in a perfect world, this would only exist in templates, not articles, as [described here](https://en.wikipedia.org/wiki/Help:Template#Noinclude,_includeonly,_and_onlyinclude). Apparently it's possible to prevent parts of a template from being used in instantiation, and "onlyinclude" means that nothing except the enclosed part will be used.

**Comment by spencermountain** [comment]
as we don't support transclusion #223 i'm not sure we're ever gonna be able to detect the context that a page is running. 

the current behaviour is to not remove any content. (but remove the tags)

will close for now, open to suggestions for how to implement this in the future.
thanks
